### PR TITLE
Fix: Deprecate implicit `file:` protocol and only allow package dirs

### LINKED ISSUE #4251: `yarn add jest@test` fails if `test` is a folder
Repro:

```
mkdir test
yarn add jest@test
# node_modules/jest is ../test
```

### PR DESCRIPTION
**Pull request by BYK**
**Summary**

Fixes #4251. Follow up to #4088. Instead of just checking whether the
target is a valid directory, we now check if it contains a
`package.json` file too. This is still different from `npm`'s behavior.
Apparently, `npm` fetches the package info upfront to favor dist-tags
over directories but this comes at a distinct performance penalty and
makes static, deterministic resolution impossible so we are now
deprecating the implicit `file:` protocol in patterns. After a certain
point, we'll remove this code and will require everyone to use `file:`
or at least one of the following path identifiers: `./`, `../`. `/`.

**Test plan**

Updated the existing test for warning check and added a new test for
invalid directories.

### CODE REVIEW

File: src/package-request.js [hunk 1]
```diff
@@ -5,6 +5,12 @@ import type PackageResolver from './package-resolver.js';
 import type {Reporter} from './reporters/index.js';
 import type Config from './config.js';
 import type {Install} from './cli/commands/install';
+
+import path from 'path';
+
+import invariant from 'invariant';
+import semver from 'semver';
```
Comment (arcanis) [inline src/package-request.js]: Be careful with this, I think some of our third-party modules (or their dependencies) are sometimes mocked in our tests, so using import will break them. Case in mind: `request`.

File: src/resolvers/exotics/file-resolver.js [hunk 2]
```diff
@@ -23,6 +23,11 @@ export default class FileResolver extends ExoticResolver {
   loc: string;
 
   static protocol = 'file';
+  static prefixMatcher = /^.{,2}\//;
+
+  static isVersion(pattern: string): boolean {
+    return super.isVersion.call(this, pattern) || this.prefixMatcher.test(pattern);
```
Comment (arcanis) [inline src/resolvers/exotics/file-resolver.js]: Maybe update the regex to also match `C:\...` ?

Comment (BYK) [reply src/resolvers/exotics/file-resolver.js]: Hmm, good catch. I'll go with [path.isAbsolute](https://nodejs.org/api/path.html#path_path_isabsolute_path) which takes care of it for me.

File: src/resolvers/exotics/file-resolver.js [hunk 3]
```diff
@@ -23,6 +24,11 @@ export default class FileResolver extends ExoticResolver {
   loc: string;
 
   static protocol = 'file';
+  static prefixMatcher = /^.{1,2}\//;
```
Comment (dylang) [inline src/resolvers/exotics/file-resolver.js]: Oops, looks like the `.` isn't escaped, so it's matching _any_ two characters, including single-character scopes like `@m`.

I have a fix here: https://github.com/yarnpkg/yarn/pull/4338

**Comment by sheerun** [comment]
Unfortunately this breaks possibility to install local packages without package.json #3855 :(

**Comment by BYK** [comment]
@sheerun - yeah that was kind of intentional since this caused lots of headaches and I think this is safer. Is it too much trouble to require people to have a simple `package.json` for local packages?

**Comment by sheerun** [comment]
For non-npm packages (like bower's or assets) there isn't package.json available. Also checking for package.json won't solve #4251 if `test` directory contains package.json (likely to happen).

The real fix would be to require local dependencies to have `../`, `./`, `/`, or `file:` prepended, just like you noticed. I'd agree that package.json requirement could be enforced when they aren't present.

**Comment by BYK** [comment]
So, we are doing both right now if I'm not wrong. Are you suggesting making it an either / or check?

**Comment by sheerun** [comment]
Yes, either correct path format, or package.json :) But rather deprecate incorrect path next major

**Comment by BYK** [comment]
@sheerun you have angered the open source gods and now they want a PR. Are you up to the challenge?
