### PR TITLE
Set UID and GID of untared files to zero if user is root

### LINKED ISSUE #1750: `yarn install` fails inside a Docker Container with `--userns-remap` enabled
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Running `yarn install` in a Docker container with the daemon having `--userns-remap` enabled fails with the following:

```
  Error: https://registry.yarnpkg.com/immutable/-/immutable-3.8.1.tgz: EINVAL: invalid argument, chown '/root/.yarn-cache/npm-immutable-3.8.1/package.json'
      at Error (native)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Start the Docker daemon with  [`--userns-remap`](https://docs.docker.com/engine/reference/commandline/dockerd/#/detailed-information-on-subuidsubgid-ranges) enabled.

Then try to run or build a Docker image with `yarn install`:

```
# Inside the Docker container
$ id
uid=0(root) gid=0(root) groups=0(root)
$ strace -o strace.log -ff yarn install
$ tail yarn-error.log 
Trace: 
  Error: https://registry.yarnpkg.com/immutable/-/immutable-3.8.1.tgz: EINVAL: invalid argument, chown '/root/.yarn-cache/npm-immutable-3.8.1/package.json'
      at Error (native)
$ grep chown strace.log.*
strace.log.202:chown("/root/.yarn-cache/npm-bowser-1.4.6/package.json", 502, 20) = 0
strace.log.202:chown("/root/.yarn-cache/npm-bowser-1.4.6/.npmignore", 502, 20) = 0
strace.log.202:chown("/root/.yarn-cache/npm-alt-utils-1.0.0/package.json", 501, 20) = 0
strace.log.202:chown("/root/.yarn-cache/npm-immutable-3.8.1/package.json", 116435139, 1876110778) = -1 EINVAL (Invalid argument)
strace.log.202:chown("/root/.yarn-cache/npm-bowser-1.4.6/LICENSE", 502, 20) = 0
strace.log.202:chown("/root/.yarn-cache/npm-react-15.3.2/package.json", 616931727, 1876110778) = -1 EINVAL (Invalid argument)
strace.log.202:chown("/root/.yarn-cache/npm-alt-0.18.6/package.json", 502, 20) = 0
strace.log.202:chown("/root/.yarn-cache/npm-react-addons-css-transition-group-15.3.2/package.json", 616931727, 1876110778) = -1 EINVAL (Invalid argument)
strace.log.202:chown("/root/.yarn-cache/npm-numeral-1.5.3/package.json", 501, 20) = 0
strace.log.203:chown("/root/.yarn-cache/npm-alt-utils-1.0.0/lib/ActionListeners.js", 501, 20) = 0
strace.log.203:chown("/root/.yarn-cache/npm-alt-utils-1.0.0/lib", 501, 20) = 0
strace.log.204:chown("/root/.yarn-cache/npm-moment-2.15.1/package.json", 1000, 1000) = 0
strace.log.204:chown("/root/.yarn-cache/npm-react-addons-update-15.3.2/package.json", 616931727, 1876110778) = -1 EINVAL (Invalid argument)
strace.log.205:chown("/root/.yarn-cache/npm-bowser-1.4.6/README.md", 502, 20) = 0
strace.log.205:chown("/root/.yarn-cache/npm-alt-utils-1.0.0/.npmignore", 501, 20) = 0
strace.log.205:chown("/root/.yarn-cache/npm-classnames-2.2.5/package.json", 501, 20) = 0
strace.log.205:chown("/root/.yarn-cache/npm-lodash-4.16.4/package.json", 501, 20) = 0

```

I am running `--userns-remap=teamcity:teamcity` with the following information:
```
$ id teamcity
uid=1001(teamcity) gid=1001(teamcity) groups=1001(teamcity),999(docker)
$ cat /etc/subuid
ubuntu:100000:65536
teamcity:165536:65536
$ cat /etc/subgid
ubuntu:100000:65536
teamcity:165536:65536
```

**What is the expected behavior?**
Successful installation

I believe this is the same issue encountered in #1485, #918 and #869. If I do `npm install`, it installs successfully. 

If I run the container with `--userns=host`, it runs successfully. So I can only conclude this issue is due to the Linux user namespace.

**Please mention your node.js, yarn and operating system version.**
```
$ node --version
v6.7.0
$ uname -a
Linux 2970f7786932 3.13.0-100-generic #147-Ubuntu SMP Tue Oct 18 16:48:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

strace:
 - [Relevant extract from one of the `package.json`](http://pastebin.com/Ci4mXZKS)

### PR DESCRIPTION
**Pull request by lawliet89**
**Summary**

Fixes #1750 

`TarballFetcher` uses [`tar`](https://github.com/npm/node-tar) to untar tarballs. `tar` in turn constructs a [`Writer`](https://github.com/npm/fstream/blob/24fabdec32e334dd3b130d77b38c010e3119b102/lib/writer.js#L26) object per entry in the tarball, preserving the original UID and GID in the tarball.

If `Writer` detects that the UID of the user is 0 (i.e. root user), it will attempt to [`chown`](https://github.com/npm/fstream/blob/24fabdec32e334dd3b130d77b38c010e3119b102/lib/writer.js#L195) the extracted file to the UID. 

Usually, this is not a problem. However, as in #1750 and other issues, if the _`root`_ user is not really root but inside a [user namespace](http://man7.org/linux/man-pages/man7/user_namespaces.7.html), and the UID is outside the [`subuid`](http://man7.org/linux/man-pages/man5/subuid.5.html) range of the mapped user, then it will fail. This is the same issue for GID.

This PR attempts to just set everything to UID 0 if the user is detected as root, regardless of whether the root is inside a namespace or not.

**Test plan**

First, configure Docker Daemon with [user namespace enabled](https://docs.docker.com/engine/reference/commandline/dockerd/#/daemon-user-namespace-options).

Consider the `Dockerfile`, `package.json`, and `yarn.lock` from [this gist](https://gist.github.com/lawliet89/891fb64540b94f4831409bf6905d8661).

```bash
$ docker build -t test .
Sending build context to Docker daemon 29.34 MB
Step 1 : FROM node:7.1
7.1: Pulling from library/node
386a066cd84a: Pull complete 
75ea84187083: Pull complete 
88b459c9f665: Pull complete 
1e3ee139a577: Pull complete 
bd2400e7d880: Pull complete 
b8c6812ba469: Pull complete 
1882bd83135c: Pull complete 
Digest: sha256:873c24bdb94e9b198bbec3c298fb7b2dfc64bce7b2dea71348b62f47814e16fb
Status: Downloaded newer image for node:7.1
 ---> f5eca816b45d
Step 2 : RUN set -x     && sudo curl https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -     && echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list     && sudo apt-get update && sudo apt-get install yarn
 ---> Running in a6b6c803751f
+ sudo curl https://dl.yarnpkg.com/debian/pubkey.gpg
/bin/sh: 1: sudo: not found
+ sudo apt-key add -
/bin/sh: 1: sudo: not found
The command '/bin/sh -c set -x     && sudo curl https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -     && echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list     && sudo apt-get update && sudo apt-get install yarn' returned a non-zero code: 127
yongwen@yongwen-Thinkpad:~/work/scratch/yarn-ns$ docker build -t test .
Sending build context to Docker daemon 29.34 MB
Step 1 : FROM node:7.1
 ---> f5eca816b45d
Step 2 : RUN set -x     && curl https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -     && echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list     && apt-get update && sudo apt-get install yarn
 ---> Running in 0e0b66e20a42
+ curl https://dl.yarnpkg.com/debian/pubkey.gpg
+ apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7453  100  7453    0     0  19369      0 --:--:-- --:--:-- --:--:-- 19408
OK
+ tee /etc/apt/sources.list.d/yarn.list
+ echo deb http://dl.yarnpkg.com/debian/ stable main
+ apt-get update
deb http://dl.yarnpkg.com/debian/ stable main
Get:1 http://dl.yarnpkg.com stable InRelease [2464 B]
Get:2 http://dl.yarnpkg.com stable/main amd64 Packages [881 B]
Get:3 http://security.debian.org jessie/updates InRelease [63.1 kB]
Ign http://deb.debian.org jessie InRelease
Get:4 http://security.debian.org jessie/updates/main amd64 Packages [403 kB]
Get:5 http://deb.debian.org jessie-updates InRelease [145 kB]
Get:6 http://deb.debian.org jessie Release.gpg [2373 B]
Get:7 http://deb.debian.org jessie-updates/main amd64 Packages [17.6 kB]
Get:8 http://deb.debian.org jessie Release [148 kB]
Get:9 http://deb.debian.org jessie/main amd64 Packages [9064 kB]
Fetched 9847 kB in 4s (2072 kB/s)
Reading package lists...
+ sudo apt-get install yarn
/bin/sh: 1: sudo: not found
The command '/bin/sh -c set -x     && curl https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -     && echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list     && apt-get update && sudo apt-get install yarn' returned a non-zero code: 127
yongwen@yongwen-Thinkpad:~/work/scratch/yarn-ns$ docker build -t test .
Sending build context to Docker daemon 29.34 MB
Step 1 : FROM node:7.1
 ---> f5eca816b45d
Step 2 : RUN set -x     && curl https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -     && echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list     && apt-get update && apt-get install yarn
 ---> Running in 5dc048773191
+ curl https://dl.yarnpkg.com/debian/pubkey.gpg
+ apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7453  100  7453    0     0  95426      0 --:--:-- --:--:-- --:--:-- 95551
OK
+ echo deb http://dl.yarnpkg.com/debian/ stable main
+ tee /etc/apt/sources.list.d/yarn.list
+ apt-get update
deb http://dl.yarnpkg.com/debian/ stable main
Get:1 http://dl.yarnpkg.com stable InRelease [2464 B]
Get:2 http://dl.yarnpkg.com stable/main amd64 Packages [881 B]
Get:3 http://security.debian.org jessie/updates InRelease [63.1 kB]
Ign http://deb.debian.org jessie InRelease
Get:4 http://security.debian.org jessie/updates/main amd64 Packages [403 kB]
Get:5 http://deb.debian.org jessie-updates InRelease [145 kB]
Get:6 http://deb.debian.org jessie Release.gpg [2373 B]
Get:7 http://deb.debian.org jessie-updates/main amd64 Packages [17.6 kB]
Get:8 http://deb.debian.org jessie Release [148 kB]
Get:9 http://deb.debian.org jessie/main amd64 Packages [9064 kB]
Fetched 9847 kB in 3s (2992 kB/s)
Reading package lists...
+ apt-get install yarn
Reading package lists...
Building dependency tree...
Reading state information...
Recommended packages:
  nodejs
The following NEW packages will be installed:
  yarn
0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
Need to get 1817 kB of archives.
After this operation, 28.1 MB of additional disk space will be used.
Get:1 http://dl.yarnpkg.com/debian/ stable/main yarn all 0.17.0-1 [1817 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 1817 kB in 1s (1446 kB/s)
Selecting previously unselected package yarn.
(Reading database ... 21208 files and directories currently installed.)
Preparing to unpack .../archives/yarn_0.17.0-1_all.deb ...
Unpacking yarn (0.17.0-1) ...
Setting up yarn (0.17.0-1) ...
 ---> 7d0fb09b8fc4
Removing intermediate container 5dc048773191
Step 3 : WORKDIR /src/app
 ---> Running in 445c55f260da
 ---> f4364d2bb0a4
Removing intermediate container 445c55f260da
Step 4 : COPY package.json yarn.lock ./
 ---> c97301d73473
Removing intermediate container 1217afe9a60e
Step 5 : RUN yarn install
 ---> Running in 11685338da3d
yarn install v0.17.0
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/immutable/-/immutable-3.8.1.tgz: EINVAL: invalid argument, chown '/root/.cache/yarn/npm-immutable-3.8.1-200807f11ab0f72710ea485542de088075f68cd2/package.json'".
info If you think this is a bug, please open a bug report with the information provided in "/src/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn install' returned a non-zero code: 1
```

With this patch, the build will be successful.

### CODE REVIEW

**Comment by bestander** [comment]
Looks more elegant than cmodding all files after they are extracted.
Can you just address one comment? And let's merge it.

File: src/constants.js [hunk 1]
```diff
@@ -86,3 +86,16 @@ export function getPathKey(platform: string, env: Env): string {
...
+  if (process.platform !== 'win32' && process.getuid) {
+    return process.getuid();
+  }
+  return null;
+}
+
+export const ROOT_USER = isRootUser(process.platform, getUid());
+
+export function isRootUser(platform: string, uid: ?number): boolean {
+  return platform !== 'win32' && uid === 0;
```
Comment (lawliet89) [inline src/constants.js]: I will remove the extraneous check.

**Comment by andrewmclagan** [comment]
ah cool, going to run this on CircleCI on Monday as a number of users experience this issue.

**Comment by amasad** [comment]
Tried this on CircleCI and it works! (Thanks to @Daniel15) I hope this lands on stable soon.
