### PR TITLE
Do not use /usr/local/share as home under fakeroot

### LINKED ISSUE #2536: Yarn fakeroot problems
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I have a Debian package that invokes Yarn during the install step.

Under Yarn 0.18.1 and previous versions, this worked fine. Starting with Yarn 0.19.1, it fails:

```
dh binary
   dh_testroot
   dh_prep
   dh_auto_install
make[2]: Entering directory `<http://jenkins:8080/job/Nightly/ws/build-area/package-2.0.2'>
make install
yarn  --pure-lockfile
/usr/share/yarn/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/usr/local/share/.cache'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at sync (/usr/share/yarn/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/share/yarn/node_modules/mkdirp/index.js:77:24)
    at Object.<anonymous> (/usr/share/yarn/bin/yarn.js:30:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

`fakeroot yarn add lodash`

**What is the expected behavior?**

`fakeroot yarn` should work as well as running `yarn` by itself does.

I believe that this issue was introduced by #2150. Since fakeroot is [commonly used](http://manpages.ubuntu.com/manpages/zesty/man1/debuild.1.html#contenttoc5) in building Debian packages, 

fakeroot sets the `FAKEROOTKEY` environment variable (see [here](http://manpages.ubuntu.com/manpages/precise/man1/fakeroot-tcp.1.html)), so one possible fix is to only switch to `/usr/local/share` if `isRootUser(getUid()) && process.env.FAKEROOTKEY == null`.

**Please mention your node.js, yarn and operating system version.**

Node 6.9.4
Yarn 0.19.1
Ubuntu 14.04

### PR DESCRIPTION
**Pull request by Tebro**
Fixes #2536

**Summary**

When packaging software that uses yarn for dependency management, some distributions use fakeroot as a part of their build system (my case, Solus OS). 

What happens is that the uid is set to 0, and because of that yarn tried to use /usr/local/share as the home directory. When yarn tried to create this directory it fails, because the user is not really root and does not have the permissions. 

This added check makes sure that we use the right home directory when running under fakeroot  

**Test plan**

This is what was executed (in the yarn codebase) to prove the difference:

With current yarn:

```
 ~/tmp/yarn $ fakeroot yarn
/usr/lib64/node_modules/yarn/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/usr/local'
    at Object.fs.mkdirSync (fs.js:895:18)
    at sync (/usr/lib64/node_modules/yarn/node_modules/mkdirp/index.js:71:13)
    at sync (/usr/lib64/node_modules/yarn/node_modules/mkdirp/index.js:77:24)
    at sync (/usr/lib64/node_modules/yarn/node_modules/mkdirp/index.js:77:24)
    at Function.sync (/usr/lib64/node_modules/yarn/node_modules/mkdirp/index.js:77:24)
    at Object.<anonymous> (/usr/lib64/node_modules/yarn/bin/yarn.js:31:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

and with the modified yarn:

```
 ~/tmp/yarn $ fakeroot bin/yarn 
yarn install v0.28.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.1.1: The platform "linux" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "ajv-keywords@1.5.1" has incorrect peer dependency "ajv@>=4.10.0".
warning "eslint-config-fbjs@2.0.0-alpha.1" has incorrect peer dependency "babel-eslint@^7.1.1".
[5/5] Building fresh packages...
Done in 2.48s.
```

### CODE REVIEW

**Comment by arcanis** [comment]
I'm not familiar with `fakeroot` but I don't understand something. Shouldn't creating the share folder work? According to the documentation it should:

```
       Here is an example session with fakeroot.  Notice that inside the  fake
       root  environment  file manipulation that requires root privileges suc-
       ceeds, but is not really happening.
```

**Comment by Tebro** [comment]
I am not familiar with it either, it is used in Solus build system, and this combination made yarn commands fail. This was encountered in the build system, but the commands listed in the Test plan above were run "normally".

File: src/util/user-home-dir.js [hunk 1]
```diff
@@ -4,7 +4,11 @@ import ROOT_USER from './root-user.js';
 
 const path = require('path');
 
+const isNotFakeRoot = typeof process.env.FAKEROOTKEY === 'undefined';
```
Comment (BYK) [inline src/util/user-home-dir.js]: Why not just `Boolean(process.env.FAKEROOTKEY)`?

Comment (BYK) [inline src/util/user-home-dir.js]: Also, I'd argue that this check should go into `./root-user.js`

Comment (Tebro) [inline src/util/user-home-dir.js]: I can understand the recommendation for `Boolean(...)` but as to moving the check into `root-user.js` I am not sure if I agree. It would make the imported `ROOT_USER` contain the combination of two checks, which at least from the current naming is not directly clear what exactly it is checking.

Comment (BYK) [inline src/util/user-home-dir.js]: Agree with the concern but looks like `ROOT_USER` is only used here and with the assumption of root permissions so probably it's a good idea to put it there. @bestander @arcanis thoguhts?

Comment (Tebro) [inline src/util/user-home-dir.js]: No I see, and agree with your point. Will add that change as well.

**Comment by arcanis** [comment]
Are the packages generated by this fakeroot build supposed to be installed on a per-user basis, or on the whole system? (in the second case, we *do* want to use `/usr/local`)

**Comment by BYK** [comment]
@arcanis sorry I missed your message. Please block the PR if you have concerns.

**Comment by Tebro** [comment]
This should affect Debian packaging as well as Solus. We build the packages in a container, and the files that end up in the actual package are placed in a specific directory, $installdir. 

So let's say we have an application like the Atom editor. It would be built from source in the container, and the resulting build artifacts are placed in $installdir. For example the main binary would be placed in $installdir/usr/bin/atom. 

When the package is installed on a Solus installation the package manager would then unpack the files that were place in $installdir into their correct locations. (/usr/bin/atom for the example above)

**Comment by Tebro** [comment]
@arcanis @BYK do you have further concerns about this?

**Comment by BYK** [comment]
I don't. Was waiting for @arcanis to jump in if he had any more concerns but I'm assuming he's okay for now. Merging.
