### PR TITLE
Set boolean config values correctly

### LINKED ISSUE #2434: yarn config set does not allow to set boolean false
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`yarn config set strict-ssl false` sets it to string 'false' instead of boolean false. In consequence, 'false' seems to be treated as truthy and has no effect.

**If the current behavior is a bug, please provide the steps to reproduce.**
see http://stackoverflow.com/questions/41439008/how-do-you-set-boolean-values-with-yarn-config

**Expected behaviour**
The config value should have been set to boolean false.

### PR DESCRIPTION
**Pull request by iredchuk**
* Fixes #2434

`yarn config set [option] [false|true]` 
should set the option value to false/true respectively. 
Currently it's set to string value "false"/"true".

*Test Plan*
* `yarn config set strict-ssl false`
* $HOME/.yarnrc should contain the line:
   strict-ssl false

### CODE REVIEW

File: src/cli/commands/config.js [hunk 1]
```diff
@@ -19,8 +20,8 @@ export const {run, setFlags} = buildSubCommands('config', {
     if (args.length === 0 || args.length > 2) {
       return false;
     }
-
-    const [key, val = true] = args;
+    const key = args[0];
+    const val = BaseRegistry.normalizeConfigOption(args[1] || true);
```
Comment (torifat) [inline src/cli/commands/config.js]: Isn't it better to use `yarnConfig` without importing `BaseRegistry`?

Comment (iredchuk) [inline src/cli/commands/config.js]: Well, can't use it directly - it's static in BaseRegistry, or do mean something else?

Comment (iredchuk) [inline src/cli/commands/config.js]: But maybe it's better to ensure config is normalized in yarn-registry's `saveHomeConfig` from the dependency prospective?

**Comment by OACDesigns** [comment]
this PR has introduced a regression (https://github.com/yarnpkg/yarn/issues/2856).
Setting a value to an empty string now results in defaulting to a boolean `true`
