### PR TITLE
Fix self-update

### LINKED ISSUE #612: self-update throws error
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

```bash
yarn self-update v0.15.0
error OAuth2 authentication requires a token or key & secret to be set
    at __dirname.authenticate (/Users/danieltschinder/.yarn/node_modules/github/lib/index.js:334:23)
    at Object.<anonymous> (/Users/danieltschinder/.yarn/lib-legacy/cli/commands/self-update.js:36:12)
    at next (native)
    at step (/Users/danieltschinder/.yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/danieltschinder/.yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (/Users/danieltschinder/.yarn/node_modules/core-js/library/modules/es6.promise.js:191:7)
    at Object.<anonymous> (/Users/danieltschinder/.yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at Object.run (/Users/danieltschinder/.yarn/lib-legacy/cli/commands/self-update.js:105:17)
    at run (/Users/danieltschinder/.yarn/lib-legacy/cli/index.js:249:18)
    at /Users/danieltschinder/.yarn/lib-legacy/cli/index.js:357:12
info Visit http://yarnpkg.com/en/docs/cli/self-update for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```bash
❯ yarn self-update
```

**What is the expected behavior?**

Update

**Please mention your node.js, yarn and operating system version.**

node 4.6.0
yarn 0.15.0
macOS 10.12.0

### PR DESCRIPTION
**Pull request by danez**
This fixes self-update by doing:

* enable the tests
* use npm run build in the test instad of make build
* invalidated roadrunner cache, so that the symlink to `current` gets reevaluated
* do not do the request to github for the assets as they are already included in the release response
* pick the correct asset from the asset list by doing a name-check (content-type is sometimes set to octet-stream for the tar file, so we can't use that)

The roadrunner change is necessary as the tests need to invalidate the path cache so that the next test can reevaluate the symlinks. Same for the actual self-update command which also changes the symlink. This depends on kittens/roadrunner#1

Fixes #612 

Docs: https://github.com/yarnpkg/website/pull/173

### CODE REVIEW

**Comment by danez** [comment]
This uses now a patched version of roadrunner see kittens/roadrunner#1 and resets roadrunner correctly
The only bad thing is that I add the roadrunner cache file to constants, but I can't use it in the bin as it is not yet sure which version of the constants to load: modern/legacy.

**Comment by bestander** [comment]
Nice!
Should we wait for roadrunner fix to be propagated to upstream?

**Comment by danez** [comment]
Yes I think so @kittens, can you have a look at kittens/roadrunner#1 ?

File: src/constants.js [hunk 1]
```diff
@@ -38,6 +38,7 @@ export function getModuleCacheDirectory(): string {
 export const MODULE_CACHE_DIRECTORY = getModuleCacheDirectory();
 export const LINK_REGISTRY_DIRECTORY = `${MODULE_CACHE_DIRECTORY}/.link`;
 export const GLOBAL_MODULE_DIRECTORY = `${MODULE_CACHE_DIRECTORY}/.global`;
+export const CACHE_FILENAME = path.join(userHome, '.yarn', '.roadrunner.json');
```
Comment (danez) [inline src/constants.js]: I would like to use this variable in `bin/yarn.js`. But there i cannot simple import this file right? currently this is duplicate here and in `bin/yarn.js`

File: __tests__/commands/self-update.js [hunk 2]
```diff
@@ -59,32 +62,31 @@ function run(checks: (reporter: reporters.Reporter, config: Config) => Promise<v
...
   });
 });
 
 
-xit('Self-update should work from self-updated location', (): Promise<void> => {
+it('Self-update should work from self-updated location', (): Promise<void> => {
   return run(async (reporter, config) => {
     // mock an existing self-update
-    await child.exec('make build');
+    await child.exec('npm run build');
```
Comment (danez) [inline __tests__/commands/self-update.js]: It is probably safe to assume that npm is available when running tests?

File: __tests__/commands/self-update.js [hunk 3]
```diff
@@ -59,32 +62,31 @@ function run(checks: (reporter: reporters.Reporter, config: Config) => Promise<v
...
+    await selfUpdate(config, reporter, {}, ['v0.14.1']);
     expect(await fs.exists(path.resolve(updatesFolder, 'current')));
-    expect(await fs.exists(path.resolve(updatesFolder, 'v0.11.0')));
+    expect(await fs.exists(path.resolve(updatesFolder, 'v0.14.1')));
     const packageJson = await fs.readJson(path.resolve(updatesFolder, 'current', 'package.json'));
-    expect(packageJson.version === '0.11.0');
+    expect(packageJson.version === '0.14.1');
     const version = await child.exec('node bin/yarn.js -V');
-    expect(version[0].trim(), `0.11.0`);
+    expect(version[0].trim(), '0.14.1');
```
Comment (danez) [inline __tests__/commands/self-update.js]: Had to update the version as <0.14 was using the name `kpm` in the release

File: __tests__/commands/self-update.js [hunk 4]
```diff
@@ -93,15 +95,15 @@ xit('Self-update should work from self-updated location', (): Promise<void> => {
...
 
     // new version is current
     version = await child.exec('node bin/yarn.js -V');
-    expect(version[0].trim(), `0.11.0`);
+    expect(version[0].trim(), '0.15.0');
 
     expect(await fs.exists(path.resolve(updatesFolder, 'v0.98.0'))).toBe(false);
     expect(await fs.exists(path.resolve(updatesFolder, 'v0.99.0'))).toBe(true);
-    expect(await fs.exists(path.resolve(updatesFolder, 'v0.11.0'))).toBe(true);
+    expect(await fs.exists(path.resolve(updatesFolder, 'v0.15.0'))).toBe(true);
```
Comment (danez) [inline __tests__/commands/self-update.js]: Here is use 0.15 to check it picks the correct asset.

File: __tests__/commands/self-update.js (hunk 2 above)
Comment (bestander) [inline __tests__/commands/self-update.js]: Can we do "kpm run build"? :)
For now, yeah, we can assume it is safe

File: src/constants.js (hunk 1 above)
Comment (bestander) [inline src/constants.js]: .yarn is prone to change afaik.
There should be a constant with the folder name

File: __tests__/commands/self-update.js (hunk 2 above)
Comment (bestander) [inline __tests__/commands/self-update.js]: Oh yeah, kpm has been engraved in my brain now :)

File: src/constants.js (hunk 1 above)
Comment (danez) [inline src/constants.js]: I can extract that to an other constant, but then still it wouldn't be usable in `bin/yarn.js` I think.

**Comment by Daniel15** [comment]
I think we can remove all the Github API stuff from this. Instead of using the Github API, you can hit https://yarnpkg.com/latest-version to get the version number. Then you can simply hit https://yarnpkg.com/latest.tar.gz to get the latest tarball. Much simpler 😄  . There's also `https://yarnpkg.com/downloads/{version}/{file}` for specific version.

**Comment by bestander** [comment]
Good point, @Daniel15, dropping Github wrapper from dependencies is good for size and startup performance.
Limiting self-update to `latest` is a limitation but I guess reasonable.

**Comment by bestander** [comment]
A good RFC discussion is how to enable self-update to be automatic.

**Comment by Daniel15** [comment]
> A good RFC discussion is how to enable self-update to be automatic.

For what it's worth, updates are handled along with the rest of the operating system if you use the Linux package (Ubuntu/Debian/CentOS), that's one major advantage of using them and one of the main reasons we built them :)

**Comment by bestander** [comment]
Well, I mean the other 99.5 percent of users who don't use Linux :)

**Comment by Daniel15** [comment]
@bestander  Chocolatey handles updates too I believe, so Windows users are covered too once our Chocolatey package is approved. The Windows dev userbase is larger than the Mac OS dev userbase 😛 . The Windows installer probably needs a proper auto-update too, that downloads the latest MSI and installs it.

**Comment by bestander** [comment]
You don't expect every version of windows to install yarn with chocolatey?
But bikeshedding aside, I think we need to decide whether we want to keep this feature here or ditch it. If we keep it then let's offer users whether to enable it by default.

Some history: I added it here when we found that maintaining packages via yummy and Chef was too much hassle and it seemed like a reasonable idea to have a lightweight mechanism to get everyone on the same version within the org.
In the end we ended up checking in yarn.js instead of relying on Chef or building our own Chef  yarn self-updates.

As for the community project, I think we get quite a lot of benefits if everyone/most is getting updated to the latest stable whether it is done via package managers or via self-update.

**Comment by bestander** [comment]
Also I am not a huge fan of this implementation, a bit too hacky

**Comment by danez** [comment]
For macOS probably adding yarn to brew might probably also make it easy to install and update there.

How do we want to proceed with this PR? Should I do all the mentioned changes (not github etc.) and later you can still decide to remove/simplify it?

**Comment by bestander** [comment]
@danez, let's do as @Daniel15 suggests and use the website API to get latest version.
Are you up to it?
We can bikeshed about whether we need this feature or enable it later.

**Comment by Daniel15** [comment]
> Should I do all the mentioned changes (not github etc.) and later you can still decide to remove/simplify it?

Yeah, that sounds good to me! Sorry I went a little off-topic in the comments. Removing all the Github stuff should simplify it quite a bit :)

**Comment by ithinkihaveacat** [comment]
@Daniel15 I don't know the implications of this but right now https://yarnpkg.com/latest-version does not list the latest version:

```sh
$ yarn -V
0.15.1
$ curl -s https://yarnpkg.com/latest-version
0.15.0
```

**Comment by bestander** [comment]
Michael, could you file a bug?

**Comment by danez** [comment]
This is beacuse there was no release created on github, only the tag in git

**Comment by ithinkihaveacat** [comment]
@bestander Sure, reported as https://github.com/yarnpkg/yarn/issues/989.

**Comment by Daniel15** [comment]
0.15.1 is not a "real" release, it was just a patch to the tarball and npm
package. All the other installation methods are still at 0.15.0

File: package.json [hunk 5]
```diff
@@ -33,7 +32,7 @@
     "request": "^2.75.0",
     "request-capture-har": "^1.1.4",
     "rimraf": "^2.5.0",
-    "roadrunner": "^1.0.6",
+    "roadrunner": "danez/roadrunner#patch-1",
```
Comment (Daniel15) [inline package.json]: Should we wait for a release of roadrunner before merging this?

File: yarn.lock [hunk 6]
```diff
@@ -2237,14 +2223,6 @@ getpass@^0.1.1:
   dependencies:
     assert-plus "^1.0.0"
 
-github@2.5.1:
```
Comment (Daniel15) [inline yarn.lock]: Nice 👍 🎉

**Comment by danez** [comment]
The test are still failing, because of 0.15.1.

The problem is that https://yarnpkg.com/latest-version says to 0.15.0, but when downloading latest.tar.gz the package.json in this archive says 0.15.1. Im gonna try instead of relying on the package.json instead see where the current symlink points.

**Comment by Daniel15** [comment]
It's tricky because 0.15.1 is not a "real" release - It was just a fixed re-release of the npm package and tarball, but everything else (Windows installer, Linux packages) are still on 0.15.0

**Comment by GantMan** [comment]
looking forward to this 👍

File: bin/yarn.js [hunk 7]
```diff
@@ -5,14 +5,12 @@
 'use strict';
 
 // init roadrunner
-var userHome = require('user-home');
 var mkdirp = require('mkdirp');
-var path = require('path');
-var CACHE_FILENAME = path.join(userHome, '.yarn', '.roadrunner.json');
-mkdirp.sync(path.dirname(CACHE_FILENAME));
+var constants = require('../lib-legacy/constants');
```
Comment (danez) [inline bin/yarn.js]: I now also require constants here from lib-legacy, so that I can use the folder constants. I think that shouldn't be a significant problem.

File: yarn.lock [hunk 8]
```diff
@@ -4449,9 +4415,9 @@ ripemd160@^1.0.0:
   version "1.0.1"
   resolved "https://registry.yarnpkg.com/ripemd160/-/ripemd160-1.0.1.tgz#93a4bbd4942bc574b69a8fa57c71de10ecca7d6e"
 
-roadrunner@^1.0.6:
+roadrunner@danez/roadrunner#patch-1:
   version "1.0.6"
-  resolved "https://registry.yarnpkg.com/roadrunner/-/roadrunner-1.0.6.tgz#e466a15f9844289413d09943ad263574623ec1c9"
+  resolved "https://codeload.github.com/danez/roadrunner/tar.gz/2ead9501e3681fa7584b79e6e6546fb046a83f54"
```
Comment (bestander) [inline yarn.lock]: Let's push the change upstream before merging this.

**Comment by danez** [comment]
While waiting for roadrunner I noticed that it is possible to download a certain version of yarn see https://github.com/yarnpkg/yarn/issues/751#issuecomment-253058942 
Should I add back the possibility to specify the version?

**Comment by Daniel15** [comment]
> Should I add back the possibility to specify the version?

Let's keep it simple - It's totally fine to only support the most recent version 😄

**Comment by thejameskyle** [comment]
@danez you have a broken test: 

```
 FAIL  __tests__/commands/self-update.js (10.597s)
  ● Self-update should work from self-updated location

    Error: Command failed: yarn run build
    /bin/sh: 1: yarn: not found
     
    Console output:
      
       
      at __tests__/commands/self-update.js:57:13
      at throw (native)
      at step (node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/babel-runtime/helpers/asyncToGenerator.js:30:20

  ✓ Self-update should download a release and symlink it as "current" (10365ms)
  ✕ Self-update should work from self-updated location (73ms)
```

**Comment by danez** [comment]
CircleCI is not updating the dependencies :(

**Comment by bestander** [comment]
I'll restart with cache clean

**Comment by danez** [comment]
Seems there is no step on circleCI to install dependencies? At least I can't see one.

**Comment by bestander** [comment]
Yeah, odd, looks like cleaning all cache lost eslint and webpack.

**Comment by bestander** [comment]
Created this one https://github.com/yarnpkg/yarn/pull/1157

**Comment by bestander** [comment]
@danez, could you please rebase it?
This should work now

**Comment by danez** [comment]
Seems circleCI is to slow to run the tests :/ The test is anyway really ugly, and involves building yarn, so not sure if we should keep it.

**Comment by bestander** [comment]
Hm, I would assume that download gets stuck.
Building yarn should be quite fast though.
This is an important test because it checks that self-update did not degrade because of the symlinks and yarn inside yarn situation.

What do you think of keeping this test disabled for a while and merge the rest?
Great work anyway!

**Comment by danez** [comment]
Okay I disabled it now, even after 3 minutes it was running into a timeout.

As all the other downloads seem to be quiet fast it might also be the FS which is slow, and we copy a lot of stuff in this test.

**Comment by bestander** [comment]
Thanks, @danez!
