### PR TITLE
fix(resolver): Fix incorrect peer dependency res. from different trees

### LINKED ISSUE #4539: Theia builds are weirdly broken with npm 5.3.0 + yarn 1.1.0
Theia builds are failing with weird errors from tslint with npm 5.3.0 + yarn 1.1.0: https://travis-ci.org/theia-ide/theia/jobs/279443045

With yarn 1.0.2 it is fine: https://travis-ci.org/theia-ide/theia/jobs/279458465

### PR DESCRIPTION
**Pull request by BYK**
**Summary**

Fixes #4539. Yarn was resolving peer dependencies from the closest level where the peer dependency was requested
but it was not checking if the peer dependency was in the same subtree. This was causing incorrect
peer dependency resolutions and package duplication when  an unrelated subtree has a depedency
satisfying the required peer dependency at the same tree level.

**Test plan**

Added new install integration test that fails without the fix.

### CODE REVIEW

File: src/package-linker.js [hunk 1]
```diff
@@ -446,6 +446,24 @@ export default class PackageLinker {
       }
       const ref = pkg._reference;
       invariant(ref, 'Package reference is missing');
+      // TODO: We are taking the "shortest" ref tree but there may be multiple ref trees with the same length
+      const refTree = ref.requests.map(req => req.parentNames).sort((arr1, arr2) => arr1.length - arr2.length)[0];
+      const refTreeLen = refTree.length;
```
Comment (arcanis) [inline src/package-linker.js]: I'd just use `refTree.length`, it looks like a premature optim (same for `pkgParentsLen`)

File: src/package-linker.js [hunk 2]
```diff
@@ -446,6 +446,24 @@ export default class PackageLinker {
       }
       const ref = pkg._reference;
       invariant(ref, 'Package reference is missing');
+      // TODO: We are taking the "shortest" ref tree but there may be multiple ref trees with the same length
```
Comment (arcanis) [inline src/package-linker.js]: Is it a problem if we choose one of those at random?

Comment (BYK) [reply src/package-linker.js]: I honestly don't know, hence the TODO.

File: src/package-linker.js (hunk 1 above)
Comment (BYK) [reply src/package-linker.js]: It was mostly for ease of reading for myself but sure.

Comment (BYK) [reply src/package-linker.js]: Oh well, these were easier on the eyes in a previous version of the code. Now they are useless as you pointed out.

File: src/package-linker.js [hunk 3]
```diff
@@ -459,16 +477,16 @@ export default class PackageLinker {
           if (!(peerPkgRef && peerPkgRef.patterns)) {
             continue;
           }
-          const levelDistance = ref.level - peerPkgRef.level;
-          if (levelDistance >= 0 && levelDistance < resolvedLevelDistance) {
+          const levelDistance = getLevelDistance(peerPkgRef);
+          if (isFinite(levelDistance) && levelDistance < resolvedLevelDistance) {
```
Comment (kaylieEB) [inline src/package-linker.js]: Is it possible to not set `minDistance` to Infinity and just check for existence now?

File: src/package-linker.js [hunk 4]
```diff
@@ -446,6 +446,24 @@ export default class PackageLinker {
...
+      const refTreeLen = refTree.length;
+
+      const getLevelDistance = pkgRef => {
+        let minDistance = Infinity;
+        for (const req of pkgRef.requests) {
+          const pkgParents = req.parentNames;
+          const pkgParentsLen = pkgParents.length;
+          const distance = refTreeLen - pkgParentsLen;
+
+          if (distance >= 0 && distance < minDistance && pkgParents.every((name, idx) => name === refTree[idx])) {
```
Comment (kaylieEB) [inline src/package-linker.js]: Might be more less readable, but more efficient to use `!pakgParents.some` instead?

File: __tests__/commands/install/integration.js [hunk 5]
```diff
@@ -55,6 +55,15 @@ test.concurrent('install should not hoist packages above their peer dependencies
   });
 });
 
+test.concurrent('install should resolve peer dependencies from same subtrees', async () => {
+  await runInstall({}, 'peer-dep-same-subtree', async (config): Promise<void> => {
+    expect(JSON.parse(await fs.readFile(`${config.cwd}/node_modules/d/node_modules/a/package.json`)).version).toEqual(
+      '1.1.0',
```
Comment (kaylieEB) [inline __tests__/commands/install/integration.js]: shouldn't this equal `1.0.0` since d points to `file:../a-1.0.0` as a dependency? and the top level version of a equal `1.1.0`?

File: src/package-linker.js [hunk 6]
```diff
@@ -446,6 +446,21 @@ export default class PackageLinker {
...
       invariant(ref, 'Package reference is missing');
+      // TODO: We are taking the "shortest" ref tree but there may be multiple ref trees with the same length
+      const refTree = ref.requests.map(req => req.parentNames).sort((arr1, arr2) => arr1.length - arr2.length)[0];
+
+      const getLevelDistance = pkgRef => {
+        let minDistance = Infinity;
+        for (const req of pkgRef.requests) {
+          const distance = refTree.length - req.parentNames.length;
+
+          if (distance >= 0 && distance < minDistance && req.parentNames.every((name, idx) => name === refTree[idx])) {
```
Comment (kaylieEB) [inline src/package-linker.js]: It might be slightly less readable but more efficient to use `!some` to exit early if they don't match

File: __tests__/commands/install/integration.js (hunk 5 above)
Comment (BYK) [reply __tests__/commands/install/integration.js]: Yup, that's why the test was failing :)

File: src/package-linker.js (hunk 6 above)
Comment (BYK) [reply src/package-linker.js]: I think both `every` and `some` do early exits so don't think it would change perf.

File: src/package-linker.js (hunk 3 above)
Comment (BYK) [reply src/package-linker.js]: I wanted that too but then I'd need to add special casing into the `getLevelDistance` code above due to the `distance >= 0 && distance < minDistance` checks. Is it too confusing right now? :(

File: src/package-linker.js (hunk 6 above)
Comment (kaylieEB) [reply src/package-linker.js]: ugh, I keep forgetting that sorry!

File: src/package-linker.js (hunk 3 above)
Comment (kaylieEB) [reply src/package-linker.js]: Ah I see, hmm can't think of an alternative atm. Thanks for explaining. :)
