### PR TITLE
Fixed #1242 - missing transitive dependencies

### LINKED ISSUE #1242: Support `yarn package` and `yarn install --local` like bundler
**Do you want to request a _feature_ or report a _bug_?**

Feature

**Desired behavior**

Bundler supports 'vendoring' dependencies out of the box with the `bundle package` command. This command saves your gems as `.gem` files into your repo at `vendor/cache`. You can install from the saved versions using `bundle install --local`.

http://bundler.io/v1.13/bundle_package.html

This is really handy for deployment and also allows one to be able to do docker builds from a fresh checkout of your application. This is particularly handy if you depend on private packages, and don't want to leak secrets, like git or npm credentials, into your docker image layers.

To get this behaviour on node our team currently use [shrinkpack](https://github.com/JamieMason/shrinkpack), but a more integrated solution would be ideal. This would help us take advantage of the power of Yarn, whilst still being able to bundle our node packages in our repo.

### LINKED ISSUE #2142: v0.18.0 postinstall missing dependencies
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I think some dependencies are missing at the time when `postinstall` scripts are ran.

I'm having this error:
```
yarn install v0.18.0
info No lockfile found.
warning test: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.15: The platform "linux" is incompatible with this module.
info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/3] ⠐ gifsicle
[2/3] ⠐ jpegtran-bin
[3/3] ⠐ optipng-bin
[-/3] ⠐ waiting...
error [my-project]/node_modules/jpegtran-bin: Command failed.
Exit code: 1
Command: sh
Arguments: -c node lib/install.js
Directory: [my-project]/node_modules/jpegtran-bin
Output:
module.js:472
    throw err;
    ^

Error: Cannot find module 'ini'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ([my-project]/node_modules/rc/lib/utils.js:3:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

In another project, after a `yarn upgrade` I also encountered this problem with other packages (`gifsicle`'s `postinstall` missing `deep-extend`). So it seems like a general problem.

**If the current behavior is a bug, please provide the steps to reproduce.**
Given this `package.json`:
```json
{
  "name": "test",
  "devDependencies": {
    "babel-cli": "^6.18.0",
    "gulp-imagemin": "^3.1.1"
  }
}
```
Run `yarn install`.

I noticed that if I try to install only one of these two, it will work. I guess that's an issue with shared dependencies between them.

**What is the expected behavior?**
Installation completes successful.

**Please mention your node.js, yarn and operating system version.**
node.js: v7.2.0
yarn: v0.18.0
OS: Arch Linux

### PR DESCRIPTION
**Pull request by bestander**
**Summary**

Fixes #2142, transitive dependencies now inherit "ignored" state from parent dynamically 

**Test plan**

Test has been added before and now is enabled

### CODE REVIEW

File: __tests__/commands/install/integration.js [hunk 1]
```diff
@@ -727,13 +713,45 @@ test.concurrent('install will not overwrite files in symlinked scoped directorie
...
+    return runInstall({}, 'install-should-skip-incompatible-optional-dep', async (config) => {
+      assert.ok(!(await fs.exists(path.join(config.cwd, 'node_modules', 'dep-a'))));
+    });
+  });
+
+if (process.platform !== 'darwin') {
+  test.concurrent('install incompatible optional dependency should still install shared child dependencies',
+    (): Promise<void> => {
+      // this tests for a problem occuring due to optional dependency incompatible with os, in this case fsevents
+      // this would fail on os's incompatible with fsevents, which is everything except osx.
```
Comment (cpojer) [inline __tests__/commands/install/integration.js]: Can you move this comment to above the if? It makes more sense there to figure out why we skip the test there.

File: src/package-hoister.js [hunk 2]
```diff
@@ -130,13 +130,17 @@ export default class PackageHoister {
 
     //
     let parentParts: Parts = [];
-    let isIgnored = ref.ignore;
+    let isIgnored = () => { return ref.ignore; };
```
Comment (cpojer) [inline src/package-hoister.js]: nit: `() => ref.ignore`.

File: src/package-hoister.js [hunk 3]
```diff
@@ -130,13 +130,17 @@ export default class PackageHoister {
...
 
     if (parent) {
       if (!this.tree.get(parent.key)) {
         return null;
       }
-      isIgnored = isIgnored || parent.ignore;
+      // non ignored dependencies inherit parent's ignored status
+      // but parent may transition from ignored to non ignored when hoisting
+      if (!isIgnored() && parent.isIgnored()) {
+        isIgnored = () => { return !!parent && parent.isIgnored(); };
```
Comment (cpojer) [inline src/package-hoister.js]: also: drop the braces and the return!

File: src/package-hoister.js [hunk 4]
```diff
@@ -182,8 +186,8 @@ export default class PackageHoister {
       if (existing) {
         if (existing.loc === info.loc) {
           // deduping an unignored reference to an ignored one
-          if (existing.ignore && !info.ignore) {
-            existing.ignore = false;
+          if (existing.isIgnored() && !info.isIgnored()) {
+            existing.isIgnored = info.isIgnored;
```
Comment (cpojer) [inline src/package-hoister.js]: I'm not sure it's great to reassign this function.
