### PR TITLE
fix(request) Fix https_proxy env var

### LINKED ISSUE #4885: Yarn 1.3.2 incorrectly bypasses HTTP(S)_PROXY
**Do you want to request a *feature* or report a *bug*?**
*Bug*

**What is the current behavior?**

1. Set HTTP_PROXY and HTTPS_PROXY environment variables to a valid proxy
2. `yarn install` attempts to access yarnpkg.com on port 443, ignoring the proxy settings

**What is the expected behavior?**

1. Yarn instead makes HTTPS requests via the proxy set in the HTTPS_PROXY environment variable. Yarn 1.2.1 does this correctly.

**Please mention your node.js, yarn and operating system version.**

Node 4.8.5
Yarn 1.3.2
Ubuntu 16.04.1

### PR DESCRIPTION
**Pull request by rally25rs**
**Summary**

Fixes #4885. In #4761 I started always passing the proxy to the `request` library to prevent it from falling back to env vars HTTPS_PROXY and HTTP_PROXY. At the time I thought that Yarn would pick up these env vars through its config system and pass them down itself.

It turns out this was not true and caused #4885. Now handling an explicit `false` in the request-manager to allow it to override the `https_proxy` if set. Otherwise, resume allowing request library to pick up the env vars.

**Test plan**

Manually tested. Since the actual requests are proxies under unit test, this is difficult to unit test.

### CODE REVIEW

File: src/util/request-manager.js [hunk 1]
```diff
@@ -412,7 +414,14 @@ export default class RequestManager {
     if (params.url.startsWith('https:')) {
       proxy = this.httpsProxy;
     }
-    params.proxy = String(proxy);
+
+    if (proxy) {
+      params.proxy = String(proxy);
+    } else if (proxy === false) {
+      // passign empty string prevents the underlying library from falling back to the env vars.
```
Comment (timja-kainos) [inline src/util/request-manager.js]: typo on passing

File: src/util/request-manager.js [hunk 2]
```diff
@@ -412,7 +414,16 @@ export default class RequestManager {
...
+
+    if (proxy) {
+      // if no proxy is set, do not pass a proxy down to request.
+      // the request library will internally check the HTTP_PROXY and HTTPS_PROXY env vars.
+      params.proxy = String(proxy);
+    } else if (proxy === false) {
+      // passing empty string prevents the underlying library from falling back to the env vars.
+      // an explicit false in the yarn config should override the env var. See #4546.
+      params.proxy = '';
+    }
```
Comment (kaylieEB) [inline src/util/request-manager.js]: what happens to other falsey variables like 0 or undefined? Maybe you should flip the order?
```
if (proxy === false) {
   params.proxy = '';
} else {
   params.proxy = String(proxy);
}
``` 
or if they're meant to be empty strings
```
params.proxy = proxy ? String(proxy) || '';
```

Comment (rally25rs) [reply src/util/request-manager.js]: Based on some logic above:
```
    if (opts.httpsProxy === '') {
      this.httpsProxy = opts.httpProxy || '';
    } else if (opts.httpsProxy === false) {
      this.httpsProxy = false;
    } else {
      this.httpsProxy = opts.httpsProxy || '';
    }
```

so `httpsProxy` should be one of `''`, `false`, `'https://wherever`

In the case of `''` we don't want to set any `params.proxy` at all because the `request` library will check `hasOwnProperty('httpsProxy')` on the object we pass it. If that property exists at all (even if set to a falsey value) then it will not check the env vars.

So basically the logic here is:

```
if ''
  don't set a proxy (request will fall back to env vars)
if false
  set a proxy to '' (request will not use env vars, and not use any proxy)
if 'some non-falsy string'
  set a proxy to that string (request will use this as the proxy)
```

Hopefully that makes sense...

Comment (kaylieEB) [reply src/util/request-manager.js]: I see. Thanks for explaining!

**Comment by lennyburdette** [comment]
@kaylieEB @BYK Glad to see this fixed—thanks for doing this! Would either of you be able to say when this would be released? I haven't found anything on github or yarnpkg.com about Yarn's release schedule or cadence. Thanks!
