### PR TITLE
Resolve Git dependencies offline if tarball is available.

### LINKED ISSUE #1925: Cannot install packages from github when offline
**Do you want to request a *feature* or report a *bug*?**
Not sure

**What is the current behavior?**
Without an internet connection, I get:
```
[1/4] 🔍  Resolving packages...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
warning There appears to be trouble with your network connection. Retrying...
```
And then the install fails and tells me which github address it was trying to reach on the internet.

**If the current behavior is a bug, please provide the steps to reproduce.**
Just make a `package.json` with a github dependency, such as:
```
"nomnom": "douglasduteil/nomnom#next"
```

Install it via `yarn` while connected to the internet. 
Then unplug your internet, delete `node_modules` dir, and try to `yarn` again.

**What is the expected behavior?**
I expect it to install all my packages from cache even while offline.

**Please mention your node.js, yarn and operating system version.**
Node 6.9.1 LTS, yarn 0.17.4, Mac OS X 10.11.6

### PR DESCRIPTION
**Pull request by raymondwang**
**Summary**

When running yarn offline, Git dependencies get trapped in `hasHTTPCapability` even though `resolveOverHTTP` defaults to returning the tarball. This change allows us to bypass that step altogether if the tarball already exists.

Resolves #1925.

**Test plan**

Create a `package.json` with a Git dependency, like:
```
"nomnom": "douglasduteil/nomnom#next"
```

Then:

```
yarn
rm -r node_modules
yarn --offline
```

This should fail prior to this commit, but succeed after.

This change was first proposed in #2705, but @chrisgavin closed the PR and hasn't had a chance to revisit. I'm happy to add unit tests if/as needed, but may need some guidance on mocking offline functionality.

### CODE REVIEW

File: src/resolvers/exotics/hosted-git-resolver.js [hunk 1]
```diff
@@ -201,7 +201,7 @@ export default class HostedGitResolver extends ExoticResolver {
     // If we can access the files over HTTP then we should as it's MUCH faster than git
     // archive and tarball unarchiving. The HTTP API is only available for public repos
     // though.
-    if (await this.hasHTTPCapability(httpUrl)) {
+    if (this.request.getLocked('tarball') || await this.hasHTTPCapability(httpUrl)) {
```
Comment (arcanis) [inline src/resolvers/exotics/hosted-git-resolver.js]: It works, but I think it would make more sense semantically speaking to just move [those lines](https://github.com/yarnpkg/yarn/blob/master/src/resolvers/exotics/hosted-git-resolver.js#L143-L146) at the beginning of the `resolve()` function instead.

Comment (raymondwang) [inline src/resolvers/exotics/hosted-git-resolver.js]: Yes, sounds good to me!

**Comment by raymondwang** [comment]
@arcanis Done!

**Comment by arcanis** [comment]
Thanks!

**Comment by tp** [comment]
I am correct in assuming that this is not part of the just released yarn 0.23.4?

Because that one still fails for me with the "--offline" flag.

```
=> yarn --offline
yarn install v0.23.4
[1/4] 🔍  Resolving packages...
error Can't make a request in offline mode
```

If so, what release would this be included in then?

**Comment by arcanis** [comment]
Yes. It will be released in the 0.24, which we want to publish later today.
