### PR TITLE
Fix transient symlinks overriding direct ones v2

### LINKED ISSUE #4937: Sub dependency .bin symlinks can override top level dependency .bin symlink
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Sub dependencies .bin symlinks override top level dependencies .bin symlinks in some cases (seems to be depending on which top level package is first when sorted alphabetically). Likely introduced in https://github.com/yarnpkg/yarn/pull/3310

**If the current behavior is a bug, please provide the steps to reproduce.**

Example: https://github.com/anders-advisa/yarn-symlink-bug

**What is the expected behavior?**
Dependencies explicitly entered into `package.json` should have precedence over sub dependencies.

**Please mention your node.js, yarn and operating system version.**
node: 8.9.1
yarn: 1.3.2

### PR DESCRIPTION
**Pull request by rally25rs**
**Summary**

This PR is a replacement for #5012 with a different fix.

fixes #4937

Added a sort to the top level bin links to ensure that direct dependencies are linked last. Since bin links are overwritten if they already exist, this will ensure that direct deps bin links will overwrite transitive ones.

**Test plan**

Run the test suite.

### CODE REVIEW

File: src/package-linker.js [hunk 1]
```diff
@@ -436,17 +436,34 @@ export default class PackageLinker {
...
+      const bIsDirect = bHoistManifest.isDirectRequire;
+
+      if (aIsDirect && !bIsDirect) {
+        return 1;
+      }
+      if (!aIsDirect && bIsDirect) {
+        return -1;
+      }
+      return 0;
+    });
```
Comment (arcanis) [inline src/package-linker.js]: What do you think about splitting the array rather than doing a full sort? The algorithmic complexity would be better:

```
let transientBins = [], topLevelBins = [];
for (let ... of Array.from(linksToCreate.values())) {
    if (isDirectRequire) {
        topLevelBins.push();
    } else {
        transientBins.push();
    }
}

return [... transientBins, ... topLevelBins];
```

Comment (rally25rs) [reply src/package-linker.js]: I like that. The code is easier to read.

**Comment by AndersAstrand** [comment]
This bug is still present in master (fb6511c9) and is blocking us from switching to yarn. Is there anything I can do to help move this PR forward?

**Comment by rally25rs** [comment]
@arcanis think we can merge this?

**Comment by arcanis** [comment]
Totally! This will be in the next release, hopefully today or tomorrow 👍
