### PR TITLE
Fix: respect GIT_SSH env variable when calling Git and support plink

### LINKED ISSUE #4167: Bug: Yarn fails to install when a custom SSH command is used for Git via GIT_SSH
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**
Yarn fails on dependencies on our private gitlab server. 

Error message:
```
yarn install v0.27.5
[1/4] Resolving packages...
error Command failed.
Exit code: 128
Command: git
Arguments: clone ssh://git@git.gitlab.local/my-package/my-package.git C:\Users\matthijsba\AppData\Local\Yarn\cache\v1\.tmp\3abb1dfe087a6eb779c097328e5514bb
Directory: C:\source\my-app
Output:
Cloning into 'C:\Users\matthijsba\AppData\Local\Yarn\cache\v1\.tmp\3abb1dfe087a6eb779c097328e5514bb'...
Permission denied (publickey,password).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
No real reproduction steps. If I run:

`git clone ssh://git@git.gitlab.local/my-package/my-package.git` this works without any issues

If I run `npm i` this will install the dependencies. 

**What is the expected behavior?**
The dependencies will be installed 

**Please mention your node.js, yarn and operating system version.**
Node: 8.3.0 / 6.11.2 (tested both)
Yarn: 0.27.5 / 0.28.1 (tested both)
OS: Windows 10 version 1703

I have read other issues like #513 and #686 but I could not find a solution yet.

### PR DESCRIPTION
**Pull request by BYK**
**Summary**

Fixes #4167. We use `$GIT_SSH_COMMAND` which overrides `$GIT_SSH`
and causes issues on some systems, where a different `ssh`
executable like `plink` is used. This patch makes our batch-mode
enforcement smarter and more respectful and adds support for `plink`.

**Test Plan**

Unit tests.

### CODE REVIEW

**Comment by BYK** [comment]
@arcanis  - I'll update the PR with more unit tests for the new cases and functionality. This is just the initial fix for your early feedback.

File: src/util/git/git-spawn.js [hunk 1]
```diff
@@ -1,15 +1,29 @@
...
 const env = {
   GIT_ASKPASS: '',
   GIT_TERMINAL_PROMPT: 0,
-  GIT_SSH_COMMAND: 'ssh -oBatchMode=yes',
   ...process.env,
 };
 
+const sshCommand = env.GIT_SSH || 'ssh';
+const sshExecutable = path.basename(sshCommand, '.exe');
+const sshBatchArgs = BATCH_MODE_ARGS[sshExecutable];
```
Comment (arcanis) [inline src/util/git/git-spawn.js]: Nit: `GIT_SSH=prototype yarn` 😄

**Comment by arcanis** [comment]
Apart from the nit, looks good to me
