### PR TITLE
Prevent optional subdependencies from being installed with --ignore-optional

### LINKED ISSUE #2666: ignore-optional flag works not like expected
**Do you want to request a *feature* or report a *bug*?**
Bug / feature ? 

**What is the current behavior?**
`yarn install --ignore-optional` tries to install also optional dependencies of sub modules. The while install process fails if one of the optional module installation fails.

**What is the expected behavior?**
To skip the optional dependencies of sub modules or to continue on errors.

**Please mention your node.js, yarn and operating system version.**
Node 7.5.0, Yarn v0.19.1, Ubuntu 14.04

### PR DESCRIPTION
**Pull request by arcanis**
Fix #2666

@blexrob Would you mind reviewing this PR? You worked a bit on the hoister in #3465, so you might have some additional insight :)

### CODE REVIEW

File: src/cli/commands/install.js [hunk 1]
```diff
@@ -277,12 +277,7 @@ export class Install {
 
       pushDeps('dependencies', projectManifestJson, {hint: null, optional: false}, true);
       pushDeps('devDependencies', projectManifestJson, {hint: 'dev', optional: false}, !this.config.production);
-      pushDeps(
-        'optionalDependencies',
-        projectManifestJson,
-        {hint: 'optional', optional: true},
-        !this.flags.ignoreOptional,
-      );
+      pushDeps('optionalDependencies', projectManifestJson, {hint: 'optional', optional: true}, true);
```
Comment (BYK) [inline src/cli/commands/install.js]: Why always set `isUsed` to true?

File: src/package-hoister.js [hunk 2]
```diff
@@ -142,15 +146,15 @@ export default class PackageHoister {
     //
     let parentParts: Parts = [];
     const isIncompatible = ref.incompatible;
-    let isRequired = isDirectRequire && !ref.ignore && !isIncompatible;
+    let isRequired = isDirectRequire && !ref.ignore && !isIncompatible && (!ref.optional || !this.ignoreOptional);
```
Comment (BYK) [inline src/package-hoister.js]: Better to write as `!(ref.optional && this.ignoreOptional)` since makes the intent clearer. Also possibly fewer instructions :P

File: src/package-hoister.js [hunk 3]
```diff
@@ -142,15 +146,15 @@ export default class PackageHoister {
...
 
     if (parent) {
       if (!this.tree.get(parent.key)) {
         return null;
       }
       // non ignored dependencies inherit parent's ignored status
       // parent may transition from ignored to non ignored when hoisted if it is used in another non ignored branch
-      if (!isDirectRequire && !isIncompatible && parent.isRequired) {
+      if (!isDirectRequire && !isIncompatible && parent.isRequired && (!ref.optional || !this.ignoreOptional)) {
```
Comment (BYK) [inline src/package-hoister.js]: Same as above. Also, may convert this to a function instead of repeating the same logic in multiple places?

File: src/package-hoister.js [hunk 4]
```diff
@@ -196,7 +200,12 @@ export default class PackageHoister {
 
       for (const depPattern of ref.dependencies) {
         const depinfo = this._lookupDependency(info, depPattern);
-        if (depinfo && !depinfo.isRequired && !depinfo.isIncompatible) {
+        if (
+          depinfo &&
+          !depinfo.isRequired &&
+          !depinfo.isIncompatible &&
+          (!depinfo.pkg._reference || !depinfo.pkg._reference.optional || !this.ignoreOptional)
```
Comment (BYK) [inline src/package-hoister.js]: Yeah, we definitely need to extract this logic out.

File: src/package-hoister.js (hunk 2 above)
Comment (arcanis) [inline src/package-hoister.js]: That's purely stylistic ;)

File: src/package-hoister.js (hunk 4 above)
Comment (arcanis) [inline src/package-hoister.js]: Yeah I agree, but there was some subtle changes in the conditions so I aimed to make the minimal change required and revisit if needed. I'll give it a second look.

File: src/cli/commands/install.js (hunk 1 above)
Comment (arcanis) [inline src/cli/commands/install.js]: Because the ignore flag isn't managed anymore by this portion of the code - we do it directly in the hoister instead, so that we can operate recursively.

Comment (BYK) [inline src/cli/commands/install.js]: Gotcha. May be we should remove that flag in a follow-up since it is only used by `devDependencies` and is confusing a bit.

File: src/package-hoister.js (hunk 2 above)
Comment (BYK) [inline src/package-hoister.js]: Not really stylistic. One reads "if `ref` is not optional or we should not ignore optionals" and the other one reads "if NOT (ref is optional and we should ignore optionals)". Human brains are bad at double negations ;)

File: src/package-hoister.js (hunk 4 above)
Comment (BYK) [inline src/package-hoister.js]: We can defer this to a follow-up since it's not the main goal of the PR anyways.

File: src/cli/commands/install.js (hunk 1 above)
Comment (blexrob) [inline src/cli/commands/install.js]: isUsed is also used to remove the package from consideration in flat mode, so I wouldn't remove it (if another package requires an incompatible version, this would create a conflict).
