### PR TITLE
Fix: always prefer CLI options over env for --prod

### LINKED ISSUE #4557: --production=false flag not being honored on install
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When passing `--production=false` with `NODE_ENV=production` devDependencies are not installed. Prior to v1.1.0 this worked correctly. 

**If the current behavior is a bug, please provide the steps to reproduce.**
`NODE_ENV=production yarn install --production=false`

**What is the expected behavior?**
devDependencies are installed despite `NODE_ENV` being set to `production`

**Please mention your node.js, yarn and operating system version.**
Node: 6.10.3
Yarn: 1.1.0
OS: MacOS 10.12.6

### PR DESCRIPTION
**Pull request by BYK**
**Summary**

Fixes #4557. Also adds `yarn config current` that lists the current
configuration as JSON for testing purposes.

**Test plan**

Added integration tests.

### CODE REVIEW

File: src/cli/commands/config.js [hunk 1]
```diff
@@ -5,6 +5,41 @@ import type {Reporter} from '../../reporters/index.js';
...
+  'networkTimeout',
+  'workspacesEnabled',
+  'pruneOfflineMirror',
+  'enableMetaFolder',
+  'enableLockfileVersions',
+  'linkFileDependencies',
+  'cacheFolder',
+  'tempFolder',
+  'production',
+];
```
Comment (arcanis) [inline src/cli/commands/config.js]: Couldn't we just iterate over `config`, and possibly blacklist fields if there's internal ones? A whitelist seems a burden to maintain.

Comment (BYK) [reply src/cli/commands/config.js]: We can but isn't it safer to have a fixed list? It also makes our job easier by simply using `JSON.stringify` and passing the whitelist. For a blacklist, we need to manually walk over the config object beforehand and copy all to a new object.
