### PR TITLE
Put build artifact tracking in integrity file

### LINKED ISSUE #1981: Installing node-sass and rebuilding/using it results in module not found
Hello,

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

I install node-sass@^3.13.0 using yarn 0.17.8. I then run `npm rebuild node-sass` and it outputs :
```Error: Cannot find module 'sax'```
The missing is sometimes different (happened to be `has` too).

It also happens without running `npm rebuild node-sass`. When using node-sass without rebuilding it, I encounter the same error.

**Logs**

<details>

```bash
$ npm rebuild node-sass@^3.13.0
       
       > node-sass@3.13.0 install /tmp/build_018b7933b66e2c3d195b746872072c52/node_modules/node-sass
       > node scripts/install.js
       
       node-sass build Binary found at /tmp/build_018b7933b66e2c3d195b746872072c52/node_modules/node-sass/vendor/linux-x64-51/binding.node
       
       > node-sass@3.13.0 postinstall /tmp/build_018b7933b66e2c3d195b746872072c52/node_modules/node-sass
       > node scripts/build.js
       
       Binary found at /tmp/build_018b7933b66e2c3d195b746872072c52/node_modules/node-sass/vendor/linux-x64-51/binding.node
       Testing binary
       Binary is fine
       node-sass@3.13.0 /tmp/build_018b7933b66e2c3d195b746872072c52/node_modules/node-sass
       Error: Cannot find module 'sax'
       at Function.Module._resolveFilename (module.js:472:15)
       at Function.Module._load (module.js:420:25)
       at Module.require (module.js:500:17)
       at require (internal/module.js:20:19)
       at Object.<anonymous> (/tmp/build_018b7933b66e2c3d195b746872072c52/node_modules/svgo/lib/svgo/svg2js.js:3:11)
       at Module._compile (module.js:573:32)
       at Object.Module._extensions..js (module.js:582:10)
       at Module.load (module.js:490:32)
       at tryModuleLoad (module.js:449:12)
       at Function.Module._load (module.js:441:3)
       at Module.require (module.js:500:17)
       at require (internal/module.js:20:19)
       at Object.<anonymous> (/tmp/build_018b7933b66e2c3d195b746872072c52/node_modules/svgo/lib/svgo.js:14:14)
       at Module._compile (module.js:573:32)
       at Object.Module._extensions..js (module.js:582:10)
       at Module.load (module.js:490:32)
       at tryModuleLoad (module.js:449:12)
       at Function.Module._load (module.js:441:3)
       at Module.require (module.js:500:17)
       at require (internal/module.js:20:19)
       at Object.<anonymous> (/tmp/build_018b7933b66e2c3d195b746872072c52/node_modules/postcss-svgo/dist/index.js:15:13)
       at Module._compile (module.js:573:32)
       at Object.Module._extensions..js (module.js:582:10)
       at Module.load (module.js:490:32)
       at tryModuleLoad (module.js:449:12)
       at Function.Module._load (module.js:441:3)
       at Module.require (module.js:500:17)
       at require (internal/module.js:20:19)
       at Object.<anonymous> (/tmp/build_018b7933b66e2c3d195b746872072c52/node_modules/cssnano/dist/index.js:37:20)
       at Module._compile (module.js:573:32)
       error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

</details>
<br>

**Versions :**
OS: Heroku VM using yarn node.js buildpack (https://github.com/heroku/heroku-buildpack-nodejs/tree/yarn)
yarn: 0.17.8
node-sass: 3.13.0
npm: 3.10.9
node: LTS and latest tried

Could be related to https://github.com/sass/node-sass/issues/1804 but on this issue they say it's fixed on yarn v0.17.7, while on 0.17.8 it isn't for me.

Thanks,
Arthur

### PR DESCRIPTION
**Pull request by kittens**
**Summary**

This moves build artifact tracking away from the cache metadata and into the integrity file.

I suspect this should fix #1981 as the cause seems to be that they restore `node_modules` and not Yarn's internal cache.

**Test plan**

Existing tests.

### CODE REVIEW

File: src/cli/commands/install.js [hunk 1]
```diff
@@ -329,6 +329,12 @@ export class Install {
       return true;
     }
 
+    const {artifacts} = match;
```
Comment (bestander) [inline src/cli/commands/install.js]: Is it the right place?
bailout() function is overridden in add.js.

In the next couple of weeks I'd like to do integrity check earlier in install phase.

File: src/integrity-checker.js [hunk 2]
```diff
@@ -247,6 +251,7 @@ export default class InstallationIntegrityChecker {
       integrityFileMissing: false,
       integrityMatches,
       missingPatterns,
+      artifacts: expected ? expected.artifacts : null,
```
Comment (bestander) [inline src/integrity-checker.js]: Returning artifacts from check seems to break cohesion of the check function.
Makes sense from performance point of view because we already parse integrity file here but I would rather have a separate function that returns integrity file.

Side note: my fault that check command has side effects (reporter logs), I plan to refactor it.

**Comment by bestander** [comment]
Let's merge it now, I'll be refactoring integrity-checker
