### PR TITLE
Fixes npm auth

### LINKED ISSUE #3765: yarn@0.27.3 consistently 404s on private packages
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
yarn@0.27.3 fails to install private packages on every run of `yarn` across several different projects/lockfiles, with a 404.

eg
screen shot 2017-06-29 at 3 55 41 pm

**If the current behavior is a bug, please provide the steps to reproduce.**

presumably, run `yarn` with `yarn@0.27.3` installed against any `yarn.lock` that includes private packages.

**What is the expected behavior?**

`yarn@0.27.3` installs private packages.

**Please mention your node.js, yarn and operating system version.**

node: 6.9.1
yarn: 0.27.3
OS: macOS@10.12.4, ubuntu 14.04.5 LTS

### PR DESCRIPTION
**Pull request by arcanis**
This commit should fix #3765. I'm not completely satisfied with hardcoding our registry, maybe that could extended at a later point with an option to "inherit" the auth token from npm. Not sure it would be useful, tho.

### CODE REVIEW

**Comment by bestander** [comment]
We definitely should extract the npmrc/yarnrc config parsing from npm-registry and yarn-registry.
There is a lot of confusion that those classes though in inheritance relationship read the config files exclusively.

**Comment by bestander** [comment]
@arcanis, how did you test the PR?
I suppose e2e test will be coming within the follow-up task https://github.com/yarnpkg/yarn/issues/3769, right?

File: src/registries/npm-registry.js [hunk 1]
```diff
@@ -208,26 +208,33 @@ export default class NpmRegistry extends Registry {
...
 
-    const registry = this.getRegistry(packageName);
+    const baseRegistry = this.getRegistry(packageName);
+    const registries = [baseRegistry];
 
-    // Check for bearer token.
-    const authToken = this.getRegistryOrGlobalOption(registry, '_authToken');
-    if (authToken) {
-      return `Bearer ${String(authToken)}`;
+    if (baseRegistry === `https://registry.yarnpkg.com/`) {
```
Comment (bestander) [inline src/registries/npm-registry.js]: we have constants for these values

File: src/registries/npm-registry.js [hunk 2]
```diff
@@ -76,15 +76,15 @@ export default class NpmRegistry extends Registry {
...
 
     const headers = Object.assign(
       {
         Accept: 'application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*',
       },
       opts.headers,
     );
-    if (this.token || (alwaysAuth && isRequestToRegistry(requestUrl, registry, customHostSuffix))) {
+
+    if (alwaysAuth || (packageName || pathname)[0] === `@`) {
```
Comment (bestander) [inline src/registries/npm-registry.js]: I don't understand the reason for this change

File: src/registries/npm-registry.js (hunk 1 above)
Comment (bestander) [inline src/registries/npm-registry.js]: So if package comes from `registry.yarnpkg.com` then you want to add `registry.npmjs.org` to the list of registries in the attempt of getting username and password.

That looks like a lazy patch, it would be better to set up `getRegistryOrGlobalOption` to return same data for yarnpkg and npmjs rather than patch every callsite

File: src/registries/npm-registry.js (hunk 2 above)
Comment (bestander) [inline src/registries/npm-registry.js]: From @arcanis:

this.token is undefined
So the codepath is not executed if alwaysAuth is not set
The condition I put tries to set an auth token if alwaysAuth is enabled, or if the package is scoped

Comment (BYK) [inline src/registries/npm-registry.js]: This should go into the code as a comment. Also a helper function named `isScoped` or `needsAuth` (or both?) would make the code more readable.

Comment (BYK) [inline src/registries/npm-registry.js]: Also I think the `this.token` check here was to memoize the token. We may wanna keep that behavior.

File: src/registries/npm-registry.js [hunk 3]
```diff
@@ -208,26 +208,33 @@ export default class NpmRegistry extends Registry {
...
+    if (baseRegistry === `https://registry.yarnpkg.com/`) {
+      registries.push(`https://registry.npmjs.org/`);
     }
 
-    // Check for basic auth token.
-    const auth = this.getRegistryOrGlobalOption(registry, '_auth');
-    if (auth) {
-      return `Basic ${String(auth)}`;
-    }
+    for (const registry of registries) {
```
Comment (BYK) [inline src/registries/npm-registry.js]: Is this trying to get an auth token for the first matching registry? If so, I find that a bit dangerous. Should we keep a mapping of `registry: token` pairs and use the appropriate one when communicating. This would also leak tokens to other registries which may be an important security threat.

Comment (arcanis) [inline src/registries/npm-registry.js]: Hence the check to make sure that the npm fallback is only added when the registry is the Yarn registry. The token won't be sent for any other hostname (wich is another issue).

That being said, the whole "multi-registry" logic is flawed, since we only support a single registry implementation (and adding more of them wouldn't make much sense, since it would complexify the codebase for little gain). I'd like to rework it so that we only support a single registry implementation, the npm one, and then make possible to configure what needs to be generic (mostly the hostname). But that's a second step.

Comment (BYK) [inline src/registries/npm-registry.js]: I'm +1 to this until we do the refactor. The code can use a short comment explaining this safe-guard.

**Comment by BYK** [comment]
Sup @arcanis? :)

File: src/registries/npm-registry.js [hunk 4]
```diff
@@ -76,15 +77,19 @@ export default class NpmRegistry extends Registry {
...
     const headers = Object.assign(
       {
         Accept: 'application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*',
       },
       opts.headers,
     );
-    if (this.token || (alwaysAuth && isRequestToRegistry(requestUrl, registry, customHostSuffix))) {
+
+    const packageIdent = packageName || pathname;
+    const isScoppedPackage = packageIdent.match(/^@|\/@/);
```
Comment (BYK) [inline src/registries/npm-registry.js]: What does the second part cover? (sorry, not very familiar with scoped packages except for the `@user/package` pattern.

File: src/registries/npm-registry.js [hunk 5]
```diff
@@ -208,26 +213,34 @@ export default class NpmRegistry extends Registry {
...
+      if (auth) {
+        return `Basic ${String(auth)}`;
+      }
+
+      // Check for basic username/password auth.
+      const username = this.getRegistryOrGlobalOption(registry, 'username');
+      const password = this.getRegistryOrGlobalOption(registry, '_password');
+      if (username && password) {
+        const pw = new Buffer(String(password), 'base64').toString();
+        return 'Basic ' + new Buffer(String(username) + ':' + pw).toString('base64');
```
Comment (BYK) [inline src/registries/npm-registry.js]: Wow, no idea we did double base64 for the password part.

File: src/registries/npm-registry.js (hunk 4 above)
Comment (arcanis) [inline src/registries/npm-registry.js]: In some case `packageIdent` will be `@user/package`, and in other cases it will be `https://example.org/@user/package.tgz`

**Comment by arcanis** [comment]
The main issue with e2e test is that it would require a private package somewhere. I have my own test package on my account, but I obviously cannot use it in the Yarn testsuite 😄 

Ideally, we should create a new private package on the `yarnpkg` organization (we might need to upgrade the plan, cc @bestander, do you know who holds the keys of this account?), create a new `yarnpkg-test` user, and give to this user the read-only rights to access the test package ([npm access](https://docs.npmjs.com/cli/access)). From there we should be able to safely put the auth token in our tests (unfortunately it will still allow malicious users to publish under this user namespace, but that shouldn't make much difference since they won't have push access to any existing project).

**Comment by BYK** [comment]
>That, or we build a stub registry server.

This. Or even better: we just do integration tests via mocks.

**Comment by bestander** [comment]
I think we should have an end to end installation without stubs at least for one package.
It should take a few minutes to register @yarnpkg test org and create a package there.
The login won't be secure but what are the risks, malicious parties will be able to install that package?

**Comment by BYK** [comment]
@bestander I'll merge this then since we have filed #3842

**Comment by daniel-nagy** [comment]
This has broken installing private modules from our company's Bitbucket server.

```JSON
"private-module": "git+ssh://git@git:7999/project/private-module.git"
```

I rolled back to version `0.27.4` and it correctly installs the package.

**Comment by bestander** [comment]
@daniel-nagy please raise a new issue.
Can you provide an example URL publicly for us to test?

**Comment by BYK** [comment]
@daniel-nagy @bestander #3907
