### PR TITLE
Fix: Don't do range collapsing when using a frozen lockfile

### LINKED ISSUE #3313: The --frozen-lockfile command-line option does not work
The `--frozen-lockfile` command-line option does not work as advertised. It behaves the same way as when the option is not supplied, modifying the yarn.lock.

Here's an example:

```
$ yarn --version
0.23.4
$ git status -s
$ yarn --frozen-lockfile
yarn install v0.23.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 6.99s.
$ git status -s
 M yarn.lock
```

**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

The yarn.lock can be overwritten when `--frozen-lockfile` is provided on the command line.

**If the current behavior is a bug, please provide the steps to reproduce.**

Have a package.json that includes transitive dependencies with different versions. Sometimes, yarn will opportunistically collapse multiple dependencies on the same package into a single entry in the lock file if they can be satisfied by a single version. I'm not sure what triggers this. #579 contains a more thorough discussion.

Here is the link to a Travis CI build that exhibits the behavior: https://travis-ci.org/atomist/travis-rugs/builds/228523519
Here is the call to yarn that ended up with the yarn.lock being changed: https://github.com/atomist/travis-rugs/blob/c8b2dddfd129ae836a30864ec410ca9f01ff535e/.atomist/build/travis-build.bash#L68

**What is the expected behavior?**

yarn will make due with what is in the yarn.lock if it satisfies everything in package.json or fail if it can't.

**Please mention your node.js, yarn and operating system version.**

```
$ node --version
v7.9.0
$ yarn --version
0.23.4
$ uname -a
Darwin mbp.local 15.6.0 Darwin Kernel Version 15.6.0: Fri Feb 17 10:21:18 PST 2017; root:xnu-3248.60.11.4.1~1/RELEASE_X86_64 x86_64
```

### PR DESCRIPTION
**Pull request by BYK**
**Summary**

Fixes #3313.

Yarn automatically optimizes less-than-ideal `yarn.lock` files, usually from older versions. That said when run with the `--frozen-lockfile` argument, it should neither touch the lockfile nor throw an exception if the lockfile satisfies all the needs, even if it can be optimized.

**Test plan**

Existing unit tests plus a new unit test which fails without the fix applied.

### CODE REVIEW

File: src/cli/commands/import.js [hunk 1]
```diff
@@ -280,7 +280,7 @@ export class Import extends Install {
     if (manifest.name && this.resolver instanceof ImportPackageResolver) {
       this.resolver.rootName = manifest.name;
     }
-    await this.resolver.init(requests, this.flags.flat);
+    await this.resolver.init(requests, this.flags.flat, this.flags.frozenLockfile);
```
Comment (cpojer) [inline src/cli/commands/import.js]: Could we change this to named args, like this:

```
this.resolver.init(requests, {
  flat: this.flags.flat,
  frozenLockFile: this.flags.frozenLockfile,
});
```

?

Comment (arcanis) [inline src/cli/commands/import.js]: Dang, this time I've been 28 seconds slower 😆

Comment (BYK) [inline src/cli/commands/import.js]: Damn! I actually did it that way first and then went back to this monstrosity :(

**Comment by BYK** [comment]
@arcanis - Please do not merge until I defuse the boolean trap ;)

File: src/cli/commands/import.js [hunk 2]
```diff
@@ -254,7 +254,10 @@ class ImportPackageResolver extends PackageResolver {
     }
   }
 
-  async init(deps: DependencyRequestPatterns, isFlat: boolean): Promise<void> {
+  async init(
+    deps: DependencyRequestPatterns,
+    {isFlat, isFrozen}: {isFlat: boolean, isFrozen?: boolean},
```
Comment (arcanis) [inline src/cli/commands/import.js]: Shouldn't `isFlat` be also a `isFlat?` in its type? I'm not really familiar with Flow, though. On a different note, you can add a default value (` = {}` at the end of the parameter declaration) so that you don't have to explicitely pass an empty object (like [here](https://github.com/yarnpkg/yarn/pull/3604/files#diff-d8db564fe8c688cb48a7eea6336f3895L147)). That might require to move the `workspaceLayout` parameter before the options.

Comment (BYK) [inline src/cli/commands/import.js]: Nice! I thought about default params but wasn't sure if we supported them. Since now I know, I'll go ahead and use it.

File: src/package-resolver.js [hunk 3]
```diff
@@ -15,6 +15,12 @@ import WorkspaceLayout from './workspace-layout.js';
 const invariant = require('invariant');
 const semver = require('semver');
 
+export type ResolverOptions = {
```
Comment (cpojer) [inline src/package-resolver.js]: Can you make it an exact type using:

```
export type ResolverOptions = {|
  …
|}
```

that way you cannot add fields to the object that aren't specified here. In general, I recommend all object type definitions to use this unless they have a good reason not to.
