### PR TITLE
fix(info): Use version from `latest` dist-tag instead of the highest one

### LINKED ISSUE #3947: The version of ui-select package is wrong in yarn CLI
The version of [ui-select package](https://yarnpkg.com/en/package/ui-select) is wrong in yarn CLI. Current version is 0.19.8 (created 2017-04-18) but in yarn CLI version is 0.20.0 (created 2016-10-19). See code below
```
$ yarn info ui-select
yarn info v0.27.5
{ name: 'ui-select',
  'dist-tags': { latest: '0.19.8' },
  versions: 
   [ '0.11.2',
     '0.13.2-amd',
     '0.13.2',
     '0.13.3',
     '0.14.0',
     '0.14.1',
     '0.14.2',
     '0.14.3',
     '0.14.4',
     '0.14.5',
     '0.14.6',
     '0.14.7',
     '0.14.10',
     '0.15.0-ar',
     '0.16.0',
     '0.16.1',
     '0.17.0',
     '0.17.1',
     '0.18.0',
     '0.18.1',
     '0.19.0',
     '0.19.1',
     '0.19.2',
     '0.19.3',
     '0.19.4',
     '0.19.5',
     '0.19.6',
     '0.19.7',
     '0.19.8',
     '0.20.0' ],
  maintainers: 
   [ { name: 'aaronroberson',
       email: 'aaronaroberson@gmail.com' },
     { name: 'ark',
       email: 'npm@mail.wtwf.com' },
     { name: 'mkoryak',
       email: 'mkoryak@gmail.com' } ],
  time: 
   { modified: '2017-04-18T05:44:50.059Z',
     created: '2015-05-15T16:29:18.731Z',
     '0.11.2': '2015-05-15T16:29:18.731Z',
     '0.13.2': '2015-10-20T20:37:20.177Z',
     '0.13.2-amd': '2016-01-25T17:43:39.645Z',
     '0.15.0-ar': '2016-01-25T18:23:02.918Z',
     '0.13.3': '2016-01-25T21:28:24.466Z',
     '0.14.0': '2016-01-25T23:04:14.734Z',
     '0.14.1': '2016-01-27T22:22:14.983Z',
     '0.14.2': '2016-01-28T20:51:07.263Z',
     '0.14.3': '2016-02-18T15:31:40.639Z',
     '0.14.4': '2016-02-18T20:03:43.363Z',
     '0.14.5': '2016-02-18T20:29:31.431Z',
     '0.14.6': '2016-02-18T20:39:48.812Z',
     '0.14.7': '2016-02-18T21:02:57.304Z',
     '0.14.10': '2016-03-06T15:06:22.040Z',
     '0.16.0': '2016-03-15T17:21:45.207Z',
     '0.16.1': '2016-03-23T20:56:10.555Z',
     '0.17.0': '2016-05-11T21:26:29.082Z',
     '0.17.1': '2016-05-16T19:53:33.118Z',
     '0.18.0': '2016-06-09T20:44:03.105Z',
     '0.18.1': '2016-07-10T00:31:16.725Z',
     '0.19.0': '2016-08-07T16:04:43.107Z',
     '0.19.1': '2016-08-07T23:40:57.578Z',
     '0.19.2': '2016-08-09T18:19:35.559Z',
     '0.19.3': '2016-08-16T19:45:30.592Z',
     '0.19.4': '2016-08-17T06:21:29.855Z',
     '0.20.0': '2016-10-19T19:45:37.343Z',
     '0.19.5': '2016-10-19T20:41:46.309Z',
     '0.19.6': '2016-10-24T23:14:59.588Z',
     '0.19.7': '2017-04-12T09:10:12.460Z',
     '0.19.8': '2017-04-18T05:44:50.059Z' },
  homepage: 'http://github.com/angular-ui/ui-select',
  repository: { url: 'git://github.com/angular-ui/ui-select.git' },
  author: { name: 'http://github.com/angular-ui/ui-select/graphs/contributors' },
  bugs: { url: 'https://github.com/angular-ui/ui-select/issues' },
  license: 'MIT',
  readmeFilename: 'README.md',
  users: 
   { herrherrmann: true,
     sesamechee: true },
  version: '0.20.0',
  main: './index.js',
  style: 'dist/select.css',
  devDependencies: 
   { angular: '^1.2.18',
     'angular-mocks': '^1.2.18',
     'angular-sanitize': '^1.2.18',
     'conventional-changelog': '^0.5.3',
     'conventional-recommended-bump': '0.0.3',
     del: '~0.1.1',
     'event-stream': '~3.1.0',
     gulp: '^3.9.1',
     'gulp-angular-templatecache': '^1.8.0',
     'gulp-bump': '^1.0.0',
     'gulp-concat': '^2.6.0',
     'gulp-conventional-changelog': '^0.7.0',
     'gulp-filenames': '^2.0.0',
     'gulp-footer': '^1.0.5',
     'gulp-git': '^1.4.0',
     'gulp-header': '^1.7.1',
     'gulp-jshint': '^2.0.0',
     'gulp-load-plugins': '^1.1.0',
     'gulp-minify-css': '^1.2.4',
     'gulp-minify-html': '^1.0.6',
     'gulp-plumber': '^0.6.3',
     'gulp-replace': '^0.5.4',
     'gulp-sourcemaps': '^1.6.0',
     'gulp-tag-version': '^1.3.0',
     'gulp-uglify': '^1.5.3',
     'gulp-util': '^2.2.19',
     jquery: '~1.11',
     jshint: '^2.9.1',
     'jshint-stylish': '~0.3.0',
     karma: '^0.12.16',
     'karma-chrome-launcher': '^0.1.3',
     'karma-coverage': '~0.2',
     'karma-firefox-launcher': '~0.1',
     'karma-jasmine': '~0.2',
     'karma-ng-html2js-preprocessor': '^0.1.0',
     'karma-phantomjs-launcher': '~0.1.4',
     'run-sequence': '^1.1.5',
     streamqueue: '^1.1.1',
     'title-case': '^1.1.2' },
  scripts: { test: 'gulp test' },
  spm: 
   { main: 'dist/select.js',
     output: [ 'dist/select.css' ] },
  gitHead: '27b9a17117ea887ecff2833a2a16b5fe8fe1de69',
  description: 'AngularJS-native version of [Select2](http://ivaynberg.github.io/select2/) and [Selectize](http://brianreavis.github.io/selectize.js/). [http://angular-ui.github.io/ui-select/](http://angular-ui.github.io/ui-select/)',
  dist: 
   { shasum: '1d7cdb44d2c7c76b338f0b1a00adb18bd051dafd',
     tarball: 'https://registry.npmjs.org/ui-select/-/ui-select-0.20.0.tgz' },
  directories: {} }
Done in 0.39s.
```

in npm everything is good:
```
$ npm view ui-select
 
{ name: 'ui-select',
  'dist-tags': { latest: '0.19.8' },
  versions: 
   [ '0.11.2',
     '0.13.2-amd',
     '0.13.2',
     '0.13.3',
     '0.14.0',
     '0.14.1',
     '0.14.2',
     '0.14.3',
     '0.14.4',
     '0.14.5',
     '0.14.6',
     '0.14.7',
     '0.14.10',
     '0.15.0-ar',
     '0.16.0',
     '0.16.1',
     '0.17.0',
     '0.17.1',
     '0.18.0',
     '0.18.1',
     '0.19.0',
     '0.19.1',
     '0.19.2',
     '0.19.3',
     '0.19.4',
     '0.19.5',
     '0.19.6',
     '0.19.7',
     '0.19.8',
     '0.20.0' ],
  maintainers: 
   [ 'aaronroberson <aaronaroberson@gmail.com>',
     'ark <npm@mail.wtwf.com>',
     'mkoryak <mkoryak@gmail.com>' ],
  time: 
   { modified: '2017-04-18T05:44:50.059Z',
     created: '2015-05-15T16:29:18.731Z',
     '0.11.2': '2015-05-15T16:29:18.731Z',
     '0.13.2': '2015-10-20T20:37:20.177Z',
     '0.13.2-amd': '2016-01-25T17:43:39.645Z',
     '0.15.0-ar': '2016-01-25T18:23:02.918Z',
     '0.13.3': '2016-01-25T21:28:24.466Z',
     '0.14.0': '2016-01-25T23:04:14.734Z',
     '0.14.1': '2016-01-27T22:22:14.983Z',
     '0.14.2': '2016-01-28T20:51:07.263Z',
     '0.14.3': '2016-02-18T15:31:40.639Z',
     '0.14.4': '2016-02-18T20:03:43.363Z',
     '0.14.5': '2016-02-18T20:29:31.431Z',
     '0.14.6': '2016-02-18T20:39:48.812Z',
     '0.14.7': '2016-02-18T21:02:57.304Z',
     '0.14.10': '2016-03-06T15:06:22.040Z',
     '0.16.0': '2016-03-15T17:21:45.207Z',
     '0.16.1': '2016-03-23T20:56:10.555Z',
     '0.17.0': '2016-05-11T21:26:29.082Z',
     '0.17.1': '2016-05-16T19:53:33.118Z',
     '0.18.0': '2016-06-09T20:44:03.105Z',
     '0.18.1': '2016-07-10T00:31:16.725Z',
     '0.19.0': '2016-08-07T16:04:43.107Z',
     '0.19.1': '2016-08-07T23:40:57.578Z',
     '0.19.2': '2016-08-09T18:19:35.559Z',
     '0.19.3': '2016-08-16T19:45:30.592Z',
     '0.19.4': '2016-08-17T06:21:29.855Z',
     '0.20.0': '2016-10-19T19:45:37.343Z',
     '0.19.5': '2016-10-19T20:41:46.309Z',
     '0.19.6': '2016-10-24T23:14:59.588Z',
     '0.19.7': '2017-04-12T09:10:12.460Z',
     '0.19.8': '2017-04-18T05:44:50.059Z' },
  homepage: 'http://github.com/angular-ui/ui-select',
  repository: { url: 'git://github.com/angular-ui/ui-select.git' },
  author: 'http://github.com/angular-ui/ui-select/graphs/contributors',
  bugs: { url: 'https://github.com/angular-ui/ui-select/issues' },
  license: 'MIT',
  readmeFilename: 'README.md',
  users: { herrherrmann: true, sesamechee: true },
  main: './index.js',
  style: 'dist/select.css',
  version: '0.19.8',
  devDependencies: 
   { angular: '^1.2.18',
     'angular-mocks': '^1.2.18',
     'angular-sanitize': '^1.2.18',
     'conventional-changelog': '^0.5.3',
     'conventional-recommended-bump': '0.0.3',
     del: '~0.1.1',
     'event-stream': '~3.1.0',
     gulp: '^3.9.1',
     'gulp-angular-templatecache': '^1.8.0',
     'gulp-bump': '^1.0.0',
     'gulp-concat': '^2.6.0',
     'gulp-conventional-changelog': '^0.7.0',
     'gulp-filenames': '^2.0.0',
     'gulp-footer': '^1.0.5',
     'gulp-git': '^1.4.0',
     'gulp-header': '^1.7.1',
     'gulp-jshint': '^2.0.0',
     'gulp-load-plugins': '^1.1.0',
     'gulp-minify-css': '^1.2.4',
     'gulp-minify-html': '^1.0.6',
     'gulp-plumber': '^0.6.3',
     'gulp-replace': '^0.5.4',
     'gulp-sourcemaps': '^1.6.0',
     'gulp-tag-version': '^1.3.0',
     'gulp-uglify': '^1.5.3',
     'gulp-util': '^2.2.19',
     jquery: '~1.11',
     jshint: '^2.9.1',
     'jshint-stylish': '~0.3.0',
     karma: '^0.12.16',
     'karma-chrome-launcher': '^0.1.3',
     'karma-coverage': '~0.2',
     'karma-firefox-launcher': '~0.1',
     'karma-jasmine': '~0.2',
     'karma-ng-html2js-preprocessor': '^0.1.0',
     'karma-phantomjs-launcher': '~0.1.4',
     'run-sequence': '^1.1.5',
     streamqueue: '^1.1.1',
     'title-case': '^1.1.2' },
  scripts: { test: 'gulp test' },
  spm: { main: 'dist/select.js', output: [ 'dist/select.css' ] },
  gitHead: '32829a39e8efe7f94de049c6b529c23fedfc6686',
  description: '',
  dist: 
   { shasum: '74860848a7fd8bc494d9856d2f62776ea98637c1',
     tarball: 'https://registry.npmjs.org/ui-select/-/ui-select-0.19.8.tgz' },
  directories: {} }
```
node 8.0.0 yarn 0.27.5 macOS Sierra 10.12.5

### PR DESCRIPTION
**Pull request by neonowy**
**Summary**

Fixes #3947. By default, package `version` was set by sorting all the versions and getting the highest one. Now it's provided via package `latest` dist-tag.

**Test plan**
##### Before:
```bash
yarn info ui-select | grep version: 
  version: '0.20.0',
```
##### After:
```bash
$ yarn info ui-select | grep version:
   version: '0.19.8',
```

I've also added a test case for it in `__tests__/commands/info.js`.
Although, I'm not sure if using a specific package like `ui-select` (from #3947) is a proper way to do it, because it'll break with the new release.

Could we add it to the `__tests__/fixtures/request-cache/`, so the package manifest won't change? Or do you have some other idea how can I write this test better?

### CODE REVIEW

**Comment by rally25rs** [comment]
I think we need to combine this with a fix for #3560 as well, otherwise `info` and `add` commands will select different versions.

**Comment by arcanis** [comment]
@neonowy Can you check to add this logic to the install process as well?

As for the tests, the fixtures should get added to the folder after you run your tests. You then only have to add them to the commit, and it should be fine :+1:

**Comment by rally25rs** [comment]
@neonowy @arcanis - I'm working on the install half of this too. Getting some unit tests in place to reproduce the issue... Can hold off to see if I get it fixed on the install side. Might come in the form of a 2nd PR though...

**Comment by arcanis** [comment]
Great, thanks! :)

**Comment by rally25rs** [comment]
Pushed #4804 to tackle the `add` side of this.

File: src/cli/commands/info.js [hunk 1]
```diff
@@ -72,7 +72,7 @@ export async function run(config: Config, reporter: Reporter, flags: Object, arg
   const versions = result.versions;
   // $FlowFixMe
   result.versions = Object.keys(versions).sort(semver.compareLoose);
-  result.version = version || result.versions[result.versions.length - 1];
+  result.version = version || result['dist-tags'].latest;
```
Comment (BYK) [inline src/cli/commands/info.js]: Are we always guaranteed to have `dist-tags` and `['dist-tags'].latest`?

Comment (arcanis) [reply src/cli/commands/info.js]: Who knows, it's entirely up to the npm server implementation :/ For now I think we can make this assumption, and revisit if needed.

**Comment by arcanis** [comment]
@neonowy Can you rebase this PR? I tried to do it on my own, but Github denied me the permission to do so (have you unchecked the checkbox that gives us permission to update the PR?)

**Comment by neonowy** [comment]
@arcanis Rebased! :shipit: 

Sorry for the trouble with edit permission, apparently I've unchecked it when creating this PR.

**Comment by arcanis** [comment]
np, thanks!
