### PR TITLE
Fix yarn workspace command and add test

### LINKED ISSUE #4021: Yarn workspace commands running in wrong location
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Running `yarn workspace my-package upgrade classnames` changes the `package.json` at the top-level instead of the one at `./packages/my-package/package.json`

**Please mention your node.js, yarn and operating system version.**
Yarn v0.27.5
Node v7.1.0

### PR DESCRIPTION
**Pull request by thejameskyle**
Resolves #4021

This fixes the workspace command so that it runs in the correct directory and adds a test to validate it.

Previously the command was also relying on `process.argv` to get the executable path for `node` and `yarn`. However, that ends up being unreliable if yarn was run as part of another process (aka `jest`).

`process.execPath` will give you the correct path to `node` and I'm assuming `require.resolve('../bin/yarn.js')` will work for getting the correct path to the `yarn` executable (from the `constants.js` file). I have a feeling it might not work perfectly though... @Daniel15 might know?

cc @arcanis

### CODE REVIEW

**Comment by Daniel15** [comment]
I haven't looked at this PR in detail yet, but bin/yarn.js won't work when using the single-JS-file build (which I think is what we use internally at Facebook for example). The single file build only has the yarn-vX.X.X.js file. 

_Sent from my Samsung SAMSUNG-SM-G925A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by thejameskyle** [comment]
@Daniel15 looked into it, turns out webpack avoids that issue by replacing `require.resolve` with the module id:

```js
YARN_BIN_PATH = /*require.resolve*/(341);
```

**Comment by thejameskyle** [comment]
Okay I am now handling the case where we are inside of a bundle separately so that it doesn't look for the `../bin/yarn.js` file.

File: src/cli/commands/workspace.js [hunk 1]
```diff
@@ -39,8 +40,13 @@ export async function run(config: Config, reporter: Reporter, flags: Object, arg
     throw new MessageError(reporter.lang('workspaceUnknownWorkspace', workspaceName));
   }
 
+  const workspace = workspaces[workspaceName];
+
   try {
-    await child.spawn(process.argv[0], [process.argv[1], ...rest], {stdio: 'inherit'});
+    await child.spawn(NODE_BIN_PATH, [YARN_BIN_PATH, ...rest], {
```
Comment (BYK) [inline src/cli/commands/workspace.js]: May be we should use [child_process.fork()](https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options) for this instead?

File: scripts/build-webpack.js [hunk 2]
```diff
@@ -38,6 +38,10 @@ const compiler = webpack({
     libraryTarget: 'commonjs2',
   },
   target: 'node',
+  node: {
```
Comment (BYK) [inline scripts/build-webpack.js]: I think this needs a comment explaining why.

File: src/constants.js [hunk 3]
```diff
@@ -59,6 +60,17 @@ export const CONFIG_DIRECTORY = getDirectory('config');
...
 export const GLOBAL_MODULE_DIRECTORY = path.join(CONFIG_DIRECTORY, 'global');
 
+export const NODE_BIN_PATH = process.execPath;
+export const YARN_BIN_PATH = getYarnBinPath();
+
+function getYarnBinPath(): string {
+  if (isWebpackBundle) {
+    return __filename;
+  } else {
+    return path.join(__dirname, '..', 'bin', 'yarn.js');
```
Comment (BYK) [inline src/constants.js]: We shouldn't rely on this path since it can change drastically as you already mentioned in your comments.

Comment (arcanis) [inline src/constants.js]: Hm, if it changes, it will get caught by the tests, and we will simply have to update it.

File: src/constants.js [hunk 4]
```diff
@@ -2,6 +2,7 @@
 
 const path = require('path');
 const userHome = require('./util/user-home-dir').default;
+const isWebpackBundle = require('is-webpack-bundle');
```
Comment (arcanis) [inline src/constants.js]: I'm not sure we should use an external module for this - inlining it would allow webpack to remove the unneeded code at compile time.

**Comment by arcanis** [comment]
@BYK Of note, that's a different issue than #4030 - the problem here is that `yarn workspace <workspace>
 <command>` will run in the current folder instead of the workspace folder. The important bit is the added `cwd` option on the `spawn` call.

File: src/constants.js (hunk 4 above)
Comment (Daniel15) [inline src/constants.js]: >  inlining it would allow webpack to remove the unneeded code at compile time.

That's a good point. Is Webpack smart enough to eliminate the unneeded branch at compile time?

**Comment by BYK** [comment]
@thejameskyle  - I'd really love to move forward with this. Please let us know what you think about our comments.

File: src/constants.js (hunk 4 above)
Comment (arcanis) [inline src/constants.js]: I think so, but I'm not completely sure now that you mention it 🤔

Comment (thejameskyle) [inline src/constants.js]: Is it that important to remove one line of code?

File: src/constants.js (hunk 3 above)
Comment (thejameskyle) [inline src/constants.js]: There's not a lot of option otherwise, there's no reliable way of automatically getting the entry point to yarn. You have to manually handle each case

File: src/cli/commands/workspace.js (hunk 1 above)
Comment (thejameskyle) [inline src/cli/commands/workspace.js]: I think in the future it's probably worthwhile not to use a child process at all, would save a whole bunch of overhead

**Comment by thejameskyle** [comment]
Updated
