### PR TITLE
Properly skip installation of packages that do not need to be installed (incompatible optionalDependencies for example)

### LINKED ISSUE #1059: Errors from optionalDependency installation scripts should be ignored
**Do you want to request a _feature_ or report a _bug_?**
Bug, for compatibility with npm

**What is the current behavior?**
If an optionalDependency install script fails, the whole 'yarn install' fails.
With npm client, these errors are ignored and the install succeeds.

**If the current behavior is a bug, please provide the steps to reproduce.**
The sinopia npm package has an optionalDependency on fs-ext, whose install script fails in Windows. This is a known issue, but since it is optional the errors get ignored with 'npm install'; but fails with 'yarn'.

In a Windows machine:
yarn add sinopia

This happens even if ignore-optional=true.
If ignore-scripts=true, error goes away.

**What is the expected behavior?**
'yarn install' prints out the errors,  but the installation succeeds.

**Please mention your node.js, yarn and operating system version.**
node.js 6.7.0
yarn 0.15.1
Windows 10

### PR DESCRIPTION
**Pull request by mvestergaard**
**Summary**

This is a different approach to #1438 
It should make sure that packages incompatible with the current environment are not installed.
See #1954 for further motivation

With this change, any `optionalDependencies` that is incompatible with the environment will be skipped entirely in the install.

Installing a package.json like this on windows or linux:
```json
{
  "optionalDependencies": {
    "fsevents": "*"
  }
}
```
Will result in an empty node_modules folder, which is the same behavior as using `npm`.

**Test plan**

The current test 'root install with optional deps' should test the scenario on anything other than OSX. It uses `fsevents` which is only compatible with OSX.
To test on OSX you need to modify `__tests__/fixtures/install/root-install-with-optional-dependency/package.json` to use an optional package that is not compatible with OSX.
CI servers are running linux, so they should be fine.
After running install on a package with a single optional incompatible dependency, node_modules should be empty.

Fixes #1059 #1435

### CODE REVIEW

**Comment by mvestergaard** [comment]
Hmm I'm not entirely sure what's causing the check-lockfile script to fail.
It's passing on my machine. Any pointers on what to look for?

File: src/cli/commands/check.js [hunk 1]
```diff
@@ -40,7 +40,7 @@ export async function run(
   }
 
   // get patterns that are installed when running `yarn install`
-  const [, rawPatterns] = await install.hydrate();
+  const [, rawPatterns] = await install.hydrate(true);
```
Comment (bestander) [inline src/cli/commands/check.js]: Why is fetch true for a check operation?

Comment (mvestergaard) [inline src/cli/commands/check.js]: It's for this bit:
```js
await this.fetcher.init();
await this.compatibility.init();
```
It seems that if the fetcher is not run beforehand, the compatibility check does not have the os and cpu data for each package to properly do the check.

Comment (bestander) [inline src/cli/commands/check.js]: Would this work offline?
I am afraid that initing fetcher may cause a longer check

Comment (mvestergaard) [inline src/cli/commands/check.js]: That's a good question. I mean if the package is in the cache, it doesn't actually fetch anything, right?

Comment (mvestergaard) [inline src/cli/commands/check.js]: This happens if the fetch is not a part of the check:
```
yarn check v0.18.0-0
error chokidar#fsevents not installed
error fsevents#nan not installed
error fsevents#node-pre-gyp not installed
error node-pre-gyp#npmlog not installed
error node-pre-gyp#rc not installed
error node-pre-gyp#tar-pack not installed
error rc#deep-extend not installed
error tar-pack#fstream-ignore not installed
error rc#minimist not installed
error tar-pack#once not installed
error tar-pack#uid-number not installed
error Found 11 errors.
```

Because the check does not exclude those package due to incompatibility, it expects them to be there, which it shouldn't.

**Comment by mvestergaard** [comment]
@bestander I'll look into adding some tests tonight. 
I suppose it kind of needs to be able to catch any issue on all OS?
Relying on `fsevents` alone will only catch issues on windows and linux, so something alternative has to be done to test on OSX.

File: src/cli/commands/check.js (hunk 1 above)
Comment (bestander) [inline src/cli/commands/check.js]: Does check work with clean caches and offline for normal dependencies?

**Comment by bestander** [comment]
> I suppose it kind of needs to be able to catch any issue on all OS?
Relying on fsevents alone will only catch issues on windows and linux, so something alternative has to be done to test on OSX.

You could depend on a fake optional dependency that does not work on any OS.
In install command we use quite a few and save them in the test case' offline morror

File: src/cli/commands/check.js (hunk 1 above)
Comment (mvestergaard) [inline src/cli/commands/check.js]: I can imagine it doesn't.

What this change is mainly intended to do is to make sure that calls to `await install.linker.getFlatHoistedTree(rawPatterns);` will exclude any package that is incompatible, or any dependency of such a package.

To be able to determine if a package is incompatible, you would need to know the os and cpu requirement of packages while offline. In which case I guess it needs to be in the lock file or something?

Comment (bestander) [inline src/cli/commands/check.js]: Ah, it makes sense.
For cross platform modules - they are installed in node_modules and could be verified in place but the missing ones could be either "missing" or not installed because they are "optional".

Adding "optional" property to lockfile makes more sense but this needs a discussion involving more people, maybe an RFC?

Comment (bestander) [inline src/cli/commands/check.js]: As a matter of fact, I think there should be a third mode for check - https://github.com/yarnpkg/yarn/issues/1934.
I would rather rely on that and the integrity check than the default one

Comment (bestander) [inline src/cli/commands/check.js]: I wonder, if package is optional but it failed to install because you don't have a compiler, is it an error or is it ok?

Comment (mvestergaard) [inline src/cli/commands/check.js]: That should be an error.
In my opinion, if it is determined by the OS and CPU requirements of the package that your system is compatible, then any installation error that occurs, are out of the scope of yarn.

**Comment by mvestergaard** [comment]
@bestander How does one go about correctly generating one of those .tgz files found in the `mirror-for-offline` fixture folders?

**Comment by bestander** [comment]
> @bestander How does one go about correctly generating one of those .tgz files found in the mirror-for-offline fixture folders?

It is a bit involved.
Just run `npm pack` on a folder with package.json.
Then you'll need to manually edit yarn.lock file to add sha1 of the file, you could get it with some console.log in tarball-fetcher.js or use a sha1 util on Mac/linux.

**Comment by mvestergaard** [comment]
@bestander I added two tests.
The `dep-incompatible` package has this in it's package.json `"os": [ "invalid" ]` so it is considered incompatible on any OS.
It also has a dependency of `dep-a`. The second test verifies that `dep-a` is also skipped.

**Comment by bestander** [comment]
Great job, @mvestergaard, I'll have a look

**Comment by mvestergaard** [comment]
@bestander Any ETA on next release?

**Comment by bestander** [comment]
Saturday-Sunday this week

**Comment by friosl** [comment]
Several years later, this worked for me, I was trying to do CI in aws and the problem was that package :D
