### PR TITLE
fix #1556: add package name to unmet/incorrect peer dependency warning

### LINKED ISSUE #1556: Print more details on "Unmet peer dependency" warning
**Do you want to request a _feature_ or report a _bug_?**

Feature.

**What is the current behavior?**

When I add multiple packages and one/some of them cause `Unmet peer dependency` warning, there's no way to figure out which package(s) cause this except manually go through their `package.json`s.

**What is the expected behavior?**

Print which package(s) cause warning.

**Please mention your node.js, yarn and operating system version.**

``` shell
macOS v10.11.6
node v7.0.0
yarn v0.16.1
```

### PR DESCRIPTION
**Pull request by tuures**
fixes #1556

before:
`warning Unmet peer dependency "somedep@0.x.x".`

after:
`warning "somepackage@0.2.4" has unmet peer dependency "somedep@0.x.x".`

### CODE REVIEW

File: src/package-linker.js [hunk 1]
```diff
@@ -273,18 +273,25 @@ export default class PackageLinker {
       }
 
       // validate found peer dependency
-      if (foundDep) {
-        if (range === '*' || semver.satisfies(foundDep.version, range, this.config.looseSemver)) {
-          ref.addDependencies([foundDep.pattern]);
-        } else {
-          this.reporter.warn(this.reporter.lang('incorrectPeer', `${name}@${range}`));
-        }
+      const depOrError = foundDep
```
Comment (wyze) [inline src/package-linker.js]: This double ternary is hard to read. Please break it out into 2 variables.

**Comment by tuures** [comment]
@wyze Thanks for feedback! Rewrote the code and I think it's more readable now. Let me know if you spot anything that still needs to be addressed.

**Comment by SimenB** [comment]
This fixes #1809 as well, right?
