### PR TITLE
fix(upgrade): Let outdated filter correctly when called from upgrade.

### LINKED ISSUE #4735: `upgrade-interactive --latest` suggests to downgrade dependency
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
when running `yarn upgrade-interactive --latest` it suggests to install version 1.0.1

**If the current behavior is a bug, please provide the steps to reproduce.**

```
yarn add react-refetch@1.0.3-0
yarn upgrade-interactive --latest
```

**What is the expected behavior?**
I think it shouldn't suggest to downgrade 

**Please mention your node.js, yarn and operating system version.**
mac os high sierra
node 8.7.0
yarn 1.2.1

### PR DESCRIPTION
**Pull request by rally25rs**
Fixes #4735 

Upgrade was calling outdated in a way that would not filter packages that did not need
an upgrade. The led to potential backdate of package if a beta version was in use. Yarn would
backdate to the "older" latest.

**Summary**

Some older upgrade code I had written had a code path to have `getOutdatedPackages()` return all packages, not just ones that were actually outdated. My belief had been that it wouldn't cause an issue because upgrading to the same version would just do nothing... but it turns out if you are on a beta version of a package, this would cause `upgrade --latest` to backdate you to the actual latest.

So for example if you were currently at beta `1.0.3-0` and the registry had `latest 1.0.1` then `yarn upgrade --latest` would backdate you to `1.0.1`.

This PR reinstates the filter that only returns versions if the current is less-than the latest, which would in the above example leave the user at `1.0.3-0`

**Test plan**

Added a unit test that would have failed previously, but passes with this PR change.

### CODE REVIEW

**Comment by kaylieEB** [comment]
haha I had the same PR open! https://github.com/yarnpkg/yarn/pull/4756

File: src/package-request.js [hunk 1]
```diff
@@ -404,7 +403,6 @@ export default class PackageRequest {
     const isDepOld = ({current, latest, wanted}) =>
       latest === 'exotic' || (latest !== 'exotic' && (semver.lt(current, wanted) || semver.lt(current, latest)));
```
Comment (kaylieEB) [inline src/package-request.js]: I thought this deserves a quick cleanup `latest === 'exotic' || (semver.lt(current, wanted) || semver.lt(current, latest));`

Comment (rally25rs) [reply src/package-request.js]: Oh geez I'm sorry... I should read the thread first huh :)
I'll review yours and kill mine???

Comment (kaylieEB) [reply src/package-request.js]: oh i don't mind it at all. Yours has a test so let's go with that! I can close mine :)

Comment (rally25rs) [reply src/package-request.js]: Actually, since mine has a unit test, should we keep mine? I'll pull in your change above too... Sorry for the churn... just physically got back from vacation, but my brain is still at the beach 🌴 ...
