### PR TITLE
fix(console-reporter): Fix issue where tree logger was ignoring --silent/-s flag

### LINKED ISSUE #5721: --silent / -s not working for `upgrade`
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Outputs a lot of text in the terminal

**If the current behavior is a bug, please provide the steps to reproduce.**

`yarn upgrade --silent`

**What is the expected behavior?**
Skip Yarn console logs. Only other types of logs (script output) should be printed. This is the behavior that `yarn upgrade --help` says it should have.

**Please mention your node.js, yarn and operating system version.**
- Node: v9.11.1
- Yarn: 1.6.0
- macOS: 10.13.4

### PR DESCRIPTION
**Pull request by jxom**
**Summary**

This PR fixes #5721 where `upgrade` was not being silent when the `--silent`/`-s` flags were provided. It still printed the tree.  🖨🌳  

**Test plan**

Added two new test cases.

Manual CLI tests:

Before:
```
> yarn-local upgrade --silent
└─ left-pad@1.3.0
└─ left-pad@1.3.0
```

After:
```
> yarn-local upgrade --silent

```

### CODE REVIEW

**Comment by jxom** [comment]
cc/ @rally25rs

**Comment by rally25rs** [comment]
To add a test for `silent` you'll have to add a way to pass options into `__tests__/reporters/_mock.js` so that you can pass down a `silent: true` flag to the reporter constructor.

I can lend a hand with that if needed.

**Comment by jxom** [comment]
@BYK @rally25rs - can you take a look at those changes?

File: __tests__/reporters/_mock.js [hunk 1]
```diff
@@ -16,7 +16,8 @@ type MockCallback = (reporter: Reporter, opts: Object) => ?Promise<void>;
 export default function<T>(
   Reporter: Function,
   interceptor: Interceptor<T>,
-  prepare?: (reporter: Reporter) => any,
+  prepare?: ?(reporter: Reporter) => any,
+  opts?: Object,
```
Comment (BYK) [inline __tests__/reporters/_mock.js]: nit: this can be `extraOpts` and then you can avoid the `opts` -> `newOpts` rename.

File: __tests__/reporters/console-reporter.js [hunk 2]
```diff
@@ -266,3 +266,41 @@ test('close', async () => {
     }),
   ).toMatchSnapshot();
 });
+
+test('ConsoleReporter.log is silent when isSilent is true', async () => {
```
Comment (BYK) [inline __tests__/reporters/console-reporter.js]: Drop the 'ConsoleReporter.' prefix please :)

Comment (BYK) [reply __tests__/reporters/console-reporter.js]: Scratch that, just realized the whole file does this.

File: __tests__/reporters/_mock.js (hunk 1 above)
Comment (jxom) [reply __tests__/reporters/_mock.js]: Yeah, I was thinking that too. But thought it would have been preferred to keep the argument named as `opts`. Let me know if you want to change though 😄

Comment (BYK) [reply __tests__/reporters/_mock.js]: Nope, already merged :D
