### PR TITLE
Fallbacks to /tmp if the preferred cache folder isn't writable

### LINKED ISSUE #4141: Fix: yarn should check if the cache folder is usable before committing to it
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Yarn directly assumes it can use the cache folder and goes ahead to create it. The thing is, sometimes even if it can create the folder, it may not be able to write into it or read from it. Even more, the creation is also not guaranteed and there are no safe guards for this. Thus, if for some reason this fails, yarn falls flat on its face.

**If the current behavior is a bug, please provide the steps to reproduce.**

Try running `yarn --cahe-folder=/root/.yarn-cache` as a normal user for instance.

**What is the expected behavior?**

Yarn should detect the issue right from the start and send out a clear message. Even better: print a warning about the cache folder not being usable and falling back to the system-provided tmp folder so things work properly.

**Please mention your node.js, yarn and operating system version.**

Latest master.

### PR DESCRIPTION
**Pull request by arcanis**
**Summary**

Fixes #4141. If `$(yarn cache dir)` isn't writable, Yarn will crash and burn with EACCESS / EPERM. This patch adds a fallback mechanism so that we try different folders until we find one that fits. As a first step, I've added `/tmp/.yarn-cache`.

**Test plan**

Tested with

```
chmod 000 /Users/mael/Library/Caches/Yarn && ~/yarn/bin/yarn
```

### CODE REVIEW

File: src/config.js [hunk 1]
```diff
@@ -276,9 +276,27 @@ export default class Config {
...
-    );
+
+    let cacheRootFolder = opts.cacheFolder || this.getOption('cache-folder', true);
+
+    for (let t = 0; t < constants.PREFERRED_MODULE_CACHE_DIRECTORIES.length && !cacheRootFolder; ++t) {
+      const tentativeCacheFolder = constants.PREFERRED_MODULE_CACHE_DIRECTORIES[t];
+
+      try {
+        await fs.mkdirp(tentativeCacheFolder);
+        await fs.writeFile(path.join(tentativeCacheFolder, constants.WTEST_FILENAME), `testing write access`);
```
Comment (BYK) [inline src/config.js]: I think we should use [fs.access](https://nodejs.org/api/fs.html#fs_fs_access_path_mode_callback) with both read and write checks.

File: src/config.js [hunk 2]
```diff
@@ -276,9 +276,27 @@ export default class Config {
...
-      opts.cacheFolder || this.getOption('cache-folder', true) || constants.MODULE_CACHE_DIRECTORY,
-    );
+
+    let cacheRootFolder = opts.cacheFolder || this.getOption('cache-folder', true);
+
+    for (let t = 0; t < constants.PREFERRED_MODULE_CACHE_DIRECTORIES.length && !cacheRootFolder; ++t) {
+      const tentativeCacheFolder = constants.PREFERRED_MODULE_CACHE_DIRECTORIES[t];
+
+      try {
+        await fs.mkdirp(tentativeCacheFolder);
```
Comment (BYK) [inline src/config.js]: I'd separate this part out and try cleaning up the cache directory if we created it but it is not usable. Kind of an edge case tho, so not feeling too strongly about this.

File: src/config.js [hunk 3]
```diff
@@ -276,9 +276,27 @@ export default class Config {
...
+        cacheRootFolder = tentativeCacheFolder;
+      } catch (error) {
+        this.reporter.warn(this.reporter.lang('cacheFolderSkipped', tentativeCacheFolder));
+      }
+    }
+
+    if (!cacheRootFolder) {
+      throw new MessageError(this.reporter.lang('cacheFolderMissing'));
+    } else {
+      this._cacheRootFolder = String(cacheRootFolder);
```
Comment (BYK) [inline src/config.js]: Why do you need the `String()` casting?

File: src/constants.js [hunk 4]
```diff
@@ -46,15 +46,21 @@ function getDirectory(category: string): string {
   return path.join(userHome, `.${category}`, 'yarn');
 }
 
-function getCacheDirectory(): string {
+function getPreferredCacheDirectories(): Array<string> {
+  const preferredCacheDirectories = [getDirectory('cache')];
+
+  if (process.platform !== 'win32') {
+    preferredCacheDirectories.unshift('/tmp/.yarn-cache');
```
Comment (BYK) [inline src/constants.js]: Nope. Use [os.tmpdir()](https://nodejs.org/api/os.html#os_os_tmpdir) please. Note that this is also platform independent.

File: src/constants.js [hunk 5]
```diff
@@ -46,15 +46,21 @@ function getDirectory(category: string): string {
...
+  }
+
   if (process.platform === 'darwin') {
-    return path.join(userHome, 'Library', 'Caches', 'Yarn');
+    preferredCacheDirectories.unshift(path.join(userHome, 'Library', 'Caches', 'Yarn'));
```
Comment (BYK) [inline src/constants.js]: This kind of changes our previous logic so not sure about that. We should directly fallback to `tmp` when our first choice fails. With this one, it will try this on OS X and then try the Linux version second.

File: src/config.js [hunk 6]
```diff
@@ -276,9 +276,27 @@ export default class Config {
       networkConcurrency: this.networkConcurrency,
       networkTimeout: this.networkTimeout,
     });
-    this._cacheRootFolder = String(
-      opts.cacheFolder || this.getOption('cache-folder', true) || constants.MODULE_CACHE_DIRECTORY,
-    );
+
+    let cacheRootFolder = opts.cacheFolder || this.getOption('cache-folder', true);
```
Comment (BYK) [inline src/config.js]: This should be pushed to the top of the list we try and we should fall back to `tmp` at all times for resilliency. Right now this override seems to be ignored.

**Comment by BYK** [comment]
We also need automated tests for this.

File: src/config.js (hunk 6 above)
Comment (arcanis) [inline src/config.js]: I disagree - if the explicitely specified cache folder cannot be used, that's an hard error. This option contract forces us to use this folder. By (almost) silently using a different directory, we might end up with subtle bugs. For example, two Yarn process might run concurrently with different caches. In such a scenario, if for some reason their respective cache could not be reached, they would end up corrupting themselves.

File: src/config.js (hunk 3 above)
Comment (arcanis) [inline src/config.js]: Was there before. Probably because of Flow, I'd guess :)

File: src/config.js (hunk 1 above)
Comment (arcanis) [inline src/config.js]: Thinking of it, I think this would still have issues (since the cache folders have to be assumed empty, we would have to make the check on the directory itself, which might yield different results than what we would have add on a file). However, I'll also add a read on the file to account for the read permissions. Does that sounds ok?

Comment (arcanis) [inline src/config.js]: After discussing this with @BYK we came to the conclusion that `--cache-folder` would keep its current semantic (and would crash if the directory is not writable) since it would break the commonly assumed contract, potentially exposing the application to vulnerabilities (the `/tmp` folder could be world-readable whereas the `--cache-folder` wouldn't). However, we'll also add a `--preferred-cache-folder` option with less restrictions. Will even make it easier to test the feature :)

Comment (BYK) [inline src/config.js]: >Thinking of it, I think this would still have issues (since the cache folders have to be assumed empty, we would have to make the check on the directory itself, which might yield different results than what we would have add on a file). However, I'll also add a read on the file to account for the read permissions. Does that sounds ok?

I don't see how this can be the case? If you can create a file in the directory it should be equivalent to `fs.access` with write permissions. Same goes for read. We can make the case for space exhaustion in the cache directory (if it is on a different drive etc.) but this doesn't protect us against that anyways.

File: src/config.js (hunk 3 above)
Comment (BYK) [inline src/config.js]: May be we can remove it now?

File: src/config.js (hunk 6 above)
Comment (BYK) [inline src/config.js]: For the readers of this thread, if there are any: we have talked about getting a unique folder once we fallback to `tmp` like by using a timestamp or the PID of the process, or both, but then decided to do this: https://github.com/yarnpkg/yarn/pull/4143#discussion_r132509455

We should still probably try to ensure a unique folder in `tmp` when we fallback for safety.

File: src/config.js [hunk 7]
```diff
@@ -276,9 +276,27 @@ export default class Config {
...
+
+    for (let t = 0; t < constants.PREFERRED_MODULE_CACHE_DIRECTORIES.length && !cacheRootFolder; ++t) {
```
Comment (BYK) [inline src/config.js]: `&& !cacheRootFolder` part totally gets lost in the code. Please make this an explicit `if` statement for clarity.

Also half-joking, half-serious: why are we using `t` as the counter and not `i`? 🗡

File: src/config.js (hunk 1 above)
Comment (arcanis) [inline src/config.js]: > If you can create a file in the directory it should be equivalent to fs.access with write permissions.

Yes but the file we've created might not be accessible. Umask, etc.

File: src/config.js (hunk 7 above)
Comment (arcanis) [inline src/config.js]: Good question, but I don't really know 😆 I've been using it for single-level loop since I started programming (and `u`/`v`/`w` or `x`/`y`/`z` when multiple loops are combined).

Could be amusing to run a search on the github repos to find what variable name is preferred by developpers :)

Comment (arcanis) [inline src/config.js]: Looking on stack exchange, it seems that literally noone else is using `t` as a variable name ... I wonder how I came to that. Meh ¯\(ツ)/¯

File: src/config.js (hunk 1 above)
Comment (BYK) [inline src/config.js]: I really think we should just use `fs.access` here.

File: src/config.js (hunk 3 above)
Comment (arcanis) [inline src/config.js]: Just tried, still fails.

File: src/config.js [hunk 8]
```diff
@@ -276,9 +276,41 @@ export default class Config {
...
+        preferredCacheFolders = [preferredCacheFolder].concat(preferredCacheFolders);
+      }
+
+      for (let t = 0; t < preferredCacheFolders.length && !cacheRootFolder; ++t) {
+        const tentativeCacheFolder = preferredCacheFolders[t];
+
+        try {
+          await fs.mkdirp(tentativeCacheFolder);
+          // eslint-disable-next-line
+          await fs.access(tentativeCacheFolder, fs.constants.R_OK | fs.constants.W_OK | fs.constants.X_OK);
```
Comment (BYK) [inline src/config.js]: Why do we need to check for execution? (`fs.constants.X_OK`)

File: src/reporters/lang/en.js [hunk 9]
```diff
@@ -174,6 +174,11 @@ const messages = {
   workspaceNameMandatory: 'Missing name in workspace at $0, ignoring.',
   workspaceNameDuplicate: 'There are more than one workspace with name $0',
 
+  cacheFolderSkipped: 'Skipping preferred cache folder $0 because it is not writable.',
+  cacheFolderMissing:
+    "Yarn hasn't been able to find a cache folder. Please use an explicit --cache-folder option to tell it what location to use, or make one of the preferred locations writable.",
```
Comment (BYK) [inline src/reporters/lang/en.js]: >Yarn hasn't been able to find a cache folder.

find a cache folder it can use

>Please use an explicit --cache-folder option

use *the* explicit --cache-folder option

File: src/reporters/lang/en.js [hunk 10]
```diff
@@ -174,6 +174,11 @@ const messages = {
...
+  cacheFolderSelected: 'Selected the next writable cache folder in the list, will be $0.',
```
Comment (BYK) [inline src/reporters/lang/en.js]: I think it is better to make this a verbose message and say "Using cache folder: $0".

File: src/constants.js [hunk 11]
```diff
@@ -46,15 +47,24 @@ function getDirectory(category: string): string {
...
   if (process.platform === 'darwin') {
-    return path.join(userHome, 'Library', 'Caches', 'Yarn');
+    preferredCacheDirectories.push(path.join(userHome, 'Library', 'Caches', 'Yarn'));
+  }
+
+  preferredCacheDirectories.push(getDirectory('cache'));
+
+  if (process.platform !== 'win32') {
+    preferredCacheDirectories.push(path.join(os.tmpdir(), '.yarn-cache'));
+    preferredCacheDirectories.push('/tmp/.yarn-cache');
```
Comment (BYK) [inline src/constants.js]: You don't need this anymore.

File: src/constants.js [hunk 12]
```diff
@@ -46,15 +47,24 @@ function getDirectory(category: string): string {
...
+
   if (process.platform === 'darwin') {
-    return path.join(userHome, 'Library', 'Caches', 'Yarn');
+    preferredCacheDirectories.push(path.join(userHome, 'Library', 'Caches', 'Yarn'));
+  }
+
+  preferredCacheDirectories.push(getDirectory('cache'));
+
+  if (process.platform !== 'win32') {
+    preferredCacheDirectories.push(path.join(os.tmpdir(), '.yarn-cache'));
```
Comment (BYK) [inline src/constants.js]: Why omit Windows??

File: src/util/fs.js [hunk 13]
```diff
@@ -13,6 +13,12 @@ const globModule = require('glob');
 const os = require('os');
 const path = require('path');
 
+export const constants = typeof fs.constants !== 'undefined' ? fs.constants : {
```
Comment (BYK) [inline src/util/fs.js]: Comment about the reason for this switch please. (Node 4/Node 5+)

File: src/config.js (hunk 8 above)
Comment (arcanis) [inline src/config.js]: You can't traverse folders if they are not executable.

Comment (BYK) [inline src/config.js]: TIL. Thanks!

File: src/cli/index.js [hunk 14]
```diff
@@ -60,6 +60,7 @@ export function main({
     '--modules-folder <path>',
     'rather than installing modules into the node_modules folder relative to the cwd, output them here',
   );
+  commander.option('--preferred-cache-folder <path>', 'specify a custom folder to store the yarn cache if possible');
   commander.option('--cache-folder <path>', 'specify a custom folder to store the yarn cache');
```
Comment (Timo82) [inline src/cli/index.js]: Hallo und weg

File: __tests__/integration.js [hunk 15]
```diff
@@ -70,3 +72,43 @@ test('--mutex network', async () => {
...
+  const cacheFolder = path.join(cwd, '.cache');
+
+  await fs.mkdirp(cacheFolder);
+
+  const command = path.resolve(__dirname, '../bin/yarn');
+  const args = ['--preferred-cache-folder', cacheFolder];
+
+  const options = {cwd};
+
+  {
```
Comment (BYK) [inline __tests__/integration.js]: I don't understand these custom blocks. Why do we need them and how do they work?

File: __tests__/integration.js [hunk 16]
```diff
@@ -70,3 +72,43 @@ test('--mutex network', async () => {
...
+    const stdoutPromise = misc.consumeStream(stdout);
+    const stderrPromise = misc.consumeStream(stderr);
+
+    const [stdoutOutput, stderrOutput] = await Promise.all([stdoutPromise, stderrPromise]);
+
+    expect(stdoutOutput.toString().trim()).toEqual(path.join(cacheFolder, `v${constants.CACHE_VERSION}`));
+    expect(stderrOutput.toString()).not.toMatch(/Skipping preferred cache folder/);
+  }
+
+  await fs.chmod(cacheFolder, 0o000);
```
Comment (BYK) [inline __tests__/integration.js]: It looks like these should be two separate test cases:
```
describe('cache folder fallback', () => {
  test('use --preferred-cache-folder when available', async () => {
    ...
  });

  test('fallback to default cache when --preferred-cache-folder is not available', async () => {
    ...
  });
});

File: __tests__/integration.js [hunk 17]
```diff
@@ -70,3 +72,43 @@ test('--mutex network', async () => {
...
+
+  {
+    const {stderr, stdout} = execa(command, ['cache', 'dir'].concat(args), options);
+
+    const stdoutPromise = misc.consumeStream(stdout);
+    const stderrPromise = misc.consumeStream(stderr);
+
+    const [stdoutOutput, stderrOutput] = await Promise.all([stdoutPromise, stderrPromise]);
+
+    expect(stdoutOutput.toString().trim()).toEqual(
```
Comment (BYK) [inline __tests__/integration.js]: We can probably use `.toMatchSnapshot()` in both cases which is easier?

File: src/cli/commands/cache.js [hunk 18]
```diff
@@ -55,7 +55,7 @@ export const {run, setFlags, examples} = buildSubCommands('cache', {
   },
 
   dir(config: Config, reporter: Reporter) {
-    reporter.log(config.cacheFolder);
+    reporter.log(config.cacheFolder, {force: true});
```
Comment (BYK) [inline src/cli/commands/cache.js]: I am not happy with this solution since I think it needs a better overall solution as we have discussed. Let's have a `TODO` comment here saying "Don't use force option and fix this ASAP" or something along those lines so we don't forget?

File: src/cli/index.js [hunk 19]
```diff
@@ -60,7 +60,8 @@ export function main({
     '--modules-folder <path>',
     'rather than installing modules into the node_modules folder relative to the cwd, output them here',
   );
-  commander.option('--cache-folder <path>', 'specify a custom folder to store the yarn cache');
+  commander.option('--preferred-cache-folder <path>', 'specify a custom folder to store the yarn cache if possible');
```
Comment (BYK) [inline src/cli/index.js]: Better to say "prefer a custom cache folder when it is available". We can make this change in a follow-up.

File: src/cli/index.js [hunk 20]
```diff
@@ -60,7 +60,8 @@ export function main({
...
+  commander.option('--cache-folder <path>', 'specify a custom folder that must be used to store the yarn cache');
```
Comment (BYK) [inline src/cli/index.js]: A+ with the added emphasis with "must be". 👍

File: src/config.js [hunk 21]
```diff
@@ -276,9 +276,41 @@ export default class Config {
...
+
+    if (!cacheRootFolder) {
+      let preferredCacheFolders = constants.PREFERRED_MODULE_CACHE_DIRECTORIES;
+      const preferredCacheFolder = opts.preferredCacheFolder || this.getOption('preferred-cache-folder', true);
+
+      if (preferredCacheFolder) {
+        preferredCacheFolders = [preferredCacheFolder].concat(preferredCacheFolders);
+      }
+
+      for (let t = 0; t < preferredCacheFolders.length && !cacheRootFolder; ++t) {
```
Comment (BYK) [inline src/config.js]: Let's just use `i` when it is available in loops? :D

File: src/config.js [hunk 22]
```diff
@@ -276,9 +276,41 @@ export default class Config {
...
+        const tentativeCacheFolder = String(preferredCacheFolders[t]);
```
Comment (BYK) [inline src/config.js]: I'm guessing this is to silence Flow. Note to self: look into this since it may be pointing to a possibly `undefined` value which would break Yarn.

File: src/config.js (hunk 8 above)
Comment (BYK) [inline src/config.js]: On second thought, we may wanna add a comment about this since I'm not sure if "You can't traverse folders if they are not executable." is common knowledge. What do you think?

File: src/config.js [hunk 23]
```diff
@@ -276,9 +276,41 @@ export default class Config {
...
+          await fs.mkdirp(tentativeCacheFolder);
+          // eslint-disable-next-line
+          await fs.access(tentativeCacheFolder, fs.constants.R_OK | fs.constants.W_OK | fs.constants.X_OK);
+          cacheRootFolder = tentativeCacheFolder;
+        } catch (error) {
+          this.reporter.warn(this.reporter.lang('cacheFolderSkipped', tentativeCacheFolder));
+        }
+
+        if (cacheRootFolder && t > 0) {
+          this.reporter.warn(this.reporter.lang('cacheFolderSelected', cacheRootFolder));
```
Comment (BYK) [inline src/config.js]: Note to self: make this information an info or debug level message for all cases to signal which cache folder is being used for each run.

File: src/constants.js [hunk 24]
```diff
@@ -46,15 +47,21 @@ function getDirectory(category: string): string {
...
+
   if (process.platform === 'darwin') {
-    return path.join(userHome, 'Library', 'Caches', 'Yarn');
+    preferredCacheDirectories.push(path.join(userHome, 'Library', 'Caches', 'Yarn'));
+  } else {
+    preferredCacheDirectories.push(getDirectory('cache'));
   }
 
-  return getDirectory('cache');
+  preferredCacheDirectories.push(path.join(os.tmpdir(), '.yarn-cache'));
```
Comment (BYK) [inline src/constants.js]: We should probably append a timestamp or something to the `'.yarn-cache'` name to make it unique across instances and runs? What do you think? (can be a follow-up)

File: src/reporters/base-reporter.js [hunk 25]
```diff
@@ -195,7 +195,7 @@ export default class BaseReporter {
   success(message: string) {}
 
   // a simple log message
-  log(message: string) {}
+  log(message: string, {force = false}: {force?: boolean} = {}) {}
```
Comment (BYK) [inline src/reporters/base-reporter.js]: Similar to above comment: let's add a TODO discouraging using this option.

File: src/util/fs.js [hunk 26]
```diff
@@ -13,6 +13,15 @@ const globModule = require('glob');
 const os = require('os');
 const path = require('path');
 
+export const constants =
+  typeof fs.constants !== 'undefined'
```
Comment (BYK) [inline src/util/fs.js]: Comment about Node 4 compatibility here would be great so in the future we don't get confused about this code.

File: __tests__/integration.js (hunk 15 above)
Comment (arcanis) [inline __tests__/integration.js]: The `let` variables declared inside are lexically bound. It allows me to reuse the variable name and underlying that those two blocks are checking the same thing. It could as well be a function, but since there are only two invocations I figured it was simpler to just duplicate the part of the code.

File: __tests__/integration.js (hunk 17 above)
Comment (arcanis) [inline __tests__/integration.js]: I'm not sure snapshots are needed here since the result shouldn't ever change. I prefer to test with the explicit value because otherwise, it wouldn't test this PR (for example, the test suite fails on Windows because for some reason the fallback is used when it shouldn't. I wouldn't have seen this problem with snapshots).

File: __tests__/integration.js (hunk 15 above)
Comment (BYK) [inline __tests__/integration.js]: I'd prefer if you can make this a function since it would make the code easier to follow. I don't remember seen usage unnamed, custom blocks in a project I have worked on and it would really surprise me as it did right now. I understand that we can leverage the block-scoping with `let` and `const` but I think this makes the code less maintainable and harder to reason about.

**Comment by shaunc** [comment]
Is this potentially a security hole (as /tmp is often writable by other users)?

**Comment by BYK** [comment]
>Is this potentially a security hole (as /tmp is often writable by other users)?

If you specify a cache folder explicitly with `--cache-folder` Yarn fails if it cannot use it, precisely because of this concern. For the common case, I'm not so sure.

**Comment by shaunc** [comment]
I would prefer that the default be secure and explicit config required for insecure usage, rather than the other way around. (E.g. have `--no-cache-folder` or some such to allow search... or maybe more sensible --cache-folder-fallback ...)

**Comment by BYK** [comment]
>I would prefer that the default be secure and explicit config required for insecure usage, rather than the other way around. (E.g. have --no-cache-folder or some such to allow search... or maybe more sensible --cache-folder-fallback ...)

For `--no-cache`, follow https://github.com/yarnpkg/rfcs/pull/53 please. We intend to ship that now. For the fallback part, are you suggesting we have `--no-cache-fallback` by default and when people enable it explicitly, use the fallback mechanisms?

**Comment by shaunc** [comment]
> you suggesting we have --no-cache-fallback by default and when people enable it explicitly, use the fallback mechanisms?

Yes ... or at the very least warn unless they have explicitly enabled. IMHO if someone doesn't have default cache location writable then 1) there is a reason for it or 2) there is no reason for it, but, either way, getting the user to think about it seems a good idea. Using /tmp without the user being conscious of it seems like a hack.

**Comment by BYK** [comment]
>Yes ... or at the very least warn unless they have explicitly enabled. 

This is what happens right now.

>IMHO if someone doesn't have default cache location writable then 1) there is a reason for it or 2) there is no reason for it, but, either way, getting the user to think about it seems a good idea. Using /tmp without the user being conscious of it seems like a hack.

Again, a warning is printed and we are thinking about a `--strict` mode, where having warnings would cause yarn to quit early with an error code. I think that combination would give you what you expect, right?

**Comment by shaunc** [comment]
Ah ... vg -- didn't realize there was an automatic warning. Yes -- "strict mode" sounds like a good idea; its documentation should point out that it has security benefits (as well as any other features -- I can imagine that over time various checks that would be a pain to configure separately could be included). Seems like it should be recommended for production builds.

Thanks!
