### PR TITLE
Fixes link: protocol linking

### LINKED ISSUE #3810: Link: protocol dependencies are not removed when the dependency changes
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The symlink is not removed even once the dependency has been removed from the package.json

**If the current behavior is a bug, please provide the steps to reproduce.**
```bash
set -e

rm -rf node_modules yarn.lock package.json

echo '{"dependencies":{"foo":"link:./hello-world"}}' > package.json
yarn

if [[ ! -L ./node_modules/foo ]]; then
    echo 'Failing (1)'
    exit 1
fi

echo '{}' > package.json
yarn

if [[ -L ./node_modules/foo ]]; then
    echo 'Failing (2)'
    exit 1
fi
```

**What is the expected behavior?**
The symlink should be removed

**Please mention your node.js, yarn and operating system version.**
yarn 0.27.5

### PR DESCRIPTION
**Pull request by arcanis**
**Summary**

Fixes #3810 

**Test plan**

Adds a new test

### CODE REVIEW

File: src/package-linker.js [hunk 1]
```diff
@@ -251,10 +251,41 @@ export default class PackageLinker {
...
 
-    // linked modules
-    for (const loc of possibleExtraneous) {
-      const stat = await fs.lstat(loc);
+    // if an extraneous is an entry created via "yarn link", we prevent it from being overwritten
+    // unfortunately, the only mean we have to know if they have been created this way is to check if
+    // they are a symlink - problem is that it then conflicts with the newly introduced "link:" protocol,
+    // which also creates symlinks :( a somewhat weak fix is to check if the symlink target is registered
+    // inside the linkFolder, in which case we assume it has been created via "yarn link". Otherwise, we
+    // remove it as usual.
```
Comment (arcanis) [inline src/package-linker.js]: Cf this comment for the rational behind this change

File: src/package-linker.js [hunk 2]
```diff
@@ -251,10 +251,41 @@ export default class PackageLinker {
...
+    const linkTargets = new Map();
+
+    for (const entry of await fs.readdir(this.config.linkFolder)) {
+      const entryPath = path.join(this.config.linkFolder, entry);
+      const stat = await fs.lstat(entryPath);
       if (stat.isSymbolicLink()) {
+        linkTargets.set(entry, await fs.readlink(entryPath));
+      } else if (stat.isDirectory()) {
+        for (const entry2 of await fs.readdir(entryPath)) {
```
Comment (BYK) [inline src/package-linker.js]: This logic needs to be explained. Why do we not recurse but just check one-level deep?

File: src/package-linker.js [hunk 3]
```diff
@@ -251,10 +251,41 @@ export default class PackageLinker {
...
+          const entryPath2 = path.join(entryPath, entry2);
+          const stat2 = await fs.lstat(entryPath2);
```
Comment (BYK) [inline src/package-linker.js]: May be use better variable names like `statsInner` or something?

File: src/package-linker.js [hunk 4]
```diff
@@ -251,10 +251,41 @@ export default class PackageLinker {
...
+          if (stat2.isSymbolicLink()) {
+            linkTargets.set(`${entry}/${entry2}`, await fs.readlink(entryPath2));
+          }
+        }
+      }
+    }
+
+    for (const loc of possibleExtraneous) {
```
Comment (BYK) [inline src/package-linker.js]: `possiblyExtraneous` or `maybeExtraneous`?

File: src/package-linker.js [hunk 5]
```diff
@@ -251,10 +251,41 @@ export default class PackageLinker {
...
+      const basename = path.basename(loc);
+      const parentname = path.basename(path.dirname(loc));
```
Comment (BYK) [inline src/package-linker.js]: May be use `path.parse()` instead? (https://nodejs.org/api/path.html#path_path_parse_path)

File: src/package-linker.js [hunk 6]
```diff
@@ -251,10 +251,41 @@ export default class PackageLinker {
...
+
+      const checkname = parentname[0] === `@` ? `${parentname}/${basename}` : basename;
```
Comment (BYK) [inline src/package-linker.js]: No idea what are we doing or why we are we doing it here. Are we checking for scoped packages? If so can we use more descriptive variable names like `isScopedPackage` or similar?

File: src/package-linker.js [hunk 7]
```diff
@@ -251,10 +251,41 @@ export default class PackageLinker {
...
+
+      if (
+        (await fs.lstat(loc)).isSymbolicLink() &&
+        linkTargets.has(checkname) &&
```
Comment (BYK) [inline src/package-linker.js]: No need for the `.has()` check since `.get()` returns `undefined` if the key doesn't exist.

File: src/util/fs.js [hunk 8]
```diff
@@ -253,6 +253,11 @@ async function buildActionsForCopy(
       }
     }
 
+    if (destStat && destStat.isSymbolicLink()) {
+      await unlink(dest);
+      destStat = null;
```
Comment (BYK) [inline src/util/fs.js]: A comment about why we set this to `null` would be nice.

File: __tests__/commands/install/integration.js [hunk 9]
```diff
@@ -152,6 +152,31 @@ test.concurrent(
...
 
+test.concurrent('replace the symlink when it changes, when using the link: protocol', async () => {
+  await runInstall({}, 'install-link', async (config, reporter): Promise<void> => {
+    const lockfile = await Lockfile.fromDirectory(config.cwd);
+
+    const pkgJson = await fs.readJson(`${config.cwd}/package.json`);
+    pkgJson.dependencies['test-missing'] = 'link:barbaz';
+    await fs.writeFile(`${config.cwd}/package.json`, JSON.stringify(pkgJson));
+
+    const install2 = new Install({}, config, reporter, lockfile);
```
Comment (arcanis) [inline __tests__/commands/install/integration.js]: runInstall does the first one, and this is the second one

File: src/package-linker.js [hunk 10]
```diff
@@ -251,10 +251,41 @@ export default class PackageLinker {
       }
     }
 
-    // linked modules
-    for (const loc of possibleExtraneous) {
-      const stat = await fs.lstat(loc);
+    // if an extraneous is an entry created via "yarn link", we prevent it from being overwritten
```
Comment (arcanis) [inline src/package-linker.js]: Nope, in this context `extraneous` is used as a name (like in `possibleExtraneous`)

File: __tests__/commands/install/integration.js [hunk 11]
```diff
@@ -152,6 +152,31 @@ test.concurrent(
...
+    const expectPath = path.join(config.cwd, 'node_modules', 'test-missing');
+
+    const stat = await fs.lstat(expectPath);
+    expect(stat.isSymbolicLink()).toEqual(true);
+
+    const target = await fs.readlink(expectPath);
+    if (process.platform !== 'win32') {
+      expect(target).toEqual('../barbaz');
+    } else {
+      expect(target).toMatch(/[\\\/]barbaz[\\\/]$/);
```
Comment (arcanis) [inline __tests__/commands/install/integration.js]: This test is took from the one above. Testing a single one might work, but I don't think we have any guarantee regarding which one is used.

File: src/package-linker.js [hunk 12]
```diff
@@ -251,10 +251,41 @@ export default class PackageLinker {
...
+    // unfortunately, the only mean we have to know if they have been created this way is to check if
+    // they are a symlink - problem is that it then conflicts with the newly introduced "link:" protocol,
+    // which also creates symlinks :( a somewhat weak fix is to check if the symlink target is registered
+    // inside the linkFolder, in which case we assume it has been created via "yarn link". Otherwise, we
+    // remove it as usual.
+    const linkTargets = new Map();
```
Comment (arcanis) [inline src/package-linker.js]: Because a `Map` is semantically better, and is already used at various places in the code

File: src/package-linker.js (hunk 2 above)
Comment (arcanis) [inline src/package-linker.js]: scopped packages, ie. `@fakescope/fake-package`

File: src/util/fs.js (hunk 8 above)
Comment (arcanis) [inline src/util/fs.js]: if we don't, the `destStat` (ie. the stat object that contains the infos regarding `dest`) will be wrong, since we've just deleted it.

File: src/package-linker.js (hunk 4 above)
Comment (arcanis) [inline src/package-linker.js]: This is an already existing variable.

File: src/package-linker.js (hunk 7 above)
Comment (arcanis) [inline src/package-linker.js]: Yeah but we don't want to execute the `readlink` if the key doesn't exists.

File: src/package-linker.js (hunk 6 above)
Comment (arcanis) [inline src/package-linker.js]: We need to get the key inside the `linkTargets` map - ie the package name.

File: src/package-linker.js (hunk 5 above)
Comment (arcanis) [inline src/package-linker.js]: I'm not sure it would be much clearer -

```js
const parsedPath = path.parse(loc);

const basename = parsedPath.base;
const parentname = path.basename(parsedPath.dir);
```

File: __tests__/commands/install/integration.js (hunk 9 above)
Comment (BYK) [inline __tests__/commands/install/integration.js]: Okay, how about `secondInstall` or `secondRound` for a more descriptive name then?

File: __tests__/commands/install/integration.js (hunk 11 above)
Comment (BYK) [inline __tests__/commands/install/integration.js]: Alright, thanks for the clarification :)

File: src/package-linker.js (hunk 4 above)
Comment (BYK) [inline src/package-linker.js]: Oh okay :(

File: src/util/fs.js (hunk 8 above)
Comment (BYK) [inline src/util/fs.js]: Gotcha. Didn't realize this was used further on.

File: src/package-linker.js (hunk 12 above)
Comment (BYK) [inline src/package-linker.js]: (y)

File: src/package-linker.js (hunk 2 above)
Comment (BYK) [inline src/package-linker.js]: Okay great. Can we put this in the code as a comment? Or may be have a function named `checkScopedPackage` or something to express the intent?

File: src/package-linker.js (hunk 5 above)
Comment (BYK) [inline src/package-linker.js]: Oh, right.

We can still have more descriptive variable names like `packageName` and `scopeName` instead of `basename` and `parentname` to make the intent clearer, right?

File: src/package-linker.js (hunk 6 above)
Comment (BYK) [inline src/package-linker.js]: Oh, now I understand. How about `fullPackageName` (assuming we also rename `basename` and `parentname` above to my suggestions: `packageName` and `scopeName`.

File: src/package-linker.js (hunk 7 above)
Comment (BYK) [inline src/package-linker.js]: Actually, if that's the intention I think there may be a more efficient way since `readLink` already does an `lstat` call internally. We can possibly do something like this:
```
const linkTarget = linkTargets.get(checkname);
let canDelete;
try {
    canDelete = linkTarget && (await fs.readLink(loc)) === linkTarget);
} catch (err) {
    canDelete = false;
}

**Comment by BYK** [comment]
We can merge once the CI builds pass.
