### PR TITLE
Fix: Always close the reporter before exiting

### LINKED ISSUE #4276: Cannot remove dependency from workspace with yarn
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Install a new dependency in a workspace, then try to uninstall it with `yarn remove`. You'll have the following output:

```
yarn remove v0.28.4
error No lockfile in this directory. Run `yarn install` to generate one.
```

It is however perfectly normal for a workspace to not have a lock file.

Removing from the root folder doesn't work either (which is expected).

**What is the expected behavior?**

There shouldn't be an error message. Like the normal case, yarn should:

- Remove the dependency from the workspace's `package.json`
- Link dependencies to trim the root folder's `yarn.lock`
- Delete the appropriate packages from the relevant `node_modules` folders

The RFC [briefly documents](https://github.com/yarnpkg/rfcs/blob/master/implemented/0000-workspaces-install-phase-1.md#running-yarn-install-in-workspaces-folders) the expected behaviour.

**Environment**

- yarn v0.28.4
- node v8.3.0
- Linux v4.9.44 (NixOS unstable distro)

### PR DESCRIPTION
**Pull request by arcanis**
**Summary**

Fix #4276

In some particular cases, the reporters are not correctly closed before Yarn exits. It makes the process hang, because the reporters are expected to periodically check for the RAM usage. This patch does two things:

- First the setInterval loop itself is `unref`, so that it will never prevent the process from exiting.
- More importantly, the reporter is now correctly closed when exiting in the two cases I've noticed.

**Test plan**

I don't think tests are required for this fix, since the reproduction steps are fairly narrow (the bug only occurred when using Yarn in an invalid way) and won't allow us to catch any other bug than this one.

### CODE REVIEW

**Comment by arcanis** [comment]
Hm Flow seems to recognize `setInterval` as returning a number, which is true for browsers but not for Node. I'll add a `$FlowFixMe`.

Re: tests, if you think it's better I'll add one.

**Comment by BYK** [comment]
If it is not too much trouble, a test would be great. If not, we'll... 🤷‍♂️

File: src/reporters/base-reporter.js [hunk 1]
```diff
@@ -152,6 +152,8 @@ export default class BaseReporter {
     this.peakMemoryInterval = setInterval(() => {
       this.checkPeakMemory();
     }, 1000);
+    // $FlowFixMe: Node's setInterval returns a Timeout, not a Number
+    this.peakMemoryInterval.unref();
```
Comment (BYK) [inline src/reporters/base-reporter.js]: I'm 👍 with this change but curious why `clearInterval(this.peakMemoryInterval);` in `close()` below isn't enough.

File: src/cli/index.js [hunk 2]
```diff
@@ -349,10 +349,10 @@ export function main({
     return errorReportLoc;
   }
 
-  const exit = exitCode => {
+  function exit(exitCode) {
```
Comment (BYK) [inline src/cli/index.js]: Why convert to "normal" functions from arrow functions?

Comment (arcanis) [reply src/cli/index.js]: Because otherwise `exit` is undefined at lines 178 & 195, since the assignment hasn't been executed yet.

Comment (BYK) [reply src/cli/index.js]: Ah, let's move this above then? Or add a comment if moving up is not possible?

**Comment by yacinehmito** [comment]
I don't think it fixes #4276, although this is a welcome PR.
The problem with the process hanging was just mentioned in passing. The real issue is that `yarn remove` in a workspace doesn't work.
