### PR TITLE
fix(audit) Report vulnerabilities in workspace package dependencies

### LINKED ISSUE #6625: yarn audit doesn't report vulnerable dependencies in a yarn workspace package
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

yarn audit doesn't report vulnerable dependencies in a yarn workspace package, even though the vulnerable package is listed in yarn.lock

**If the current behavior is a bug, please provide the steps to reproduce.**

make a repo using yarn workspaces, add minimatch@3.0.0 as a dependency in one of the workspaces, run `yarn install` and `yarn audit`

Here's an example repo that reproduces the issue:
https://github.com/gdamjan/yarn-audit-workspaces-example

**What is the expected behavior?**

yarn audit should report the vulnerability of a dependency listed in yarn.lock

**Please mention your node.js, yarn and operating system version.**

```
damjan docker $ node --version
v8.12.0
damjan docker $ yarn --version
1.12.1
damjan docker $ cat /etc/os-release 
NAME="Arch Linux"
```

### PR DESCRIPTION
**Pull request by rally25rs**
**Summary**

`yarn audit` was not reporting vulnerabilities for workspace package dependencies. This was due to only considering the actual `dependencies` and `devDependencies` listed in the root `package.json` file. Workspace packages were not being considered dependencies of the root workspace.

With this change, workspace packages will be added to the dependencies list that is sent to the npm audit API for auditing.

fixes #6625 

**Test plan**

Added unit test to `commands/audit`

### CODE REVIEW

File: src/cli/commands/audit.js [hunk 1]
```diff
@@ -229,12 +229,27 @@ export default class Audit {
...
+      const workspaceAggregatorName = resolver.workspaceLayout.virtualManifestName;
+      const workspaceManifest = resolver.workspaceLayout.workspaces[workspaceAggregatorName].manifest;
+
+      manifest.dependencies = Object.assign(manifest.dependencies || {}, workspaceManifest.dependencies);
+      manifest.devDependencies = Object.assign(manifest.devDependencies || {}, workspaceManifest.devDependencies);
+      manifest.optionalDependencies = Object.assign(
+        manifest.optionalDependencies || {},
+        workspaceManifest.optionalDependencies,
+      );
+    }
```
Comment (arcanis) [inline src/cli/commands/audit.js]: It's too bad we have to hardcode the copy :(
