### PR TITLE
fixes #2406 - don't create tag for preminor version change in master branch

### LINKED ISSUE #2406: Appveyor should not build for prerelease tags v0.xx.0-0
When 0.19-stable branch was cut, current master version became 0.20.0-0, indicating that whatever is now in master will be released to 0.20 release.

Appveyor built and uploaded artifacts to GitHub releases for version v0.19.0 (correct) and v0.20.0-0 (incorrect).

appveyor

### PR DESCRIPTION
**Pull request by bestander**
**Summary**

New tags trigger CI to make GitHub releases, there is no need for us to tag master branch with preminor version every time the branch is cut

### CODE REVIEW

File: scripts/release-branch.sh [hunk 1]
```diff
@@ -9,5 +9,7 @@ echo "$BRANCH"
 git checkout -b "$BRANCH"
 git push origin "$BRANCH" --follow-tags
 git checkout master
-yarn version --new-version preminor
-git push origin master --follow-tags
+yarn version --new-version preminor --no-git-tag-version
+NEW_VERSION=$(node -p -e "require('./package.json').version")
+git commit -a -m "$NEW_VERSION"
+git push origin master
```
Comment (Daniel15) [inline scripts/release-branch.sh]: Why did you remove the `--follow-tags` flag?

Comment (bestander) [inline scripts/release-branch.sh]: I stopped tagging master branch so that GitHub does not consider it as a new release.
So no reason to send new tags to origin

**Comment by bestander** [comment]
@Daniel15, ping, was my explanation satisfactory?

**Comment by Daniel15** [comment]
Looks good to me! :shipit:
