### PR TITLE
fix #5881: allow folder name of focused workspace to not match package name

### LINKED ISSUE #5881: --install focus gives error "targetHoistManifest missing"
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
```
$ yarn install --focus
yarn install v1.7.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
error An unexpected error occurred: "targetHoistManifest missing".
info If you think this is a bug, please open a bug report with the information provided in "XXX\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Unfortunately, this is in a private monorepo.

**What is the expected behavior?**

To install dependencies without errors.

**Please mention your node.js, yarn and operating system version.**

Windows 10

```
$ node --version
v8.9.1
$ yarn --version
1.7.0
```

### PR DESCRIPTION
**Pull request by bdwain**
**Summary**
fix #5881. Previously, the focused workspace logic determined the target workspace name by looking at the folder it was contained in. This was a mistake and it should have looked at the package.json name field.

I also moved the focus property to the config object rather than just as a flag for the install command. This made it easier to read the target name once rather than everywhere it was needed. 

**Test plan**

Added a unit test focusing on a scoped package. It also demonstrates that the focused workspace is not requested from npm, like mentioned in #5864.

### CODE REVIEW

File: src/config.js [hunk 1]
```diff
@@ -229,6 +234,17 @@ export default class Config {
...
+    // using focus in a workspace root is not allowed
+    if (this.focus && (!this.workspaceRootFolder || this.cwd === this.workspaceRootFolder)) {
+      throw new MessageError(this.reporter.lang('workspacesFocusRootCheck'));
+    }
+
+    if (this.focus) {
+      const focusedWorkspaceManifest = await this.findManifest(this.cwd, false);
+      invariant(focusedWorkspaceManifest, `missing manifest at ${this.cwd}`);
+      this.focusedWorkspaceName = focusedWorkspaceManifest.name;
+    }
```
Comment (arcanis) [inline src/config.js]: You should use `readRootManifest`

File: src/package-hoister.js [hunk 2]
```diff
@@ -666,9 +666,9 @@ export default class PackageHoister {
   }
 
   markShallowWorkspaceEntries() {
-    const targetWorkspace = path.basename(this.config.cwd);
```
Comment (arcanis) [inline src/package-hoister.js]: Why do you need the `focusedWorkspaceName` instead of just using `readRootManifest` here?

File: src/config.js (hunk 1 above)
Comment (bdwain) [reply src/config.js]: that hardcodes isRoot to true for normalizeManifest though. Isn't the root in this case the root of the whole project, not the individual workspace that is being focused on? 

Maybe it would make more sense to say readManfiest and pass false for isRoot? Or does it not make a difference for this?

File: src/package-hoister.js (hunk 2 above)
Comment (bdwain) [reply src/package-hoister.js]: I suppose we could read the manifest everywhere we need the focused package's name. It seemed simpler and faster to do it once up front because otherwise we'd need to do it like 4-5 times.

**Comment by bdwain** [comment]
@arcanis the test failures seem to be occurring in master as well. I don't think they are related to my PR.

 FAIL  __tests__/commands/info.js
  ✓ without arguments and in directory containing a valid package file (465ms)
  ✓ with first argument "." and in directory containing a valid package file
  ✓ with one argument shows info about the package with specified name
  ✓ with one argument does not contain readme field (1ms)
  ✓ with two arguments and second argument "readme" shows readme string
  ✓ with two arguments and second argument "version" shows `latest` version
  ✓ with two arguments and second argument as a simple field
  ✓ with two arguments and second argument as "."-separated field path
  ✓ with two arguments and second argument as a non-existing field
  ✓ with two arguments and second argument path containing non-existing field (1ms)
  ✕ reports error on invalid package names (218ms)
  ✓ reports error with too many arguments

  ● reports error on invalid package names

    https://registry.yarnpkg.com/YARN.invalid.package.name.YARN: Not found

**Comment by bdwain** [comment]
@arcanis FYI ill be out of town the next 4 days but can address any comments you have when i get back.

**Comment by bdwain** [comment]
fixed the merge conflicts

**Comment by arcanis** [comment]
LGTM, thanks!

**Comment by bdwain** [comment]
thanks!
