### PR TITLE
fix(cli-create): fix scoped creation

### LINKED ISSUE #6233: yarn create @scope doesnt work as expected
**What is the current behavior?** it is also steps to reproduce

```
## create doesnt recognise scope without "/"
☯ yarn create @scope
yarn create v1.9.4
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/create-: Not found".

## create recognise scope with "/", but adds unnecessary "-" in the end
☯ yarn create @scope/
yarn create v1.9.4
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@scope%2fcreate-: Not found".
```

**What is the expected behavior?** npm's one is an expected behaviour

```
☯ npm init @scope
npm ERR! code E404
npm ERR! 404 Not Found: @scope/create@latest
```

**Please mention your node.js, yarn and operating system version.**

```
darwin 17.7.0
Node.js v8.11.3
yarn 1.9.4
```

### PR DESCRIPTION
**Pull request by iamstarkov**
This one works as it should:
yarn create @scope/name => @scope/create-name

There were problems when name was omitted:

Before:
yarn create @scope => create-
yarn create @scope/ => @scope/create-

After:
yarn create @scope => @scope/create
yarn create @scope/ => @scope/create

Fixes #6233

**Summary**

it Is not substantial feature request.

Existing behaviour is a bit odd and not aligned with npm. This PR aims to fix it.

**Test plan**

```
~/projects/oss/yarn fix/scoped-create
☯ ./bin/yarn create name
{ packageName: 'create-name',
  packageDir: '',
  commandName: 'create-name' }

~/projects/oss/yarn fix/scoped-create
☯ ./bin/yarn create @scope/name
{ packageName: '@scope/create-name',
  packageDir: '@scope',
  commandName: 'create-name' }

~/projects/oss/yarn fix/scoped-create
☯ ./bin/yarn create @scope/
{ packageName: '@scope/create',
  packageDir: '@scope',
  commandName: 'create' }

~/projects/oss/yarn fix/scoped-create
☯ ./bin/yarn create @scope
{ packageName: '@scope/create',
  packageDir: '@scope',
  commandName: 'create' }
```

Disclaimer:
* I didnt manage to adjust existing RegExps to fix bug: whenever I fixed one use case another one was breaking.
* Due to difficulties with RegExps I streamlined package's scope and name extraction with few helpers.
* ~Couldn't find a place to add test for helper, so I inlined working test assertions.~
* Also I couldn't find documentation in a repository, thus couldn't update it and sadly contribution guide doesnt describe how to update docs.

If tests or documentation are required to be added/updated in the same PR please let me know how to do it.

### CODE REVIEW

**Comment by iamstarkov** [comment]
`ci/circleci: test-pkg-tests-linux-node10` failed I believe due to some network glitch:

```
error https://registry.yarnpkg.com/ws/-/ws-4.0.0.tgz: Integrity check failed for "ws" (computed integrity doesn't match our records, got "sha512-o0lyLXKExgoAAX5h3jesLVi7vSGrwFJGpy+Zc+/gil3UWQz2jnGkhD84rpkIJmYE3DIsOnuoojk2CqO19D653g==")
```

**Comment by iamstarkov** [comment]
@arcanis @torifat, please take a look when you have time

File: src/cli/commands/create.js [hunk 1]
```diff
@@ -16,17 +16,50 @@ export function hasWrapper(commander: Object, args: Array<string>): boolean {
...
+ * parseBuilderName('@scope/name').packageName === '@scope/create-name'
+ *
+ * ## not adding "-" if name is empty
+ * parseBuilderName('@scope/').packageName === '@scope/create'
+ * parseBuilderName('@scope').packageName === '@scope/create'
+ *
+ * ## edge cases
+ * parseBuilderName('@/name').packageName === 'create-name'
+ * parseBuilderName('/name').packageName === 'create-name'
+ * parseBuilderName('@/').packageName === 'create'
```
Comment (arcanis) [inline src/cli/commands/create.js]: I'd prefer if you could put this in a file called `__tests__/commands/create.js` (you can just export the `parseBuilderName` symbol and require the file), so that they are actually ran. Otherwise the comment can just be removed, since it will never be run.

File: src/cli/commands/create.js [hunk 2]
```diff
@@ -16,17 +16,50 @@ export function hasWrapper(commander: Object, args: Array<string>): boolean {
...
+ */
+const parseBuilderName = str => {
+  const parts = str.split('/');
+  if (parts.length === 1 && !str.includes('@')) {
```
Comment (arcanis) [inline src/cli/commands/create.js]: `str.charAt(0) === '@'` would be more correct, I think.

File: src/cli/commands/create.js [hunk 3]
```diff
@@ -16,17 +16,50 @@ export function hasWrapper(commander: Object, args: Array<string>): boolean {
...
+ * parseBuilderName('@scope/').packageName === '@scope/create'
+ * parseBuilderName('@scope').packageName === '@scope/create'
+ *
+ * ## edge cases
+ * parseBuilderName('@/name').packageName === 'create-name'
+ * parseBuilderName('/name').packageName === 'create-name'
+ * parseBuilderName('@/').packageName === 'create'
+ */
+const parseBuilderName = str => {
+  const parts = str.split('/');
```
Comment (arcanis) [inline src/cli/commands/create.js]: It should reject as invalid if there's more than two parts, or if the first part doesn't start with a '@'

File: src/cli/commands/create.js (hunk 1 above)
Comment (iamstarkov) [reply src/cli/commands/create.js]: okay, will do

File: src/cli/commands/create.js (hunk 2 above)
Comment (iamstarkov) [reply src/cli/commands/create.js]: right

File: src/cli/commands/create.js (hunk 3 above)
Comment (iamstarkov) [reply src/cli/commands/create.js]: good idea

File: src/cli/commands/create.js (hunk 1 above)
Comment (iamstarkov) [reply src/cli/commands/create.js]: added tests

File: src/cli/commands/create.js (hunk 2 above)
Comment (iamstarkov) [reply src/cli/commands/create.js]: fixed

File: src/cli/commands/create.js (hunk 3 above)
Comment (iamstarkov) [reply src/cli/commands/create.js]: I changed `parseBuilderName` to `parsePackageName` and it throws error if first character is `.` or `/`. It also throws if scope equals `@`. 

About throwing id there are more than 2 parts: and i want yarn to be robust so I just put that extra part into `path` field of `pkgNameObject`¹ and ignore it in rest of `create` command.

\[1]:
```js
'@scope/name/path/to/file.js' => pkgNameObject {
  fullName: '@scope/name',
  name: 'name',
  scope: '@scope',
  path: 'path/to/file.js',
  full: '@scope/name/path/to/file.js',
}
```

**Comment by iamstarkov** [comment]
@aracarie updated PR with respect to requested changes

**Comment by iamstarkov** [comment]
@arcanis had any chance to review it?

**Comment by arcanis** [comment]
Looks great, thanks! 👍
