### PR TITLE
Fix: 'yarn --flat' unbound transitive deps shouldn't conflict with top level deps

### LINKED ISSUE #3780: yarn --flat sees a version conflict where there is none
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`yarn --flat` sees a version conflict where there is none (in >=0.27.0).

If I have package A that requires 'left-pad@>=1.0.1" and package B that requires both A and "left-pad@1.1.1", and install package B with `yarn --flat` there is a conflict.

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/mxmul/yarn_flat_regression

**What is the expected behavior?**
yarn would choose the one version that satisfies the version constraints (1.1.1)

**Please mention your node.js, yarn and operating system version.**
`yarn@0.27.1` `node@5.11.0` `ubuntu@10.04`

### PR DESCRIPTION
**Pull request by mxmul**
**Summary**

Fixes #3780, and makes the failing test from #3779 passing.

As a final step of package resolution, for each dependency we check whether any version satisfies all resolved version ranges. 

**Test plan**

Fixes an existing (failing) test: "unbound transitive dependencies should not conflict with top level dependency"

### CODE REVIEW

File: src/package-resolver.js [hunk 1]
```diff
@@ -530,10 +530,48 @@ export default class PackageResolver {
...
 
+  // for a given package, see if a single manifest can satisfy all ranges
+  optimizeResolutions(name: string) {
+    const patterns: Array<string> = this.patternsByPackage[name] || [];
+
+    // don't optimize things that already have a lockfile entry:
+    // https://github.com/yarnpkg/yarn/issues/79
+    const anyLocked = patterns.some(pattern => this.lockfile.getLocked(pattern));
+    if (anyLocked) {
+      return;
```
Comment (BYK) [inline src/package-resolver.js]: Why not exclude only the locked ones and still optimize the rest?

File: src/package-resolver.js [hunk 2]
```diff
@@ -530,10 +530,48 @@ export default class PackageResolver {
...
+    }
+
+    const manifestByVersion: Map<string, Manifest> = new Map();
```
Comment (BYK) [inline src/package-resolver.js]: Looks like you just need `this.getAllInfoForPackageName(name)` above instead.

File: src/package-resolver.js [hunk 3]
```diff
@@ -530,10 +530,48 @@ export default class PackageResolver {
...
+    patterns.forEach(p => {
+      const manifest = this.patterns[p];
+      manifestByVersion.set(manifest.version, manifest);
+    });
+
+    // reverse sort, so we'll find the maximum satisfying version
+    const availableVersions = [...manifestByVersion.keys()];
```
Comment (BYK) [inline src/package-resolver.js]: Why not `Array.from(manifestByVersion.keys())`. That said spread looks is faster in latest V8 versions so NVM: https://jsperf.com/set-iterator-vs-foreach/4

File: src/package-resolver.js [hunk 4]
```diff
@@ -530,10 +530,48 @@ export default class PackageResolver {
...
+    availableVersions.sort(semver.rcompare);
+
+    const requiredRanges = patterns.map(p => normalizePattern(p).range);
```
Comment (BYK) [inline src/package-resolver.js]: I think you can leverage some semver secrets as follows:
```js
const fullRange = patterns.map(pattern => normalizePattern(p).range).join(' ');
const oneRingToRuleThemAll = semver.maxSatisfying([...manifestByVersion.keys()], fullRange);
if (oneRingToRuleThemAll) {
    this.collapseAllVersionsOfPackage(name, oneRingToRuleThemAll);
}
```

This should be more efficient than what the code below does. Also, the code below continuously resolves to new versions as it goes on since `return` in a `forEach` loop doesn't terminate the loop at all.

Comment (mxmul) [reply src/package-resolver.js]: Yep, that's a nice optimization.

File: src/package-resolver.js (hunk 1 above)
Comment (mxmul) [reply src/package-resolver.js]: So I've made this change, but it causes some workspace related tests to fail ("install should link workspaces that refer each other", "install should not link workspaces that refer not compatible version of another workspace"). I don't quite understand why these are failing, but I've just disabled the optimization wherever `remote.type === "workspace"`. Open to other suggestions.
