### PR TITLE
fix(resolution): Prevent duplicate patterns in PackageResolver patternsByPackage array

### LINKED ISSUE #5676: Upgrade command fails with Yarn 1.5.1/1.6.0
## Current Outcome

At my pacage.json, the upgrade command fails with Yarn 1.5.1/1.6.0. In case of 1.3.2, not so.
The error log is different every time, but it always fails.
\* The install command has no problem.

[ package.json ]
```{
  "main": "gulpfile.js",
  "license": "Unlicense",
  "devDependencies": {
    "@types/autosize": "3.0.6",
    "@types/bootstrap": "3.3.38",
    "@types/clipboard": "2.0.0",
    "@types/eonasdan-bootstrap-datetimepicker": "4.17.26",
    "@types/jquery": "3.3.1",
    "@types/jquery.blockui": "0.0.28",
    "@types/purl": "2.3.30",
    "del": "3.0.0",
    "fancy-log": "1.3.2",
    "gulp": "^4.0.0",
    "gulp-autoprefixer": "5.0.0",
    "gulp-clean-css": "3.9.3",
    "gulp-csscomb": "3.0.8",
    "gulp-debug": "3.2.0",
    "gulp-filter": "5.1.0",
    "gulp-htmlmin": "4.0.0",
    "gulp-if": "2.0.2",
    "gulp-imagemin": "4.1.0",
    "gulp-notify": "3.2.0",
    "gulp-plumber": "1.2.0",
    "gulp-rename": "1.2.2",
    "gulp-sass": "4.0.1",
    "gulp-token-replace": "1.1.2",
    "gulp-typedoc": "2.2.0",
    "gulp-typescript": "4.0.2",
    "gulp-uglify": "3.0.0",
    "gulp-zip": "4.1.0",
    "lazypipe": "1.0.1",
    "main-bower-files": "2.13.1",
    "merge2": "1.2.1",
    "object-merge": "2.5.1",
    "path-exists": "3.0.0",
    "typedoc": "0.11.1",
    "typescript": "2.8.1",
    "uglify-save-license": "0.4.1"
  },
  "dependencies": {
    "@allmarkedup/purl": "allmarkedup/purl#2.3.2",
    "@bower_components/add-to-homescreen": "cubiq/add-to-homescreen#3.2.3",
    "@bower_components/autosize": "jackmoore/autosize#4.0.1",
    "@bower_components/blockUI": "malsup/blockui#*",
    "@bower_components/bootstrap": "twbs/bootstrap#3.3.7",
    "@bower_components/bootstrap-select": "silviomoreto/bootstrap-select#1.12.4",
    "@bower_components/bootstrap-show-password": "wenzhixin/bootstrap-show-password#1.1.2",
    "@bower_components/clipboard": "zenorocha/clipboard.js#2.0.0",
    "@bower_components/eonasdan-bootstrap-datetimepicker": "Eonasdan/bootstrap-datetimepicker#4.17.47",
    "@bower_components/font-awesome": "FortAwesome/Font-Awesome#5.0.10",
    "@bower_components/instantclick": "dieulot/instantclick#3.1.0",
    "@bower_components/jquery": "jquery/jquery-dist#3.3.1",
    "@bower_components/jquery-i18n-properties": "jquery-i18n-properties/jquery-i18n-properties#1.2.7",
    "@bower_components/jquery-toast-plugin": "kamranahmedse/jquery-toast-plugin#1.3.2",
    "@bower_components/moment": "moment/moment#2.22.1",
    "@bower_components/moment-timezone": "moment/moment-timezone#0.5.14",
    "@bower_components/pretty-checkbox": "lokesh-coder/pretty-checkbox#3.0.3",
    "@bower_components/purl": "allmarkedup/purl#2.3.2",
    "Font-Awesome": "FortAwesome/Font-Awesome#5.0.10",
    "add-to-homescreen": "cubiq/add-to-homescreen#3.2.3",
    "autosize": "jackmoore/autosize#4.0.1",
    "blockui": "malsup/blockui#*",
    "bootstrap": "twbs/bootstrap#3.3.7",
    "bootstrap-select": "silviomoreto/bootstrap-select#1.12.4",
    "bootstrap-show-password": "wenzhixin/bootstrap-show-password#1.1.2",
    "clipboard": "zenorocha/clipboard.js#2.0.0",
    "eonasdan-bootstrap-datetimepicker": "Eonasdan/bootstrap-datetimepicker#4.17.47",
    "instantclick": "dieulot/instantclick#3.1.0",
    "jquery": "jquery/jquery-dist#3.3.1",
    "jquery-i18n-properties": "jquery-i18n-properties/jquery-i18n-properties#1.2.7",
    "jquery-toast-plugin": "kamranahmedse/jquery-toast-plugin#1.3.2",
    "moment": "moment/moment#2.22.1",
    "moment-timezone": "moment/moment-timezone#0.5.14",
    "pretty-checkbox": "lokesh-coder/pretty-checkbox#3.0.3"
  },
  "engines": {
    "yarn": ">= 1.0.0"
  },
  "scripts": {
    "postinstall": "node -e \"try { require('fs').symlinkSync(require('path').resolve('node_modules/@bower_components'), 'bower_components', 'junction') } catch (e) { }\""
  }
}
```

## Environment ##

- **Node.js Version**: 8.11.1
- **Yarn**: 1.5.1/1.6.0
- **Operating System**: Windows 10/Amazon Linux(release 2017.09)

### PR DESCRIPTION
**Pull request by rally25rs**
**Summary**

Fixes #5676. Previously duplicate patterns would be inserted into this array, causing unnecessary looping and manifest reading of the same patterns. It also caused a bug when duplicate patterns were marked as
peerDeps. We now prevent these duplicate entries.

**Test plan**

Added test to `package-resolver` tests.

### CODE REVIEW

File: __tests__/package-resolver.js [hunk 1]
```diff
@@ -16,25 +16,34 @@ const path = require('path');
...
+  const reporter = new reporters.NoopReporter({});
 
-    const loc = await makeTemp();
-    const cacheFolder = path.join(loc, 'cache');
+  const loc = await makeTemp();
+  const cacheFolder = path.join(loc, 'cache');
 
-    const config = await Config.create(
+  const config = await Config.create(
+    Object.assign(
```
Comment (BYK) [inline __tests__/package-resolver.js]: nit: prefer object spread notation:
```js
{
  cwd: loc,
  offline: false,
  cacheFolder,
  ...configOptions,
}
```

File: src/package-resolver.js [hunk 2]
```diff
@@ -352,7 +353,9 @@ export default class PackageResolver {
     this.patterns[pattern] = info;
 
     const byName = (this.patternsByPackage[info.name] = this.patternsByPackage[info.name] || []);
-    byName.push(pattern);
+    if (byName.indexOf(pattern) === -1) {
```
Comment (BYK) [inline src/package-resolver.js]: I feel like it would be a lot more efficient to use a `Set` here since the ordering doesn't seem to be important?

I guess that'd be a refactor we need to do in a follow up?

Comment (rally25rs) [reply src/package-resolver.js]: In that specific function yes, `Set` would be better, but the rest of the functions use `Array.map` and `Array.filter` on that object, which are not available on `Set` so we would have to convert Set to Array all over the place: `[...patterns].map(` which is probably worse overall for memory and performance usage. (expanding the set to an array frequently, vs infrequent `.indexOf` calls on small arrays)

**Comment by BYK** [comment]
@rally25rs submitted #5687 to fix the failures on master.
