### PR TITLE
Fix: prevent Git from showing a password prompt

### LINKED ISSUE #764: yarn install hangs during "Fetching packages..."
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

yarn install hangs at fetching packages and does not provide any further information as to the cause.

**If the current behavior is a bug, please provide the steps to reproduce.**

With the following [package.json](https://gist.github.com/indieisaconcept/875c30f41eb0683e17628c6b6f7b5ae1) run the below

```
> yarn cache clean & yarn install
```

**What is the expected behavior?**

Installation should succeed.

**Please mention your node.js, yarn and operating system version.**
- yarn@v0.15.1
- node@v4.4.6
- osx@10.10.5

### PR DESCRIPTION
**Pull request by BYK**
**Summary**

Fixes #764.

Turns out when fetching packages from remote sources via Git,
it may ask for a username or password and get stuck there since
we run it in the background. This patch passes the following env
variables to disable any prompts:

1. `$GIT_ASKPASS=""`
   This is the command Git runs to get username and pass. Setting
   it to an empty string disables it and git exits with an error.
2. `$GIT_TERMINAL_PROMPT=0`
    This is new in Git 2.3 and it prevents git from even trying to
    ask for a password. Surpasses `$GIT_ASKPASS` above.
3. `$GIT_SSH_COMMAND="ssh -oBatchMode=yes"`
    This is also new in Git 2.3 and it makes git make the call to
    ssh via this command. `BatchMode=yes` option tells ssh to not
    do anything interactive (because batch/script mode) like
    password prompts in case publickey auth fails etc.

**Test plan**

Do `yarn add git+https://github.com/Napsty/privrepo.git#1.0.2`. `yarn`
hangs before this patch and fails with a "Refusing to download" error
after the patch.

### CODE REVIEW

**Comment by BYK** [comment]
Three notes about this PR:

1. Not sure if this covers the entire #764 but I think it covers a significant portion
2. The error messages are not really descriptive, almost deceptive. Planning to address that in a follow-up but I can change them here if requested.
3. I'm not very happy about the manual test plan. Any directions to automate this without `git` and network dependency are welcome.

File: src/util/git.js [hunk 1]
```diff
@@ -87,6 +90,10 @@ export default class Git {
     };
   }
 
+  static git(args: Array<string>, opts?: child_process$spawnOpts = {}): Promise<string> {
```
Comment (BYK) [inline src/util/git.js]: May be I should rename this to `spawn`?

Comment (cpojer) [inline src/util/git.js]: Yes please. "Git.git" is weird :D

**Comment by kirs** [comment]
❤️

**Comment by kisamoto** [comment]
If I understand this correctly this disables the use of passphrase protected SSH keys as now there is no opportunity to enter the passphrase for a private SSH key or password for HTTPS authentication?

**Comment by BYK** [comment]
Sounds about right. Both of those scenarios can be addressed via SSH agent and Git Credentials Manager respectively though.

**Comment by bestander** [comment]
@BYK, this seems to have broken ability to use git dependencies behind a proxy, I raised an internal task with details t19705486

**Comment by BYK** [comment]
@bestander created #3742 for public tracker.
