### PR TITLE
Color fix

### LINKED ISSUE #2724: Yarn help changes text color in powershell
bug in yarn 0.20.3 (installed through chocolatey)

**What is the current behavior?**
when running [yarn help] the help is displayed but the textcolor is changed and left to a dark color, so nothing can be read afterwards.

**If the current behavior is a bug, please provide the steps to reproduce.**
Just run yarn help in powershell (I also have poshgit installed in case that makes a difference)

**What is the expected behavior?**
The text color should be reset to whatever it was before yarn help was called

**Please mention your node.js, yarn and operating system version.**
Node 7.5.0
Yarn 0.20.3

As a work around I can run `[Console]::ResetColor()` in powershell to reset the text

### PR DESCRIPTION
**Pull request by ViceIce**
**Summary**
This PR resets the console style after using bold, because the new windows console does not support the ansi escape codes ^[[21m and ^[[22m. This would fix  #2724 

**Test plan**

Only one test case had to be fixed. :)

### CODE REVIEW

**Comment by ViceIce** [comment]
Test timeouts 😞

**Comment by rally25rs** [comment]
I was going to merge this PR, but was a little unclear on the "Fix prettier on windows." commit.
Seems like a large diff. Is this change actually related to fixing the color output on Win?

**Comment by ViceIce** [comment]
It's not relate to the Bug, but the old prettier script was not working on windows. Command too long error. I found this solution on Facebook flow project.

https://github.com/facebook/react/issues/9500

**Comment by ViceIce** [comment]
Removed prettier commit and opened another PR #3635

File: src/reporters/console/console-reporter.js [hunk 1]
```diff
@@ -27,6 +27,12 @@ const tty = require('tty');
 type Row = Array<string>;
 type InquirerResponses<K, T> = {[key: K]: Array<T>};
 
+// fixes bold on windows
+// $FlowFixMe TERM is not a string?
+if (process.platform === 'win32' && !/^xterm/i.test(process.env.TERM)) {
```
Comment (torifat) [inline src/reporters/console/console-reporter.js]: Does `flow` still complain if you do
```js
if (process.platform === 'win32' && process.env.TERM && !/^xterm/i.test(process.env.TERM)) {
```

And, how about using `startswith` instead of the regex?

Comment (ViceIce) [inline src/reporters/console/console-reporter.js]: I can test it, this was copied from /chalk/chalk/blob/v1.1.1/index.js#L8

startsWith is not case insensitive.

Comment (torifat) [inline src/reporters/console/console-reporter.js]: Yeah, I missed the `i`.

It's better if we can get rid of `$FlowFixMe`.

Comment (ViceIce) [inline src/reporters/console/console-reporter.js]: Done 😄

File: src/reporters/console/console-reporter.js [hunk 2]
```diff
@@ -27,6 +27,11 @@ const tty = require('tty');
 type Row = Array<string>;
 type InquirerResponses<K, T> = {[key: K]: Array<T>};
 
+// fixes bold on windows
+if (process.platform === 'win32' && process.env.TERM && !/^xterm/i.test(process.env.TERM)) {
+  chalk.styles.bold.close += '\u001b[m';
```
Comment (Daniel15) [inline src/reporters/console/console-reporter.js]: I wonder if this should be submitted upstream to the `chalk` project?

Comment (ViceIce) [inline src/reporters/console/console-reporter.js]: See chalk/chalk#145

Comment (Daniel15) [inline src/reporters/console/console-reporter.js]: Cool, sounds like we can remove this hack in the future, then.
