### PR TITLE
switched to tar-fs from node-tar to unpack tars

### LINKED ISSUE #961: Yarn should normalize permissions when untarring packages.
**Do you want to request a _feature_ or report a _bug_?**
This is a bug report.

**What is the current behavior?**
Yarn keeps the permissions of the archives is untars intact, while npm normalizes them. This means some npm packages cannot be installed using yarn.

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a folder with the following package.json:

```
{
  "name": "test-case",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@types/history": "2.0.38"
  }
}
```

Run `yarn` using a version of yarn with support for scoped modules (e.g., `master`).

**Note:** This is **not** an issue with scoped modules in general. Other scoped modules work on `master`.

**What is the expected behavior?**
The operation should succeed (as it does with `npm install`), and the the permissions should be as follows:

```
total 40
-rw-r--r--   1 mcbr   611B Oct  3 08:23 README.md
-rw-r--r--   1 mcbr   5.7K Oct  3 08:23 index.d.ts
drwxr-xr-x  11 mcbr   374B Oct 12 22:07 lib
-rw-r--r--   1 mcbr   2.1K Oct 12 22:07 package.json
-rw-r--r--   1 mcbr   1.1K Oct  3 08:23 types-metadata.json

./node_modules/@types/history/lib:
total 72
-rw-r--r--  1 mcbr   624B Oct  3 08:23 DOMUtils.d.ts
-rw-r--r--  1 mcbr   143B Oct  3 08:23 actions.d.ts
-rw-r--r--  1 mcbr   133B Oct  3 08:23 createBrowserHistory.d.ts
-rw-r--r--  1 mcbr   130B Oct  3 08:23 createHashHistory.d.ts
-rw-r--r--  1 mcbr   203B Oct  3 08:23 createLocation.d.ts
-rw-r--r--  1 mcbr   134B Oct  3 08:23 createMemoryHistory.d.ts
-rw-r--r--  1 mcbr   135B Oct  3 08:23 useBasename.d.ts
-rw-r--r--  1 mcbr   182B Oct  3 08:23 useBeforeUnload.d.ts
-rw-r--r--  1 mcbr   165B Oct  3 08:23 useQueries.d.ts
```

I don't think it's required that the date for "lib" be set to the current date. `npm install` just does this for some reason.

Instead, the operation does not succeed:

```
yarn install v0.15.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error https://registry.npmjs.org/@types/history/-/history-2.0.38.tgz: EACCES: permission denied, open '/Users/mcbr/.yarn-cache/npm-@types/history-2.0.38/lib/DOMUtils.d.ts'
    at Error (native)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Note: untarring `https://registry.npmjs.org/@types/history/-/history-2.0.38.tgz` results in:

```
total 40
-rw-r--r--   1 mcbr   611B Oct  3 08:23 README.md
-rw-r--r--   1 mcbr   5.7K Oct  3 08:23 index.d.ts
drw-r--r--  11 mcbr   374B Oct  3 08:23 lib
-rw-r--r--   1 mcbr   603B Oct  3 08:23 package.json
-rw-r--r--   1 mcbr   1.1K Oct  3 08:23 types-metadata.json

./history/lib:
```

Note that `lib` does not have executable ("cd") permissions. While we could ask DefinitelyTyped (`@types/history`) to fix their permissions, I'm reporting the issue here in case you with to improve compatibility with npm packages, especially in case there are other strange packages.

**Please mention your node.js, yarn and operating system version.**
- Node v6.6.0
- Yarn `ee07644ed9080a22ca9742c9383100b8f03221a3` (`master`)
- macOS Sierra

### PR DESCRIPTION
**Pull request by bestander**
**Summary**

A mitigation for https://github.com/yarnpkg/yarn/issues/2629
Also fixes #961

Based on a few ad-hoc tests (//gitlab.com/linagora/petals-cockpit.git#075bac4c54fee466568c000c7ffe8025f593e212) tar-fs seems to make less IO thus is more stable and a bit faster.

I noticed that we never tested git repos that support archive.
Did they ever work?

----
Test data:

1. Using offline-mirror (no download), on my MBPro 13", clean cache and using `node-tar` to unzip files.
Concurrency 12 - fails
Concurrency 8 - 18 seconds
Concurrency 4 - 18 seconds
Concurrency 2 - 21 seconds

2. Using offline-mirror (no download), on my MBPro 13", clean cache and using `tar-fs` to unzip files.
Concurrency 12 - 15 seconds
Concurrency 8 - 15 seconds
Concurrency 4 - 17 seconds
Concurrency 2 - 18 seconds

3. Downloading packages from internet, on my MBPro 13", clean cache and using `tar-fs` to unzip files.
Concurrency 12 - failed once
Concurrency 8 - 21 seconds
Concurrency 4 - 23 seconds
Concurrency 2 - 34 seconds

**Test plan**
- All changes are covered with tests (verified every change)
- Could not properly test git archives (see https://github.com/yarnpkg/yarn/issues/2831) but did an ad-hoc test via `yarn add ssh://git@bitbucket.org/bestander/test-repo.git` and made sure that archive was accessed and installed.

### CODE REVIEW

**Comment by bestander** [comment]
Don't merge, still need to remove node-tar from 2 more places.

**Comment by bestander** [comment]
Also fixes #961

**Comment by bestander** [comment]
@arcanis, could you review this please?

File: __tests__/commands/pack.js [hunk 1]
```diff
@@ -83,8 +83,12 @@ export async function getFilesFromArchive(source, destination): Promise<Array<st
   const unzip = new Promise((resolve, reject) => {
     fs2.createReadStream(source)
       .pipe(new zlib.Gunzip())
-      .pipe(tar.Extract({path: destination, strip: 1}))
-      .on('end', resolve)
+      .pipe(tarFs.extract(destination, {
+        strip: 1,
+        dmode: parseInt(555, 8), // all dirs should be readable
+        fmode: parseInt(444, 8), // all files should be readable
```
Comment (arcanis) [inline __tests__/commands/pack.js]: `0o555` and `0o444` ?

File: src/fetchers/git-fetcher.js [hunk 2]
```diff
@@ -34,15 +34,18 @@ export default class GitFetcher extends BaseFetcher {
     }
 
     return new Promise((resolve, reject) => {
-      const untarStream = tar.Extract({path: this.dest});
+      const untarStream = tarFs.extract(this.dest, {
+        dmode: parseInt(555, 8), // all dirs should be readable
+        fmode: parseInt(444, 8), // all files should be readable
```
Comment (arcanis) [inline src/fetchers/git-fetcher.js]: Same

File: src/fetchers/tarball-fetcher.js [hunk 3]
```diff
@@ -77,7 +77,11 @@ export default class TarballFetcher extends BaseFetcher {
   } {
     const validateStream = new crypto.HashStream();
     const extractorStream = new UnpackStream();
-    const untarStream = tar.Extract({path: this.dest, strip: 1});
+    const untarStream = tarFs.extract(this.dest, {
+      strip: 1,
+      dmode: parseInt(555, 8), // all dirs should be readable
+      fmode: parseInt(444, 8), // all files should be readable
```
Comment (arcanis) [inline src/fetchers/tarball-fetcher.js]: Same - shouldn't the unpack routine be splitted into an helper, since it used in a few places?

File: src/util/git.js [hunk 4]
```diff
@@ -279,13 +287,21 @@ export default class Git {
...
-          parser.on('end', done);
-
-          parser.on('data', (entry: Buffer) => {
-            update(entry.toString());
+          parser.on('finish', done);
+
+          parser.on('entry', (header, stream, next) => {
+            let string = '';
+            stream.on('data', (buffer) => {
+              string += buffer.toString();
```
Comment (arcanis) [inline src/util/git.js]: iirc, this pattern might break when the buffer contains part of an unicode character but not the others. It might be better to concat the buffers together (possibly by storing them in a list and then concatenating everything at once with `Buffer.concat`) rather than concatenating strings.

File: src/util/git.js [hunk 5]
```diff
@@ -205,9 +206,12 @@ export default class Git {
   async _cloneViaRemoteArchive(dest: string): Promise<void> {
     await child.spawn('git', ['archive', `--remote=${this.url}`, this.ref], {
       process(proc, update, reject, done) {
-        const extractor = tar.Extract({path: dest});
+        const extractor = tarFs.extract(dest, {
+          dmode: parseInt(555, 8), // all dirs should be readable
+          fmode: parseInt(444, 8), // all files should be readable
```
Comment (arcanis) [inline src/util/git.js]: Same

File: src/util/git.js [hunk 6]
```diff
@@ -219,9 +223,13 @@ export default class Git {
     await child.spawn('git', ['archive', this.hash], {
       cwd: this.cwd,
       process(proc, resolve, reject, done) {
-        const extractor = tar.Extract({path: dest});
+        const extractor = tarFs.extract(dest, {
+          dmode: parseInt(555, 8), // all dirs should be readable
+          fmode: parseInt(444, 8), // all files should be readable
```
Comment (arcanis) [inline src/util/git.js]: [Ditto](http://cdn.bulbagarden.net/upload/3/36/132Ditto.png)

File: src/fetchers/tarball-fetcher.js (hunk 3 above)
Comment (bestander) [inline src/fetchers/tarball-fetcher.js]: Sometimes we need to strip first folder, sometimes not.
And moving dmode,fbmode into a separate function looks like an overkill

File: src/util/git.js (hunk 4 above)
Comment (bestander) [inline src/util/git.js]: Oh, smart!
I'll do that

File: __tests__/commands/pack.js (hunk 1 above)
Comment (bestander) [inline __tests__/commands/pack.js]: 👍

File: src/fetchers/tarball-fetcher.js (hunk 3 above)
Comment (arcanis) [inline src/fetchers/tarball-fetcher.js]: 👍

**Comment by bestander** [comment]
ping @arcanis, ready for another round

File: src/util/git.js [hunk 7]
```diff
@@ -293,12 +295,15 @@ export default class Git {
...
+            let fileContent = '';
+
             stream.on('data', (buffer) => {
-              string += buffer.toString();
+              fileContent += decoder.write(buffer);
             });
             stream.on('end', () => {
-              update(string);
+              fileContent += decoder.end();
+              update(fileContent);
```
Comment (arcanis) [inline src/util/git.js]: Since it isn't really used anymore, maybe `fileContent` should be removed completely, using `update(decoded.end())` instead

File: __tests__/commands/pack.js (hunk 1 above)
Comment (arcanis) [inline __tests__/commands/pack.js]: Just noticed - you forgot this instance :)

File: src/util/git.js (hunk 7 above)
Comment (bestander) [inline src/util/git.js]: decoded.end() won't return a full string.
It would just return remaining bytes if there were any.
So I needed to accumulate them in a string

Comment (arcanis) [inline src/util/git.js]: Oh I see, my bad ! I initially thought the decoder was holding the whole buffer 👍

**Comment by victornoel** [comment]
@bestander it could make sense to also use `gunzip-maybe` (like `tar-fs`, it is by @mafintosh) instead of reimplementing it in `utils/stream`.
