### PR TITLE
fix: Removes usage of deprecated Buffer constructor. (#5477)

### LINKED ISSUE #5477: Replace use of deprecated/unsafe new Buffer constructor
**What is the current behavior?**

`yarn` uses deprecated `new Buffer()` constructor and causes deprecation warnings when run with `NODE_PENDING_DEPRECATION=1`.

```
$ ag '\bBuffer\('
src/registries/npm-registry.js
340:        const pw = new Buffer(String(password), 'base64').toString();
341:        return 'Basic ' + new Buffer(String(username) + ':' + pw).toString('base64');

src/util/fs.js
835:const cr = new Buffer('\r', 'utf8')[0];
836:const lf = new Buffer('\n', 'utf8')[0];
```

**What is the expected behavior?**

`yarn` should not use deprecated/unsafe `Buffer` constructor. According to the deprecation warning `new Buffer()` should be replaced with one of `Buffer.alloc()`, `Buffer.allocUnsafe()` or `Buffer.from()`; the [`safe-buffer`](https://yarn.pm/safe-buffer) package is another option.

**Please mention your node.js, yarn and operating system version.**

```
$ node -v
v8.9.4

$ yarn -v
1.5.1

$ uname -a
Linux 4.15.6-300.fc27.x86_64 #1 SMP Mon Feb 26 18:43:03 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by aduh95**
**Summary**

Fixes #5477 and #5704.

Remove usager of deprecated `Buffer`constructor to avoid ugly warnings on Node 10.

**Test plan**

Existing test should pass.

### CODE REVIEW

**Comment by aduh95** [comment]
In order to merge this PR, it needs to be reviewed first, and I believe anyone in the community can do it (but me, because I am the author).

File: src/util/fs.js [hunk 1]
```diff
@@ -767,8 +767,8 @@ export function normalizeOS(body: string): string {
   return body.replace(/\r\n/g, '\n');
 }
 
-const cr = new Buffer('\r', 'utf8')[0];
```
Comment (BYK) [inline src/util/fs.js]: lol

**Comment by felixrabe** [comment]
Thanks!

As a workaround before the next release of Yarn, I've created a `~/bin/node` script that comes before (Homebrew-installed) `/usr/local/bin/node` in my `$PATH`:

    #!/bin/bash

    /usr/local/bin/node --no-deprecation "$@"

**Comment by tusharmath** [comment]
Has this been release?

**Comment by samtheson** [comment]
Great work on having this out of the way. Any news on a release with the fix? Hit pretty hard, and as more people update their npm the cats will rain harder.

**Comment by BYK** [comment]
@tusharmath @samtheson you can follow #5769 for the final Node 10 fix. We'll release a new version as soon as we merge that.
