### PR TITLE
modify git ref parsing to not error on non-matching lines

### LINKED ISSUE #3325: yarn installation of self hosted git+ssh repos fail when there's a message returned from gitlab
yarn 0.23.4
macOs 10.12.4

When working with a "self-hosted" gitlab repo (such as talked about in #513), there's a case where gitlab is setup to output a warning message before returning the contents.

In certain settings gitlab server could possibly return a header prior to every interaction like:

```
*******************************************
Matt's Gitlab server, proceed at your own risk
*******************************************
abcde1234 refs/heads/blah
bdbadf4321 refs/heads/blah2
```

In these cases the following error is seen:

     TypeError: Cannot read property 'split' of undefined

When using a git+ssh://git@something/... etc. url

Stack trace:

```
at Function.parseRefs (...node/v6.10.3/lib/node_modules/yarn/lib/util/git.js:519:20)
at ...node/v6.10.3/lib/node_modules/yarn/lib/util/git.js:450:24
at next (native)
at step (node/v6.10.3/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30
at node/v6.10.3/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
at process._tickCallback (internal/process/next_tick.js:109:7)
```

### PR DESCRIPTION
**Pull request by rally25rs**
**Summary**

Fixes #3325 

Modified the parsing of Git ref lines to check it against a regexp before assuming the input line is a reference.
Since I was now using a regexp, I also use capture groups to extract the tag name and sha hash, insted of hte old implementation that was using string splits.

**Test plan**

Added unit tests for `Git.parseRefs()` to `__tests__/util/git.js`

### CODE REVIEW

File: src/util/git.js [hunk 1]
```diff
@@ -434,14 +439,21 @@ export default class Git {
...
+      if (match) {
+        const [, sha, tagName] = match;
 
-      refs[name] = sha;
+        // As documented in gitrevisions:
+        //   https://www.kernel.org/pub/software/scm/git/docs/gitrevisions.html#_specifying_revisions
+        // "A suffix ^ followed by an empty brace pair means the object could be a tag,
+        //   and dereference the tag recursively until a non-tag object is found."
+        // In other words, the hash without ^{} is the hash of the tag,
+        //   and the hash with ^{} is the hash of the commit at which the tag was made.
```
Comment (TimvdLippe) [inline src/util/git.js]: TIL, great description!

Comment (rally25rs) [inline src/util/git.js]: haha thanks, I figured it was better than the old code which was "// TODO: find out why this is necessary. idk it makes it work..." 😆

**Comment by bestander** [comment]
Thanks, @rally25rs!

**Comment by mmucklo** [comment]
Seems to have fixed the issue.
