### PR TITLE
Remove failed to install optional modules from node_modules

### LINKED ISSUE #2274: optional dependencies that fail builds should be removed from node_modules
**Do you want to request a *feature* or report a *bug*?**

feature/bug

**What is the current behavior?**

Optional Dependencies are first linked (files are copied from cache to node_modules) and then their install scripts are executed.
If install script fails this is considered OK but node_modules then has a half built folder.

**If the current behavior is a bug, please provide the steps to reproduce.**

I created test `optional dependency that fails build should still be installed` in integration.js that covers current behavior but I think it should be changed.

**What is the expected behavior?**

I think Yarn should remove failed to install optional modules from node_modules.

**Please mention your node.js, yarn and operating system version.**

Yarn 0.18.0

### PR DESCRIPTION
**Pull request by lgeiger**
**Summary**

> Optional Dependencies are first linked (files are copied from cache to node_modules) and then their install scripts are executed.
If install script fails this is considered OK but `node_modules` then has a half built folder.

Yarn now removes failed to install optional modules from `node_modules`.

Addresses #2274

**Test plan**

I manually tested this PR and it works as expected.
~~Unfortunately the integration tests fail but I can't figure out why. Any help would be really appreciated.~~ The integration tests have been adjusted accordingly.

### CODE REVIEW

File: __tests__/commands/install/integration.js [hunk 1]
```diff
@@ -764,18 +764,18 @@ if (process.platform !== 'darwin') {
...
 
+// Covers current behavior, issue opened whether this should be changed https://github.com/yarnpkg/yarn/issues/2274
 test.concurrent('a subdependency of an optional dependency that fails should be installed',
   (): Promise<void> => {
-    return runInstall({}, 'should-install-failing-optional-sub-deps', async (config) => {
-      assert.ok(await fs.exists(path.join(config.cwd, 'node_modules', 'optional-failing')));
-      assert.ok(await fs.exists(path.join(config.cwd, 'node_modules', 'sub-dep')));
+    return runInstallWithoutCheck({}, 'should-install-failing-optional-sub-deps', (config) => {
+      assert.equal(fsNode.existsSync(path.join(config.cwd, 'node_modules', 'optional-failing')), false);
+      assert.equal(fsNode.existsSync(path.join(config.cwd, 'node_modules', 'sub-dep')), true);
```
Comment (lgeiger) [inline __tests__/commands/install/integration.js]: Sub-dependencies only required by the failing module still aren't deleted.

File: __tests__/commands/install/integration.js [hunk 2]
```diff
@@ -764,18 +764,18 @@ if (process.platform !== 'darwin') {
...
 }
 
-// Covers current behavior, issue opened whether this should be changed https://github.com/yarnpkg/yarn/issues/2274
-test.concurrent('optional dependency that fails to build should still be installed',
+test.concurrent('optional dependency that fails to build should not be installed',
   (): Promise<void> => {
-    return runInstall({}, 'should-install-failing-optional-deps', async (config) => {
-      assert.ok(await fs.exists(path.join(config.cwd, 'node_modules', 'optional-failing')));
+    return runInstallWithoutCheck({}, 'should-not-install-failing-optional-deps', (config) => {
+      assert.equal(fsNode.existsSync(path.join(config.cwd, 'node_modules', 'optional-failing')), false);
```
Comment (bestander) [inline __tests__/commands/install/integration.js]: Why did you switch to `existsSync` from await `fs.exists`?

File: __tests__/commands/_helpers.js [hunk 3]
```diff
@@ -28,6 +28,18 @@ export const runInstall = run.bind(
   [],
 );
 
+export const runInstallWithoutCheck = run.bind(
```
Comment (bestander) [inline __tests__/commands/_helpers.js]: Why would you need install without check?

File: __tests__/commands/install/integration.js (hunk 2 above)
Comment (lgeiger) [inline __tests__/commands/install/integration.js]: I did it primarily out of two reasons:
1. If I recall correctly `fs.exists` throws if the path is empty
2. `fs.exists` is deprecated while `fs.existsSync` isn't

File: __tests__/commands/_helpers.js (hunk 3 above)
Comment (lgeiger) [inline __tests__/commands/_helpers.js]: Since the `optional-failing` module will be removed from `node_modules`, `check` will fail.

Comment (bestander) [inline __tests__/commands/_helpers.js]: That might be a problem, check should not fail after a correct install

Comment (lgeiger) [inline __tests__/commands/_helpers.js]: Oh I see. So just removing the folder from `node_modules` isn't enough and will cause check to fail since the module isn't installed.

File: __tests__/commands/install/integration.js (hunk 2 above)
Comment (lgeiger) [inline __tests__/commands/install/integration.js]: The wrapped method uses Node's `fs.exists` underneath which is deprecated: https://nodejs.org/api/fs.html#fs_fs_exists_path_callback

That said I'm happy to change it for consistency 👍

**Comment by bestander** [comment]
I suppose there needs to be a fix in Check that would ignore optional deps
if they are missing

File: __tests__/commands/install/integration.js (hunk 2 above)
Comment (bestander) [inline __tests__/commands/install/integration.js]: Thanks, I did not know that.
We'll probably do a one-off codemod to change to fs.access everywhere

**Comment by rgbkrk** [comment]
What's reflected in the `yarn.lock` if the optional dependency is not kept?

**Comment by bestander** [comment]
Lock file represents full dependency graph.
If you install with --production it will still contain dev dependencies.
Same thing for failed optional dependencies

**Comment by rgbkrk** [comment]
Ok, that makes sense since many times the optional dependencies are platform specific modules (darwin, windows, linux, etc.). Thanks @bestander and @lgeiger!
