### PR TITLE
fix(run): Fix script running in paths with special chars

### LINKED ISSUE #5479: "Couldn't find the binary sh" with yarn 1.5.1
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
I get this installing our yarn packages., With yarn 1.3.2 it was working fine. This is on a linux box. On my windows box it works fine.

```
2018-03-07 11:43:17 gobuilds.Compile : [INFO] yarn install v1.5.1
2018-03-07 11:43:17 gobuilds.Compile : [INFO] [1/4] Resolving packages...
2018-03-07 11:43:18 gobuilds.Compile : [INFO] [2/4] Fetching packages...
2018-03-07 11:43:31 gobuilds.Compile : [INFO] info fsevents@1.1.3: The platform "linux" is incompatible with this module.
2018-03-07 11:43:31 gobuilds.Compile : [INFO] info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
2018-03-07 11:43:31 gobuilds.Compile : [INFO] [3/4] Linking dependencies...
2018-03-07 11:43:37 gobuilds.Compile : [INFO] [4/4] Building fresh packages...
2018-03-07 11:43:38 gobuilds.Compile : [ERROR] error An unexpected error occurred: "/build/mts/release/sb-14177014/vcac/core/branding/navigation/node_modules/webpack/node_modules/uglifyjs-webpack-plugin: Couldn't find the binary sh".
2018-03-07 11:43:38 gobuilds.Compile : [INFO] info If you think this is a bug, please open a bug report with the information provided in "/build/mts/release/sb-14177014/vcac/core/branding/navigation/yarn-error.log".
2018-03-07 11:43:38 gobuilds.Compile : [INFO] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
2018-03-07 11:43:38 gobuilds.Compile : [INFO] info This module is OPTIONAL, you can safely ignore this error
2018-03-07 11:43:38 gobuilds.Compile : [ERROR] warning Error running install script for optional dependency: "/build/mts/release/sb-14177014/vcac/core/branding/navigation/node_modules/node-sass: Couldn't find the binary sh"
2018-03-07 11:43:38 gobuilds.Compile : [INFO] info This module is OPTIONAL, you can safely ignore this error
2018-03-07 11:43:38 gobuilds.Compile : [ERROR] warning Error running install script for optional dependency: "/build/mts/release/sb-14177014/vcac/core/branding/navigation/node_modules/uws: Couldn't find the binary sh"
```

**If the current behavior is a bug, please provide the steps to reproduce.**

running 'yarn install'. With yarn 1.3.2 it is working fine. All I did was replace to yarn 1.5.1

**What is the expected behavior?**

Expect to install packages

**Please mention your node.js, yarn and operating system version.**

Node 8.9.4
Yarn 1.5.1
Linux

### LINKED ISSUE #5481: Yarn 1.5.1 breaks on directories with special characters like ( )
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug.

**What is the current behavior?**
When you run "yarn webpack" in a directory that contains braces (For example: "C:\Dev\Trunk (Build 1)\Webpack") the command gets cut off at the first brace.

**If the current behavior is a bug, please provide the steps to reproduce.**
1) Create a directory with braces in it
2) Try to run a command in this directory (Like 'yarn webpack')

Here is the yarn-error.log:
[yarn-error.log](https://github.com/yarnpkg/yarn/files/1792299/yarn-error.log)

This is the output on the console (Sorry about the German):
`PS C:\Dev\syneris_trunk\Web (test 1)> yarn webpack
yarn run v1.5.1
$ "C:\Dev\syneris_trunk\Web (test 1)\node_modules\.bin\webpack"
Der Befehl "C:\Dev\syneris_trunk\Web" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: C:\\WINDOWS\\system32\\cmd.exe
Arguments: /d /s /c \"C:\\Dev\\syneris_trunk\\Web (test 1)\
ode_modules\\.bin\\webpack\"
Directory: C:\\Dev\\syneris_trunk\\Web (test 1)
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Dev\\syneris_trunk\\Web (test 1)\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.` (You can see it cuts the command off right after "Web " where the opening brace starts)

**What is the expected behavior?**
It should fully parse the command with the path intact, like it did on yarn version 1.3.2. This bug unfortunately broke our Jenkins builds.

**Please mention your node.js, yarn and operating system version.**
Node v.9.5.0
Yarn 1.5.1
Windows 10 64-bit

### PR DESCRIPTION
**Pull request by BYK**
**Summary**

Fixes #5481.

With #5133, we have stopped passing the command/script name to the shell properly. This patch makes
sure the proper escaping is done when not using the `script-shell` option.

This patch may also fix #5479.

**Test plan**

Added a new integration test.

### CODE REVIEW

File: __tests__/integration.js [hunk 1]
```diff
@@ -392,12 +392,31 @@ test('yarn run <script> <strings that need escaping>', async () => {
 
   const options = {cwd, env: {YARN_SILENT: 1}};
 
-  const trickyStrings = ['$PWD', '%CD%', '^', '!', '\\', '>', '<', '|', '&', "'", '"', '`', '  '];
+  const trickyStrings = ['$PWD', '%CD%', '^', '!', '\\', '>', '<', '|', '&', "'", '"', '`', '  ', '()'];
```
Comment (arcanis) [inline __tests__/integration.js]: Why does this string need to be added?

File: src/util/execute-lifecycle-script.js [hunk 2]
```diff
@@ -184,18 +184,7 @@ export async function executeLifecycleScript(
...
-  let sh = 'sh';
-  let shFlag = '-c';
-
-  let windowsVerbatimArguments = undefined;
-
-  if (customShell) {
-    sh = customShell;
-  } else if (process.platform === 'win32') {
-    sh = process.env.comspec || 'cmd';
-    shFlag = '/d /s /c';
```
Comment (arcanis) [inline src/util/execute-lifecycle-script.js]: Is it ok to remove these options? I have no idea what they do :/

`process.env.comspec` is also ignored with this PR

File: __tests__/integration.js (hunk 1 above)
Comment (BYK) [reply __tests__/integration.js]: Because parenthesis are also special characters and we were not testing them. We don't have to add it for this specific PR tho.

File: src/util/execute-lifecycle-script.js (hunk 2 above)
Comment (BYK) [reply src/util/execute-lifecycle-script.js]: Yes, the `shell: true` option takes care of all this. Please see #5133 which kind of undid what we already had here.

File: __tests__/integration.js (hunk 1 above)
Comment (arcanis) [reply __tests__/integration.js]: Shouldn't they be in separate string? `'(', ')'`?

File: src/util/execute-lifecycle-script.js (hunk 2 above)
Comment (arcanis) [reply src/util/execute-lifecycle-script.js]: Yeah but you also removed those options from the path that doesn't use `shell: true`, cf https://github.com/yarnpkg/yarn/pull/5484/files#diff-939cc0d319704d4f0d98baf9167ba850R212

Comment (arcanis) [reply src/util/execute-lifecycle-script.js]: Nevermind I'm tired

File: __tests__/integration.js (hunk 1 above)
Comment (BYK) [reply __tests__/integration.js]: Sure :)

Comment (BYK) [reply __tests__/integration.js]: Done!
