### PR TITLE
fix: handle npm prefix config environment variables

### LINKED ISSUE #4682: Underscore prefixed config (_auth) provided by env var is converted to dash (-auth)
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
npm config that have a `_` prefix (`_auth`, `_authToken`, `_password`), when provided as environment variables (`export npm_config__auth=blah`) have their `_` prefix converted to `-` (`-auth` instead of `_auth` for example).

**If the current behavior is a bug, please provide the steps to reproduce.**
```
npm_config__auth=abc yarn config get _auth
undefined

npm_config__auth=abc yarn config list | grep abc
  '-auth': 'abc' }
```

**What is the expected behavior?**
The npm config which start with `_` have their prefix untouched (`npm_config__auth` -> `_auth`)

**Please mention your node.js, yarn and operating system version.**
yarn 1.1.0 and 1.2.0
node 6.11.4
debian jessie

### PR DESCRIPTION
**Pull request by NicholasBoll**
Fixes #4682

**Summary**

Passing `npm_config_` environment variables changed all underscores (`_`) to dashes (`-`) which isn't correct behavior for special config variables (`_auth`, `_authToken`, `_username` and `_password`). An additional check was added to `base-registry.js` to filter out these config keys from this processing.

**Test plan**

`yarn test` - all tests passed except two tests that have nothing with my change - they are integration tests (I assume my environment isn't set up correctly for these to pass? Maybe CI will verify?)

### CODE REVIEW

File: src/registries/base-registry.js [hunk 1]
```diff
@@ -171,7 +171,9 @@ export default class BaseRegistry {
       key = key.replace(/__/g, '.');
 
       // replace underscores with dashes
-      key = key.replace(/_/g, '-');
```
Comment (arcanis) [inline src/registries/base-registry.js]: Can you instead add it in a more generic way that supports `__`?

For example: `key.replace(/([^_])_/g, '$1-')`

Comment (NicholasBoll) [reply src/registries/base-registry.js]: That's a good idea. We're probably assuming any key starting with an underscore needs to stay an underscore, but that's probably always true

File: __tests__/registries/npm-registry.js [hunk 2]
```diff
@@ -731,6 +731,37 @@ describe('isScopedPackage functional test', () => {
...
+    delete process.env.npm_config__auth;
+    delete process.env.npm_config__authToken;
+    delete process.env.npm_config__username;
+    delete process.env.npm_config__password;
+  });
+
+  test('correctly escapes environment config variables', () => {
+    const testCwd = '.';
+    const {mockRequestManager, mockRegistries, mockReporter} = createMocks();
+    const npmRegistry = new NpmRegistry(testCwd, mockRegistries, mockRequestManager, mockReporter, true, []);
```
Comment (NicholasBoll) [inline __tests__/registries/npm-registry.js]: I had trouble figuring out where these tests should go. `mergeEnv` is an instance method that requires a whole mocked registry to test.

Simplifying this test would involve refactoring the `mergeEnv` method to use a utility method, but I decided to reduce the changes to the code and instead have a more complicated test

File: src/registries/base-registry.js (hunk 1 above)
Comment (NicholasBoll) [reply src/registries/base-registry.js]: @arcanis Are the changes satisfactory?

**Comment by arcanis** [comment]
Yep! Thanks 😃
